### ISSUE TITLE
slack 404

### ISSUE THREAD

**Issue by tobz-nz** [ansible/ansible-modules-extras#100]
I'm getting the same issue as was reported here: https://github.com/ansible/ansible/issues/8669

Error output I'm getting is:

```
failed: [test-domain.com -> 127.0.0.1] => {"failed": true}
msg:  failed to send payload={"username": "toby", "text": "stage update has successfully completed", "link_names": 1, "channel": "#deploys", "icon_url": "http://www.ansible.com/favicon.ico"} to https://pixelfusion.slack.com/services/hooks/incoming-webhook?token=[obscured]: HTTP Error 404: Not Found
```

**Comment by lucidaeon** [comment]
For what it's worth, you'll get the exact same 404 response if the integration was created and subsequently disabled.

**Comment by stefanhorning** [comment]
Same here, while the request is working with curl, using latest module from devel branch. Using the https://hooks.slack.com/services/ endpoint

**Comment by stefanhorning** [comment]
nevermind, was just a typo in the channel name.

**Comment by rolindroy** [comment]
Hi, I am still getting this issue. Ansible version 2.1.1.0

Error : fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": " failed to send payload={\"username\": \"Ansible\", \"text\": \"Test Message\", \"link_names\": 1, \"icon_url\": \"http://www.ansible.com/favicon.ico\"} to https://hooks.slack.com/services/[obscured]: HTTP Error 404: Not Found"}

   tasks:
    - name: "It should arrive in the channel set in slack integration"
      local_action:
        module: slack
        token: XXXXX/YYYYY/ZZZZZZZZZZZZZ
        msg: "Test Message"

How do I fix this issue ?

**Comment by mmochan** [comment]
I am also getting this in Ansible version 2.1.1.0
