### ISSUE TITLE
pam_limits: value 'unlimited' isn't accepted

### ISSUE THREAD

**Issue by tomjakubowski** [ansible/ansible-modules-extras#1033]
If I try to use `'unlimited'` as the `value` argument to the `pam_limits` module, I get this error:

```
ValueError: invalid literal for int() with base 10: 'unlimited'
```

**Comment by tomjakubowski** [comment]
I believe also that an existing `unlimited` value in the `limits.conf` file will cause an error here: https://github.com/ansible/ansible-modules-extras/blob/bc07c3b504eb5370b1a6e7db8864b6ac5b8bcaea/system/pam_limits.py#L184

**Comment by robynbergeron** [comment]
[module: system/pam_limits.py]

**Comment by robynbergeron** [comment]
Hi @tomjakubowski -- thanks for submitting this bug report.

@usawa -- pinging you to let you know about this bug report for pam_limits.py.

**Comment by machacekondra** [comment]
Hi @tomjakubowski patch which fix this issue was merged, you can try if it works OK for you, now.

**Comment by tomjakubowski** [comment]
:+1: thanks!
