### ISSUE TITLE
Modules missing EXAMPLES

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-modules-extras#1061]
The following modules are missing an `EXAMPLES` section:
- cloud/amazon/route53_zone.py @minichate
- windows/win_iis_virtualdirectory.py @whenrik

Please send PRs to include the `EXAMPLES` section.  For more information see:

http://docs.ansible.com/ansible/developing_modules.html#example

**Comment by henrikwallstrom** [comment]
We will have a look at it :)
