### ISSUE TITLE
mysql_replication fails. New modes not added to supported mode dict

### ISSUE THREAD

**Issue by luiseterc** [ansible/ansible-modules-extras#1067]
New modes added to mysql_replication module (resetslave and resetslaveall) were not added to the supported mode dictionary which causes the module to fail when using these new options.

mode=dict(default="getslave", choices=["getmaster", "getslave", "changemaster", "stopslave", "startslave"]),

**Comment by robynbergeron** [comment]
[module: database/mysql/mysql_replication.py]

**Comment by robynbergeron** [comment]
@luiseterc -- thanks for filing this bug report.

@banyek -- pinging you here to let you know about this bug report, will be pinging in the associated PR as well for review.

**Comment by Jmainguy** [comment]
@luiseterc Since #1068 was merged, is this good to close?

**Comment by luiseterc** [comment]
Sure, let's close it please.

Thank you

**Comment by bcoca** [comment]
closing as per above
