### ISSUE TITLE
win_package: The variable '$script:MsiTools' cannot be retrieved because it has not been set.

### ISSUE THREAD

**Issue by darrengruber** [ansible/ansible-modules-extras#1073]
##### Ansible Version:

```
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/08 14:32:55 (GMT -400)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/08 14:31:12 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/08 14:31:24 (GMT -400)
  config file =
  configured module search path = None
```
##### Ansible Configuration:

N/A
##### Environment:

Managing from: `OSX 10.10.5`
Managing to: `Microsoft Windows NT 6.2.9200.0 (Microsoft Windows Server 2012 Standard)`
##### Summary:

Attempts to install an .msi from a URL using `win_package` will result in an error.
##### Steps To Reproduce:
- Create a playbook with this task defined on it:  

```
    - name: Install Microsoft ReportViewer 2012 Runtime
      win_package:
        path: http://download.microsoft.com/download/F/B/7/FB728406-A1EE-4AB5-9C56-74EB8BDDF2FF/ReportViewer.msi
        product_id: "{DFDB4411-54A2-41CE-AB89-CE54C176A69D}"
```
- Run this task against a Windows Server 2012 Standard host.
##### Expected Results:

When given a working URL for download along with its corresponding `product_id`, ansible will download and install this package in an idempotent manner.
##### Actual Results:

Task fails with the following error:

```
TASK [Install Microsoft® ReportViewer 2012 Runtime] ****************************
fatal: [IP]: FAILED! => {"changed": false, "failed": true, "msg": "System.Management.Automation.RuntimeException: The variable '$script:MsiTools' cannot be retrieved because it has not been set.\r\n   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)\r\n   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)\r\n   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)\r\n   at System.Management.Automation.CommandProcessorBase.Complete()", "name": "http://download.microsoft.com/download/F/B/7/FB728406-A1EE-4AB5-9C56-74EB8BDDF2FF/ReportViewer.msi"}
```
##### Pure Speculation

Maybe `Get-MsiTools` in `lib/ansible/modules/extras/windows/win_package.ps1` is never invoked?

**Comment by robynbergeron** [comment]
Hi @darrengruber -- thanks for submitting this bug report. 

@trondhindenes -- pinging you to let you know about this bug report for the win_package module. Thanks for your ongoing maintenance and love to this module :)

**Comment by robynbergeron** [comment]
[module: windows/win_package.py]

**Comment by trondhindenes** [comment]
This is related to the Set-Strictmode change that was done (which I still am very much against). We're gonna have lots of bugs like this pouring in over the course of the next few months (or longer, depending on usage). In any case, I'll take a look at this particular module and make the necessary changes.

**Comment by darrengruber** [comment]
You guys work quick! Thanks for taking a look!

**Comment by trondhindenes** [comment]
@darrengruber I'm not getting the same error as you are. I'm getting this:

FAILED! => {"changed": false, "failed": true, "msg": "System.ArgumentException: The specified Name (http://download.microsoft.com/download/F/B/7/FB728406-A1EE-4AB5-9C56-74EB8BDDF2FF/ReportViewer.msi) and IdentifyingNumber ({DFDB4411-54A2-41CE-AB89-CE54C176A69D}) do not match Name (Microsoft Report Viewer 2012 Runtime) and IdentifyingNumber ({C58378BC-0B7B-474E-855C-9D02E5E75D71}) in the MSI file", "name": "http://download.microsoft.com/download/F/B/7/FB728406-A1EE-4AB5-9C56-74EB8BDDF2FF/ReportViewer.msi"}

This indicates that the product id specified does not match the one specified in the msi. Could you please provide:
-Ansible version (if running from source please provide tag or checkout id)
-Exact OS version of target node
-Exact PowerShell version of target node (essentially the values from $psversiontable)

**Comment by trondhindenes** [comment]
Bugfix PR #1076
@darrengruber if you'd like to test the revised version straigt away I'd be more than happy to get feedback on it. You would have to use this one:https://github.com/trondhindenes/ansible-modules-extras/blob/win_package_bugfix/windows/win_package.ps1

Also, it looks like you're trying to use the wrong product id. Ansible will now fail with a more humane message if that happens. Furthermore I was getting a 1603 which means that the msi has unfulfilled dependencies. This turned out to be the SQL CRL types package. Here's the playbook that worked for me:

```
  - name: Install Microsoft CRL thungy
    win_package:
      path=http://download.microsoft.com/download/F/E/D/FEDB200F-DE2A-46D8-B661-D019DFE9D470/ENU/x64/SQLSysClrTypes.msi
      product_id="{F1949145-EB64-4DE7-9D81-E6D27937146C}"

  - name: Install Microsoft ReportViewer 2012 Runtime
    win_package:
      path=http://download.microsoft.com/download/F/B/7/FB728406-A1EE-4AB5-9C56-74EB8BDDF2FF/ReportViewer.msi
      product_id="{C58378BC-0B7B-474E-855C-9D02E5E75D71}"
```

**Comment by trondhindenes** [comment]
@robynbergeron we can probably go ahead and close this out. Assuming the fix worked.
