### ISSUE TITLE
Firewalld traces with ALREADY_ENABLED when using port name or re-ordered rich rule

### ISSUE THREAD

**Issue by ag-wood** [ansible/ansible-modules-extras#1080]
Fails when using a port name (e.g. http) instead of a number or if a rich rule is in the incorrect order (e.g. rich_rule='rule family="ipv4" source address="192.168.1.50" port protocol="tcp" port="80" accept').

Both of the above situations result in  a stack trace that includes:
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: ALREADY_ENABLED

**Comment by robynbergeron** [comment]
Hi @ag-wood -- thanks for the bug report (and the PR!). 

pinging @maxamillion to let you know about this issue (and the PR, but will be pinging you there as well.)

**Comment by robynbergeron** [comment]
[module: system/firewalld.py]

**Comment by mscherer** [comment]
PR was merged, so closing this bug

**Comment by bdgscotland** [comment]
I think i've recreated this bug still..
Does not cause it:
  xxx_xxx_xxx: "{{ lookup('dig', 'xxx-xxx-xxx') }}"
  ...
  rule: 'rule family="ipv4" source address="{{ xxx_xxx_xxx }}/32" destination address="{{ server_ip.stdout }}/32" port port="24007-24010" protocol="tcp" accept'

Does cause it:
  rule: "rule family='ipv4' source address='{{ hostvars[\"xxx-xxx-xxx\"][\"ansible_default_ipv4\"][\"address\"] }}/32' destination address='{{ server_ip.stdout }}/32' port port='24007-24010' protocol='tcp' accept"

Whether it's using the predefined variable or the in-line fact does not matter. It's the inversion of quotes that causes it.

**Comment by mscherer** [comment]
Could you open a new issue, as I think it will make easier for tracking ?

(and so you also get a free chance to fix formatting)

**Comment by bdgscotland** [comment]
Sure, I'll do this when I get back 

On May 17, 2016, at 15:46, Michael Scherer notifications@github.com wrote:

Could you open a new issue, as I think it will make easier for tracking ?

(and so you also get a free chance to fix formatting)
