### ISSUE TITLE
s3 module: error message unclear if you download multipart s3 objects and dest=/folder

### ISSUE THREAD

**Issue by volker-fr** [ansible/ansible-modules-extras#1095]
If you download a uploaded file with the s3 module the destination needs to be a file. If you set `dest=/folder` and the file is a multipart upload, the error message is misleading.

This task

```
- s3: bucket=mybucket object=/my/desired/key.txt dest=/usr/local/myfolder mode=get
```

will result in a unclear error

```
msg: Files uploaded with multipart of s3 are not supported with checksum, unable to compute checksum.
```

while

```
- s3: bucket=mybucket object=/my/desired/key.txt dest=/usr/local/myfile.txt mode=get
```

works as expected without any errors.

The core issue here is that the s3 object is a multipart upload and ansible can't handle it (see #5442 which has the same error message).

If the s3 object is a "single part" upload the error message you will get when using `dest=/folder` is obvious and will result in a `IOError: [Errno 21] Is a directory: '/folder'` output

**Comment by wimnat** [comment]
The s3 module is a core module so you might want to recreate this issue in the ansible-modules-core repo
