### ISSUE TITLE
mongodb_user works incorrectly with old pymongo

### ISSUE THREAD

**Issue by senz** [ansible/ansible-modules-extras#11]
##### Environment:

OSX 10.7 -> Ubuntu precise
##### Summary:

mongodb_user works incorrectly with old pymongo (~2.1). 
Tested with 2.7.2, work correctly.
##### Steps To Reproduce:
- Fresh mongo instance with auth enabled, no users
- ansible host  -m mongodb_user -a "database=admin user=test roles=root password=test state=present"
##### Expected Results:

Creates new user
##### Actual Results:

Changed = false

This code block supposed to fail on non-existant user:

```
        try:
           client[db_name].authenticate(user, password)
           if state == 'present':
              module.exit_json(changed=False, user=user)
        except OperationFailure:
           if state == 'absent':
              module.exit_json(changed=False, user=user)
```

But it is exiting correctly and continue. 
### Old issue

https://github.com/ansible/ansible/issues/8899

**Comment by dopry** [comment]
I am experiencing the same behavior on Debian 7.5 using python-pymongo install from apt. 

Ansible reports no change and no error and the user is not created. 

I was able to work around the issue by upgrading pymongo with pip. 

```
sudo apt-get install python-pip
sudo pip install --upgrade pymongo
```

**Comment by bcoca** [comment]
we probably just need to add lib version detection and an alternate method

**Comment by gregdek** [comment]
@senz @dopry Thanks for submitting this bug report. Apologies for taking so long to triage it. Since this bug has been open for a while, we would appreciate if you can verify if you are still seeing the reported behavior in the latest version.

If you are seeing the reported behavior, just let us know and we will leave the bug open and notify the module maintainer.

If you are no longer seeing the reported behavior, please let us know and we will close the bug report.

**Comment by gregdek** [comment]
[module: database/misc/mongodb_user.py]

**Comment by Lujeni** [comment]
### Environment

ansible version: 1.9.4
pymongo: 2.1.1
mongodb: 3.0.7

### Test

``` bash
(ansible-modules-extras-11) ✘-1 ~/works/pew/project/ansible-modules-extras-11 
23:34 $ ansible localhost -i localhost,  -m mongodb_user -a "database=admin user=test roles=root password=test state=present" --user julien --ask-pass
SSH password: 
localhost | success >> {
    "changed": true,
    "user": "test"
}

# mongodb
> use admin
switched to db admin
> db.getUsers()
[
        {
                "_id" : "admin.test",
                "user" : "test",
                "db" : "admin",
                "roles" : [
                        {
                                "role" : "root",
                                "db" : "admin"
                        }
                ]
        }
]

```
- @senz @dopry @gregdek This bug seems fixed with the current version.
