### ISSUE TITLE
win_webpicmd fails with strict mode errors

### ISSUE THREAD

**Issue by bgeihsgt** [ansible/ansible-modules-extras#1101]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

```
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/13 06:57:44 (GMT +000)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/13 06:57:49 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/13 06:58:00 (GMT +000)
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = /vagrant/ansible/library
```
##### Ansible Configuration:

I haven't changed anything that affects this module.
##### Environment:

Running from Ubuntu 14, managing Windows Server 2012 R2.
##### Summary:

win_iis_webpicmd fails with property error when doing any operation
##### Steps To Reproduce:
- Use webpicmd to install any package
##### Expected Results:

It successfully installs the package.
##### Actual Results:

It does not install the package and fails with an error that 'length' does not exist on the object.  Pull request fixing this incoming.

**Comment by robynbergeron** [comment]
Hi @bgeihsgt -- thanks for filing this bug report (and for the accompanying PR in #1102 :D)

@petemounce - thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by robynbergeron** [comment]
[module: windows/win_webpicmd.py]
