### ISSUE TITLE
The crypttab modules mangles names incorrectly

### ISSUE THREAD

**Issue by ozamosi** [ansible/ansible-modules-extras#1105]
##### Issue Type:
- Bug Report
##### Ansible Version:

2.0.0
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

The crypttab module mangles a lot of names.
##### Steps To Reproduce:

```
crypttab: name=my-luks-home state=present opts=discard,cipher=aes-cbc-essiv:sha256
```
##### Expected Results:

The luks volume `my-luks-home` is added to my crypttab file
##### Actual Results:

The non-existing volume `y-luks-home` is added to my crypttab file.

The module runs

```
name           = module.params['name'].lstrip('/dev/mapper')
```

which means any of the characters in the argument to `lstrip` will be removed from the beginning of the volume name.

**Comment by robynbergeron** [comment]
Hi @ozamosi -- thanks for this bug report, much appreciated.

@groks -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by robynbergeron** [comment]
[module: system/crypttab.py]

**Comment by mscherer** [comment]
Close the bug, since it was fixed (cf history )
