### ISSUE TITLE
win_regedit: Failure in parameter validation and in creating registry key

### ISSUE THREAD

**Issue by bgeihsgt** [ansible/ansible-modules-extras#1107]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

```
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/13 06:57:44 (GMT +000)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/13 06:57:49 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/13 06:58:00 (GMT +000)
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = /vagrant/ansible/library
```
##### Ansible Configuration:

I haven't changed anything that affects this module.
##### Environment:

Running from Ubuntu 14, managing Windows Server 2012 R2.
##### Summary:

Two issues: 
1. win_regedit fails with property error when parsing parameters
2. win_regedit fails to create a new registry key with a NonInteractiveMode error
##### Steps To Reproduce:
- Use win_regedit to create a new registry value in a new key
##### Expected Results:

It successfully creates the key
##### Actual Results:

It fails with strict mode errors when parsing parameters.  After moving the parameter parsing to use Get-Attr, it started failing saying you can't prompt in NonInteractiveMode.  Digging in, I saw that it was prompting for the Type parameter in the New-Item call to create the key.  I fixed this by prepending a "Registry::" before the path so Powershell knows it's a registry path.  Pull request coming shortly.

**Comment by robynbergeron** [comment]
@bgeihsgt -- Thanks for submitting this bug report, and the accompanying PR (#1108).

@smadam813 & @joshludwig --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module. Please note there is a PR addressing this issue.

**Comment by robynbergeron** [comment]
[module: windows/win_regedit.py]

**Comment by smadam813** [comment]
Will take a look!  Thanks for the bug submission!

**Comment by dreamcat4** [comment]
Hi there. I also found problems with this module accepting certain input values. Specifically when trying to set the `data:` or a registry key to be `0` or `false`, `no` or something like that. Then it gets confused and thinks the `data` param doesn't exist or wasn't set to any specific value.

The module is also _very slow_ to process any loop of multiple items using the outside looping of `with_items:`. As it re-uploads a new copy of the same script for setting each individual key. And each winrm file transfers are very slow.

**Comment by smadam813** [comment]
@dreamcat4 Have you tried after the changes in the pull request?  I did not notice issues that you are referring to when I tested.

To be explicit, you could trying wrapping your value in quotes within the playbook.  Let me know if that fixes the issue.

**Comment by dreamcat4** [comment]
@smadam813

Thanks! Indeed you are right - my git is now behind and not including those recent changes. Glad to hear there are some fixes ongoing. I can see the bit i had to change for the no-value data, and it's also been substantially changed in the ^^ above referenced commit. So probably fixed, sorry I haven't actually retest yet but it looks promising.

**Comment by dreamcat4** [comment]
@smadam813 I've been using these changes for a while now. It has solved my previous input validation problems and is working well.
