### ISSUE TITLE
FirewallD Module Fails with backtrace when firewalld cannot be contacted

### ISSUE THREAD

**Issue by lightblu** [ansible/ansible-modules-extras#1138]
**Issue Type:** Bug Report

**Ansible Version**:

```
ansible 2.0.0 (devel 6b419db9fa) last updated 2015/10/21 13:15:31 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dc51e1ae41) last updated 2015/10/21 13:15:36 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD eeeb1264d3) last updated 2015/10/21 13:15:36 (GMT +200)
```

**Environment:**
Ubuntu hosts managing Centos7 targets in multi-environment setups, some of these are Vagrant VMs.

**Summary**:
firewalld is disabled on our Vagrant VMs; there the firewalld tasks fail with a misguiding backtrace.

**Steps To Reproduce:**

```
ansible -m service -a "name=firewalld state=stopped" host1 
ansible -m firewalld -a "port=80/tcp state=enabled permanent=true" host1 
```

**Expected Results:**

Something more informative than the backtrace deep from Python.

**Actual Results:**

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 2366, in <module>
  File "<stdin>", line 278, in main
  File "<string>", line 2, in getDefaultZone
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 103, in _enable_proxy
    return func(*p, **k)
  File "<string>", line 2, in getDefaultZone
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1917, in getDefaultZone
    return dbus_to_python(self.fw.getDefaultZone())
AttributeError: 'NoneType' object has no attribute 'getDefaultZone'

fatal: [host]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

**Note**:
This report is an almost 1-to-1 copy from https://github.com/ansible/ansible/issues/6911 with the same fix. The patch (actually checking for fw.connected) was undone with https://github.com/ansible/ansible-modules-extras/commit/6f2b61d2d88294ea7938020183ea613b7e5e878d

**Comment by robynbergeron** [comment]
[module: system/firewalld.py]

**Comment by robynbergeron** [comment]
Hi @lightblu -- thanks for submitting this bug report.

@maxamillion -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module. :)
