### ISSUE TITLE
Modul "cpanm" not working

### ISSUE THREAD

**Issue by zwicky11** [ansible/ansible-modules-extras#1155]
I use user "root" with key-login - not using "sudo". If the perl package not installed and i try to install i get ever an error:
# Dancer = example, same problem with another perl packages (Net::IP , Config::Simple , Proc::PID::File )

i@ansible ~/ansible $ ansible -u root -m cpanm hostx.xyz.xx -a 'name="Dancer" notest=false'
hostx.xyz.xx | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1445785673.77-159715255447855/cpanm\", line 2100, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1445785673.77-159715255447855/cpanm\", line 179, in main\r\n    mirror_only, installdeps, cpanm)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1445785673.77-159715255447855/cpanm\", line 139, in _build_cmd_line\r\n    if use_sudo is True:\r\nNameError: global name 'use_sudo' is not defined\r\n", 
    "parsed": false
}

**Comment by zwicky11** [comment]
Manual installation on the server works perfect:

root@host120 ~ # cpanm Config::Simple Proc::PID::File
--> Working on Config::Simple
Fetching http://www.cpan.org/authors/id/S/SH/SHERZODR/Config-Simple-4.58.tar.gz ... OK
Configuring Config-Simple-4.58 ... OK
Building and testing Config-Simple-4.58 ... OK
Successfully installed Config-Simple-4.58
--> Working on Proc::PID::File
Fetching http://www.cpan.org/authors/id/E/EC/ECALDER/Proc-PID-File-1.27.tar.gz ... OK
Configuring Proc-PID-File-1.27 ... OK
Building and testing Proc-PID-File-1.27 ... OK
Successfully installed Proc-PID-File-1.27
2 distributions installed
root@hostx ~ #

**Comment by bcoca** [comment]
fixed via 08d89bca9ca539612943305d94946bf511daac3e
