### ISSUE TITLE
win_updates: win2008 + powershell 3 fails

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible-modules-extras#1167]
Hey,
i'm trying to execute updates via ansible, but the task is failing on win 2008 since the RunAsTask property / method is not defined.

there is already a logic for powershell v3, but the author does not check the version (If ($PSVersionTable.PSVersion.Major -gt 3)) but decided to check the property that colides with strict support on ansible 2.0

```
TASK [win_updates log_path=C:\Windows\Temp\ansible-updates.log status=searched category_names=[u'Application', u'Connectors', u'CriticalUpdates', u'DefinitionUpdates', u'DeveloperKits', u'FeaturePacks', u'Guidance', u'SecurityUpdates', u'ServicePacks', u'Tools', u'UpdateRollups', u'Updates']] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +      ~~~~~~~~~~~~~~~~~~~
fatal: [XXXXXXXXX]: FAILED! => {"changed": false, "failed": true, "msg": "Die Eigenschaft \"RunAsTask\" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass sie vorhanden ist."}
```

**Comment by h0nIg** [comment]
what do you think @nitzmahone @petemounce ?

**Comment by nitzmahone** [comment]
Yeah, I developed/tested this before the strict mode change went in, and we don't have CI running tests for this module yet. I'd still rather be explicit about checking for the existence of the method rather than checking the PS version, though. I'll PR a fix...

**Comment by nitzmahone** [comment]
Fixed: https://github.com/ansible/ansible-modules-extras/pull/1172
