### ISSUE TITLE
npm module does not update packages when state=latest

### ISSUE THREAD

**Issue by mattwwarren** [ansible/ansible-modules-extras#1184]
There is a [function in npm.py](https://github.com/ansible/ansible-modules-extras/blob/devel/packaging/language/npm.py#L248) that executes an `npm update` but it does not appear to be used. Currently executing the following play will not update packages.

```
- npm: state=latest path={{ my_code_checkout }}
```

There is nothing obvious in the code to suggest the update function should not be used and making the change locally does fix the issue. I'm happy to make this change and a PR for it.

**Comment by robynbergeron** [comment]
[module: packaging/language/npm.py]

**Comment by robynbergeron** [comment]
@MattTheRat -- Thanks for submitting this bug report.

@chrishoffman -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by mattwwarren** [comment]
@robynbergeron what can I do to push this issue forward? It would appear the maintainer of the npm plugin is not active and there is an open pull request I can confirm fixes this.

Granted I've only been running it for a few days but it has not introduced any bugs. I'm happy to go through a more formal process and assume maintenance.

**Comment by offero** [comment]
Seconded. This is a simple change and is really messing with our deployment workflow. Please merge.

**Comment by bcoca** [comment]
closing via merged #446
