### ISSUE TITLE
iptables module : Use state instead of ctstate ?

### ISSUE THREAD

**Issue by romainrbr** [ansible/ansible-modules-extras#1209]
A few days ago @dvigueras added conntrack module ctstate support to the iptables module.

However, contrack has to be enabled on old kernels.
If we refer to this discussion : https://groups.google.com/forum/#!msg/VGLUG/A1VVZLrwudY/NaitoDnSPvkJ it seems that using :

```
-m state --state
```

Is actually translated into 

```
-m conntrack --ctstate
```

Shouldn't we replace "-m conntrack --ctstate" by "-m state --state" so we can cover the most cases ?

@bcoca, @LinusU .

**Comment by robynbergeron** [comment]
@romainrbr -- thanks for submitting this bug report / feature idea, and for the accompanying PR. :)

It looks like it's been merged, so I'll close this out. 

Cheers!

**Comment by robynbergeron** [comment]
[module: system/iptables.py]
