### ISSUE TITLE
Verbs change in Elasticsearch 2.0.0

### ISSUE THREAD

**Issue by omame** [ansible/ansible-modules-extras#1214]
Since Elasticsearch 2.0.0 `plugin` dropped the double-dash for verbs. So what used to be `--install` now became `install`. Hence, [this](https://github.com/ansible/ansible-modules-extras/blob/devel/packaging/elasticsearch_plugin.py#L114-L117) doesn't work with new versions.

**Comment by robynbergeron** [comment]
Hi @omame -- Thanks for submitting this bug report.

@ThePixelDeveloper -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by robynbergeron** [comment]
[module: packaging/elasticsearch_plugin.py]

**Comment by johnarnold** [comment]
FWIW I verified that removing the double-dashes from the module works with ES 2.0

**Comment by ThePixelDeveloper** [comment]
Alright, I'll take a look at it this week, thanks for bringing it to my attention.

**Comment by robynbergeron** [comment]
@ThePixelDeveloper -- thanks for the update, let us know when you have something ready. :)

**Comment by ThePixelDeveloper** [comment]
Sorry for the delay! Working on this now.

I'm not sure how to attack this issue, but I think I'm going to go with trying a version 2 install and falling back to a version 1 style. I don't believe adding a version argument would be good for the developer experience here, although I'm a bit unhappy with the solution I came up with still ... Suggestions appreciated, but shall have a PR ready soon.

**Comment by barryib** [comment]
Hello, for information, it's seem that `bin/plugin install [plugin_name]` works on ES 1.x and ES 2.x. See this [issue on ansible-elasticsearch](https://github.com/elastic/ansible-elasticsearch/issues/61).

I tested on ES 1.7.2 and it works.
