### ISSUE TITLE
win_regedit: can't remove registry entries following #1107

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible-modules-extras#1236]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (reg_merge_tests 7b83698ac2) last updated 2015/10/27 06:29:59 (GMT +100)

(yes this is a branch but the branch just adds integration tests, so likely the same on latest devel.
##### Ansible Configuration:

config file =
configured module search path = None
##### Environment:

Ansible Controller: Lubuntu 14.04
Targets:
Windows Server 2008 R2 (Powershell 3.0)
Windows Server 2012 R2 (Powershell 4.0)
##### Summary:

Since https://github.com/ansible/ansible-modules-extras/commit/c6a934d57b9d0b171ad6a4c45c14ca5087a941c0

It is not possible to remove registry entries using a key

I think pre-pending 'Registry::' to the registry key is some how causing Test-Path to fail.   Note that the example registry key has a space in the name.
##### Steps To Reproduce:

Add a registry key called 'Cow Corp' to  'HKLM:\SOFTWARE\Wow6432Node'

Run the following task in a playbook:

win_regedit:
  key: 'HKLM:\SOFTWARE\Wow6432Node\Cow Corp'
  state: absent
##### Expected Results:

win_regedit should report changed: true
##### Actual Results:

win_regedit reports changed: false

**Comment by jhawkesworth** [comment]
@smadam813 - can you spare any cycles to investigate?
cc ing @bgeihsgt for info/comment.

**Comment by robynbergeron** [comment]
[module: windows/win_regedit.py]

**Comment by robynbergeron** [comment]
@jhawkesworth -- Thanks for submitting this bug report.

@smadam813 @joshludwig --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module. And re-pinging @bgeihsgt as @jhawkesworth did originally :)

**Comment by smadam813** [comment]
Sorry for not stepping in earlier!  I have been crazy busy lately, so I will take a look as soon as I can.

**Comment by smadam813** [comment]
I submitted a pull request (#1286) which fixes this issue.  @jhawkesworth Please let me know if this fixes the issue for you!

**Comment by jhawkesworth** [comment]
To confirm here as well.. Yes https://github.com/ansible/ansible-modules-extras/pull/1286 fixes this issue.

Once https://github.com/ansible/ansible-modules-extras/pull/1286 has been merged this can be closed.

Many thanks everyone.
