### ISSUE TITLE
RiakCS bucket provisioning support

### ISSUE THREAD

**Issue by pmarques** [ansible/ansible-modules-extras#1251]
Hi, RiakCS uses S3 API but is not yet 100% compliant. I would like t discusse some changes that I have made to support RiakCS bucket provisioning:

RiakCS doesn't support versioning pays & it seems to not support tags and payments
- https://github.com/ansible/ansible-modules-extras/compare/devel...pmarques:s3_none_options

Suppoer proxy on S3 connection:
- https://github.com/ansible/ansible-modules-extras/compare/devel...pmarques:s3_bucket_proxy

I also had to import urlparse, but this got me confused, maybe an issue from my side
- https://github.com/ansible/ansible-modules-extras/compare/devel...pmarques:s3_import_url_parse

**Comment by pmarques** [comment]
Also due to other issue on RiakCS we need to force Content-Type when "putting" policy:
https://github.com/ansible/ansible-modules-extras/compare/devel...pmarques:s3_bucket_policy

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by pmarques** [comment]
Done: https://groups.google.com/forum/#!topic/ansible-project/jAjwDcmJhBA
