### ISSUE TITLE
Puppet module no stdout when rc=2

### ISSUE THREAD

**Issue by xavpaice** [ansible/ansible-modules-extras#1253]
I think it would be really helpful to capture stderr and stdout when the RC=2 from a Puppet run - currently the puppet module doesn't output this leaving us to scrape log files etc.

Easy change to L200, happy to submit PR if people agree this would be a good approach?

**Comment by tronicum** [comment]
I i try to run puppet it goes to that "check if puppet is disabled here" clause where it fails with that "elif rc !=0" check. I needed to remove that elif to get that puppet agent run working.

**Comment by xavpaice** [comment]
See https://github.com/ansible/ansible-modules-extras/pull/1260

**Comment by robynbergeron** [comment]
[module: system/puppet.py]

**Comment by robynbergeron** [comment]
@xavpaice Thanks for submitting this feature idea.

@emonty -- Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by robynbergeron** [comment]
@xavpaice -- note that this appears to be implemented in #1260, which was merged today -- you can probably give that a try and let us know if this can be closed out :)

@emonty -- this is likely already taken care of, as FYI :)

**Comment by tronicum** [comment]
No this merge just gives changes back to ansible but does not change the timeout problem. It is also not just a feature request (the timeout issue). Users with old Linux versions deployed can't use the module with the timeout binary requirement.

**Comment by xavpaice** [comment]
I really don't understand what's going on here.

The original issue was to track the addition of stderr and stdout to the output of a puppet run when the RC is 2 - I submitted #1260 to achieve that and as far as I can see this can be closed.

@tronicum the timeout issue is something completely separate, and I don't actually understand what that problem even is.  I'll close this one off and ask if you could please raise a new issue regards the timeout, with some more detail to reproduce it?

**Comment by tronicum** [comment]
@xavpaice there is already a an issue for that (issue #1273 ), and an PR that solves it. I probably mixed up the comment "this is likely already taken care of" as an solution to the timeout problem. whatever, they are separate so close is fine here.
