### ISSUE TITLE
lvol module can't be used to take snapshots

### ISSUE THREAD

**Issue by Ferroin** [ansible/ansible-modules-extras#1266]
One of the things that I (and a lot of other people I know) use LVM for is the ability to take snapshots.  Because of how the lvol module works, it can't be used to take a snapshot.

Lvol always requires the vg argument, and always passes this as the last argument to the lvcreate command.  However, lvcreate's --snapshot option requires the VG to be specified in the origin volumes name (so for example, vg/origin as opposed to just origin), and then requires you to not pass any VG name outside of that (because you can only create snapshots in the same VG as the origin LV), which results in the VG name passed by the lvol module being interpreted as the name of a PV to put the snapshot on, which causes the command to fail.

**Comment by robynbergeron** [comment]
[module: system/lvol.py]

**Comment by robynbergeron** [comment]
@Ferroin Thanks for submitting this feature idea.

@jhoekx @abulimov -- Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by Jmainguy** [comment]
@Ferroin Could you expand on how you would like it to look in the module.
- lvol: vg=firefly lv=test state=absent force=yes snapshot=example1

Would you want the snapshots to work with state=present/absent and only change if needed. (ie, snapshot exists with name, or doest not exist with that name). I can try adding it once I get your feedback.

**Comment by Ferroin** [comment]
For my usage at least, what you have described would probably work perfectly.  In the scripts I've been converting to Ansible playbooks, I make a point to check if the snapshot exists, and delete it if it does, and I'd much rather that that logic be explicit in the playbook rather than implied by the snapshot creation (that, and it's more consistent with how the module works already, and how most other modules work).

I do like the idea of using 'snapshot' as a property for the source LV, as that's consistent with the command line syntax for lvcreate.

**Comment by Jmainguy** [comment]
@Ferroin as promised, please see #1382. Let me know if it works as intended for you.

**Comment by Ferroin** [comment]
An initial look seems to indicate that it should work perfectly for what I need, I'll try and get it tested sometime within the next few hours.

**Comment by Ferroin** [comment]
OK, somehow I missed this when I first looked, but the implementation in the module is the reverse of the commandline syntax for lvcreate.  With lvcreate, the --snapshot option specifies the origin which the snapshot is based on, while the changes for the module appear to expect the opposite.  This may make things somewhat confusing for people who are used to using lvcreate.

Other than that, everything appears to work correctly as documented, although I've by no means done rigorous testing to spot any regressions.

**Comment by Jmainguy** [comment]
@Ferroin yup, that can be a little confusing. Basically I needed a name for the new snapshot, the lv it was based off of, and the vg it belonged to as well. So to try and limit the amount of options someone would have to pass I wrote it that way. You are definitely correct.

**Comment by Jmainguy** [comment]
@Ferroin Can this be closed now since #1382 was merged?

**Comment by Ferroin** [comment]
Yeah, sorry I forgot to follow up on this.
