### ISSUE TITLE
puppet module uses timout binary

### ISSUE THREAD

**Issue by tronicum** [ansible/ansible-modules-extras#1273]
ansible version: git latest
issue type: bug/feature request

summary: the puppet modules uses the "timeout" binary (Line 215) from GNU coreutils to set a puppet agent timeout. centos 5.7 don't have a recent coreutils RPM so fails on such hosts. puppet has a built in timeout parameter. it would be much nicer to use native that option.

**Comment by robynbergeron** [comment]
[module: system/puppet.py]

**Comment by robynbergeron** [comment]
@tronicum -- Thanks for submitting this feature idea.

@emonty -- Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by emonty** [comment]
@tronicum we actually use the timeout binary because the timeout parameter in agent does not protect against puppet agent hangs - which we actually had consistent problems with in a large farm. However, it should be simple enough to detect if timeout exists on the host and if not pass timeout to agent anyway.

**Comment by tronicum** [comment]
That is a nice solution, we have an mixed cluster with old and new centos vms so it could use timout if exists

**Comment by Jmainguy** [comment]
With #1285 getting merged, can this be closed now?

**Comment by bcoca** [comment]
closing as per above
