### ISSUE TITLE
zabbix_host module example doesn't work on 2.0

### ISSUE THREAD

**Issue by guibw** [ansible/ansible-modules-extras#1274]
hello,

I'm following the zabbix_host module example on http://docs.ansible.com/ansible/zabbix_host_module.html

however, it doesn't seem to work at all

this is my playbook: http://pastebin.ca/3270021
this is the fail return that I'm getting:
fatal: [192.168.20.115 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "internal error: do not know how to interpret argument_spec"}

I'm new to ansible so I don't know exactly how to help debugging it

**Comment by robynbergeron** [comment]
[module: monitoring/zabbix_host.py]

**Comment by robynbergeron** [comment]
@guibw Thanks for submitting this bug report.

@cove @harrisongu -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by eikef** [comment]
That error seems weird. The playbook works fine here (on 2.0.0), although during testing the numeric password showed another problem in the code (which is fixed in #1752).

@guibw: is this still a problem you encounter?

**Comment by bcoca** [comment]
closing via merged #1752
