### ISSUE TITLE
firewalld module needs "python-firewalld" to works (not python3 version).

### ISSUE THREAD

**Issue by lerenn** [ansible/ansible-modules-extras#1282]
Hi everyone,

I've [found](http://stackoverflow.com/questions/33904917/ansible-and-fedora23-firewalld-required-for-this-module/33905418#33905418) that firewalld module needs "firewall" library. Normally, it's installed with firewalld, except that Fedora23 installs python3 version of the package. So it doesn't work with Ansible (I suppose, Ansible uses Python2). So I just installed the right library and it worked !

I don't know if there is a way to resolve that in the code but, at least, it would be nice to precise it in the documentation :)

Thank you for reading and sorry if it's not the right place.

**Comment by robynbergeron** [comment]
[module: system/firewalld.py]

**Comment by robynbergeron** [comment]
@Lerenn -- Thanks for submitting this bug / docs report.

@maxamillion -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by hryamzik** [comment]
Just a note for those who found this issue searching for ubuntu 16.04 solution, I've made a [package](https://github.com/hryamzik/python-firewalld/releases/tag/0.1-0).

**Comment by JakeDEvans** [comment]
For others: make sure firewalld is running.

**Comment by tallandtree** [comment]
@hryamzik, do you know if it is possible to install the python-firewalld by pip on ubuntu 16.04?

**Comment by hryamzik** [comment]
@tallandtree not sure, just try it out in vagrant. I've moved from firewalld to bare iptables. But I don't think I would've made a package if there was a simple pip solution but I could've missed it. ;-)

**Comment by tallandtree** [comment]
@hryamzik, good advice. I think I will go back to bare iptables as well. Ansible, firewalld and docker still do not work together very well. See also https://github.com/docker/docker/pull/9397.

**Comment by hryamzik** [comment]
@tallandtree I've faced issues with port forwarding for LXC containers and wasn't happy with auto-generated iptables rules in general. Firewalld seem to be fine for workstations but doesn't meet any production requirements.

**Comment by tadman** [comment]
For Fedora 23+ you can create an Ansible task that installs dependencies for Ansible itself:

```
- name: Install Ansible Python 2 Dependencies
  with_items:
  - python-firewall
  dnf:
    name: "{{item}}"
    state: present
```

I've had to add a number of things here for compatibility reasons, `python-firewall` being the fix for using the `firewalld` module.
