### ISSUE TITLE
ec2_remote_facts - documentation is not updated

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible-modules-extras#1287]
Hi All,

The documentation here http://docs.ansible.com/ansible/ec2_remote_facts_module.html states that there is 'filter' option whereas the actual module has no such option at all. Probably replacement for 'lookup'.

This is confusing. Could you please sync the docs with the actual state of module?

Regards,
 Constantin

**Comment by wimnat** [comment]
The filters option is indeed present in the devel branch which is where I believe docs is built from. Where's your HEAD? ;)

**Comment by Constantin07** [comment]
I'm looking at 'devel' branch at a21d935e66da40d6184b0dc12d3e894917279476 and current doc http://docs.ansible.com/ansible/ec2_remote_facts_module.html

**Comment by bcoca** [comment]
@Constantin07 soo, the filters option is implemented in devel, line 125 of the file, you can see it even in the specific hash you point at above.

**Comment by Constantin07** [comment]
@wimnat @bcoca Yes, all is fine. Thanks. 
Probably I've looked at old version of document. Sorry.
