### ISSUE TITLE
pam_limits - documentation is not updated 

### ISSUE THREAD

**Issue by ggrossetie** [ansible/ansible-modules-extras#1290]
`limit_type` choices are `hard`, `soft` in the [documentation](http://docs.ansible.com/ansible/pam_limits_module.html) but in the [code](https://github.com/ansible/ansible-modules-extras/blob/devel/system/pam_limits.py#L95) `-` is supported.

**Comment by ggrossetie** [comment]
@bcoca Thanks, do you know when the documentation will be updated on http://docs.ansible.com/ansible/pam_limits_module.html ?

**Comment by bcoca** [comment]
we manually push changes to the site, you'll probably see it before the end of the week.
