### ISSUE TITLE
locale_gen does not generate locales on Arch Linux

### ISSUE THREAD

**Issue by tummychow** [ansible/ansible-modules-extras#13]
##### Issue Type:

Bug report
##### Ansible Version:

1.6.10
##### Environment:

Arch Linux (both master and slave)
##### Summary:

locale_gen doesn't generate locales on Arch Linux.

The [locale_gen](https://github.com/ansible/ansible/blob/devel/library/system/locale_gen#L66) module looks for lines starting with a hash and a space, and removes the hash to enable locale generation for those lines. But Arch's locale.gen doesn't have spaces (only the hash) so no lines get uncommented. Since no locales are enabled, locale-gen does nothing.
##### Steps To Reproduce:

Create a fresh Arch Linux system and install openssh/python2 on it. Add it to your Ansible hosts.

```
$ ansible -m locale_gen -a "name=en_US.UTF-8 state=present" --extra-vars "ansible_python_interpreter=/usr/bin/python2" <your Arch Linux target here>
$ ssh <your arch linux target here> locale -a
```
##### Expected Results:

The Ansible ad-hoc command should succeed and indicate "changed"
The ssh command `locale -a` should list all the locales on the system. `en_US.UTF-8` should be on the list.
##### Actual Results:

The Ansible command does succeed, but C and POSIX are the only locales listed aftewards. `en_US.UTF-8` does not appear.

Note: clone of ansible/ansible#8387

**Comment by bcoca** [comment]
closing this as fixed by #181
