### ISSUE TITLE
Zypper should be able to install "pattern"

### ISSUE THREAD

**Issue by robinro** [ansible/ansible-modules-extras#130]
The ansible zypper module is currently not able to install a "pattern".
##### Issue Type:

 “Feature Idea”
##### Ansible Version:

1.8.1
##### Environment:

openSUSE 13.1
##### Summary:

Use case on the shell, that is not covered by the zypper module:
zypper install -t pattern kde

This could be implemented by another argument like
type='package', 'pattern' which is then passed to zypper.
There are other types like 'srcpackage', 'product', 'patch' which zypper knows of.

The get_current_version and get_package_state functions needs to be adjusted to correctly treat patterns.
##### Steps To Reproduce:

zypper:  type=pattern name=kde state=present
##### Expected Results:

installs the pattern kde
##### Actual Results:

not possible

**Comment by alxgu** [comment]
Hi,

it is solved with this pr: https://github.com/ansible/ansible-modules-extras/pull/368

**Comment by bcoca** [comment]
closing as per merged #368
