### ISSUE TITLE
pam_limits - improve documentation

### ISSUE THREAD

**Issue by ggrossetie** [ansible/ansible-modules-extras#1312]
- Adds `comment` parameter
- Adds new examples with:
  - `comment` parameter
  - `value=unlimited`
  - `limit_type=-`

**Comment by robynbergeron** [comment]
@Mogztter -- Thanks for submitting this bug/docs report, and for the accompanying PR in #1313. 

@usawa --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module; please note that there is a PR for a fix as well that has already been sent your way for approval.
