### ISSUE TITLE
Cannot create S3 buckets in us-east-1

### ISSUE THREAD

**Issue by edsonmarquezani** [ansible/ansible-modules-extras#1317]
I can't create S3 buckets in _us-east-1_ region (US Standard) with _s3_bucket_ module. Setting _region_ attribute as another region makes it work, but using _us-east-1_ throws the following error:

`<Error><Code>InvalidLocationConstraint</Code><Message>The specified location-constraint is not valid</Message><LocationConstraint>us-east-1</LocationConstraint><RequestId>062E949D00F5D730</RequestId><HostId>fNQfoM+k/ug690XEwWY0MKYlXXOJDHaip6rXLDqfaxKcYJiPSebymIPVVIWYmQ7t</HostId></Error>`

I know it is from S3 API, which doesn't accept the value _us-east-1_, and if you want to create a bucket in that region, you should omit it. Ok. So, maybe you could blame Boto for it.

But, when I don't set a region (not in the task nor environment), I get another error, which I found to be Boto's too.

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: cannot concatenate 'str' and 'NoneType' objects`

Somehow a null location variable is ending up in this piece of code.

In **boto/s3/connection.py**:

```
     if location == Location.DEFAULT:
        data = ''
    else:
        data = '<CreateBucketConfiguration><LocationConstraint>' + \ 
                location + '</LocationConstraint></CreateBucketConfiguration>'
```

I went through Ansible's code, and couldn't understand why this is happening, once it seems to handle that condition.

In **ansible/modules/extras/cloud/amazon/s3_bucket.py**:

```
if region in ('us-east-1', '', None):
    # S3ism for the US Standard region
    location = Location.DEFAULT
else:
    # Boto uses symbolic names for locations but region strings will
    # actually work fine for everything except us-east-1 (US Standard)
    location = region
```

So, is that still a bug, or am I doing something very wrong?

I'm using the devel branch as for the time of this post and Boto 2.38. I made sure I didn't have an older version of both running here before I filled this bug report. I tried every form of setting the region attribute (with and without quotes, as variable and hardcoded, environment variable). I really can't understand why this is happening.

I hope you can reproduce it.

Thank you.

**Comment by wimnat** [comment]
Are you sure your development branch has the latest changes? A fix for this was merged just over a week ago

**Comment by halberom** [comment]
Testing Ansible RC1 and hit this. Not sure how it could be done, but flagging of RC1 known bugs would be useful.

**Comment by edsonmarquezani** [comment]
I'm using the devel branch (the very head of the repository), I doubled, tripled checked it. I cannot see what I can be possibly doing wrong.

**Comment by wimnat** [comment]
I can't replicate this.  If I don't specify a region in my play, the bucket is created in us-east-1.  If i specify the region as us-east-1, the bucket is also created without error.

Can you add detail based on https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md?

I'm particularly interested in what your play looks like and how you are authenticating to Amazon.  I.e. is it an IAM role, access key in a credential file, access key as an environment parameter etc.

Thanks,

**Comment by halberom** [comment]
Following up, the bug's definitely in RC1, but devel (tested at e201a255d17) worked for me.

**Comment by edsonmarquezani** [comment]
I've just updated my local repository and installed again from devel head, and then it worked.
With _region: us-east-1_ specified in the play it works, as well as when not specified but declared on _AWS_DEFAULT_REGION_ environment variable.

I really don't know what I was doing wrong, but it was probably some mistake of mine with Git or with the RPM packages I was building locally. I'm sorry for that.

My play was as simple as that:

```
- name: "s3-{{ environment_short }}-{{ group }}-test2"
  s3_bucket:
    name: "{{ environment_short }}-{{ group }}-test2"
    region: "{{ aws_region }}"
    state: present
    versioning: yes
```

And I was authenticating from environment variables (access key/ secret key). I'm running it in a Fedora 21 box.

What is really weird is that, looking directly at the installed code, the patch for it was there all the time, as said earlier in this thread.

Anyway, thanks for your help.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
