### ISSUE TITLE
win_firewall_rule: Doesn't work in ansible v2.x

### ISSUE THREAD

**Issue by dreamcat4** [ansible/ansible-modules-extras#1406]
Hi,
I'm experiencing the following errors in ansible 2:

``` sh
TASK [0_base : Be sure winrm http is disabled] *********************************
fatal: [ga-z170x-g3]: FAILED! => {"changed": false, "error": "The property 'Enable' cannot be found on this object. Verify that the property exists.", "failed": true, "msg": ["The rule 'Deny WinRM HTTP' exists."]}

PLAY RECAP *********************************************************************
ga-z170x-g3                : ok=3    changed=0    unreachable=0    failed=1   

# and

TASK [0_base : Be sure winrm http is disabled] *********************************
fatal: [ga-z170x-g3]: FAILED! => {"changed": false, "error": "The property 'profile' cannot be found on this object. Verify that the property exists.", "failed": true, "msg": ["The rule 'Deny WinRM HTTP' exists."]}

PLAY RECAP *********************************************************************
ga-z170x-g3                : ok=3    changed=0    unreachable=0    failed=1   
```

Where the task being run looks like this in my playbook:

``` yaml
- name: Be sure winrm http is disabled
  win_firewall_rule:
    name: Deny WinRM HTTP
    enable: yes
    profile: Domain,Private,Public
    protocol: tcp
    localport: 5985
    direction: in
    action: block
    state: present
    force: yes
  tags: firewall
```

These errors do not happen on ansible v1.9.4.

**Comment by dreamcat4** [comment]
more:

It seems now the powershell is running under `EXEC Set-StrictMode -Version Latest`. So maybe that extra strict checking has something to do with the issue.

``` sh
TASK [0_base : Be sure winrm http is disabled] *********************************
task path: /home/id/ansible/windows/roles/0_base/tasks/winrm.yml:3
<ga-z170x-g3> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO ga-z170x-g3
<ga-z170x-g3> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1450541507.55-2395495437913").FullName | Write-Host -Separator '';
<ga-z170x-g3> PUT "/tmp/tmpwMvyrl" TO "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1450541507.55-2395495437913\win_firewall_rule.ps1"
<ga-z170x-g3> EXEC Set-StrictMode -Version Latest
Try
{
& "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1450541507.55-2395495437913\win_firewall_rule.ps1"
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1450541507.55-2395495437913" -Force -Recurse -ErrorAction SilentlyContinue }
fatal: [ga-z170x-g3]: FAILED! => {"changed": false, "error": "The property 'Enable' cannot be found on this object. Verify that the property exists.", "failed": true, "invocation": {"module_args": {"action": "block", "direction": "in", "enable": true, "force": true, "localport": 5985, "name": "Deny WinRM HTTP", "profile": "Domain,Private,Public", "protocol": "tcp", "state": "present"}, "module_name": "win_firewall_rule"}, "msg": ["The rule 'Deny WinRM HTTP' exists."]}

PLAY RECAP *********************************************************************
ga-z170x-g3                : ok=3    changed=0    unreachable=0    failed=1   

id@emachines-e520:~/ansible$ 

```

**Comment by dreamcat4** [comment]
@TimothyVandenbrande please look into this matter as soon as you can.

The problem occurs enabling powershell's `Strict` syntax checking mode. Which happens to be the default going forward in ansible v2.0 + now. Many thanks.

**Comment by richard-chivers** [comment]
Hi,

We have done some fixes for this.

Essentially the line that says "if ($capture.failed -eq $true) {“ Was the main issue as it  always failed as the Result returned when successful did not have a .failed property.

Anyway, There were also issues when matching rules, the results returned from $rawoutput did not match the params in the fwsettings, for example the setting had Enable and the result returned Enabled. This seemed to have been catered for with some if else specific statements, but lines that did $output.$($comparekey) just fell over now strick is enabled.

To combat the issue I updated the code a little with a method that just mapped the values like:

function getFirewallRuleCompareKey ($key) {
    switch -wildcard ($key) 
    { 
        "Enable" { return "Enabled" } 
        "profile" { return "Profiles" }  
        "name" { return "Rule Name" }  
        default { Return $key }
    }
}

I have tested on windows 2012 core, but nothing else!

I also think I could have gone further with my changes, and may do if anyone thinks it is useful, but from a personal perspective fairly new to powershell.

Maybe this is useful as a starting point.
[win_firewall_rule_z.txt](https://github.com/ansible/ansible-modules-extras/files/70494/win_firewall_rule_z.txt)

**Comment by dreamcat4** [comment]
@richard-chivers  Thanks richard!

Indeed there are more other bugs (still there), for example with the profiles key. And it's not the most pleasant module to work on. So +1 for getting rid of some of that hardcoded if/else case-by-case checking. Pretty narly let's be honest.

I _do_ wonder if there's and better alternative to the `netsh` command. Or that we should filter it first before comparison to give a more guaranteed consistent / uniform output. In particular vs it's own input params. Because when we set the rule, we tell it `enable`, and netsh comes back with `enabled`. And when we flick other options all-on. e.g. profiles=x,y,z, then they can come back printed different too (`profiles: x,y,z` -->  `all`). the API is a nightmare really to be honest especially once they changed it across different windows versions.

Well regardless, we really need to continue improving this module as many people absolutely require firewall and it's not going away. So your efforts are much appreciated here.

**Comment by robynbergeron** [comment]
[module: windows/win_firewall_rule.py]

**Comment by ghost** [comment]
Maybe my issue is also related? https://github.com/ansible/ansible/issues/13741

**Comment by t-v** [comment]
My apologies, I have been ill for the past months so I was quite unavailable to follow up on this, but I'll try to sort this out this week.
My apologies for the delay.

**Comment by t-v** [comment]
@janhoeve your issue is related to this one. The strict checking in Ansible 2.0 broke the way it worked.

@dreamcat4 I know the the if/else checking is nasty, the issue is that netsh doesn't give the same output as the one requested, so I had to capture it somehow. The other issue is that the firewall cmdlets are only fully available for windows 2012 R2. Since we still had some 2008 windows servers, I chose to use netsh, but I totally agree to the fact that netsh parsing is ugly and nasty. But if you have a solution for it, it is more than welcome.

For the 2.0+ issue, I still can't get Ansible 2.0 running on my environment so unfortunately I was unable to test and further debug this. I am still planning to get it installed but due to my former abscence it honestly isn't a priority.

**Comment by ghost** [comment]
@TimothyVandenbrande My issue got closed because I created in the wrong section apparently.
Do you want me to re-create it in the ansible-modules-extras, or do you have enough information?

**Comment by t-v** [comment]
@janhoeve I can still see the reference, so there's no need to recreate it.

**Comment by dreamcat4** [comment]
> @dreamcat4 I know the the if/else checking is nasty, the issue is that netsh doesn't give the same output as the one requested, so I had to capture it somehow. The other issue is that the firewall cmdlets are only fully available for windows 2012 R2. Since we still had some 2008 windows servers, I chose to use netsh, but I totally agree to the fact that netsh parsing is ugly and nasty. But if you have a solution for it, it is more than welcome.

Yeah I appreciate its a tricky one. And not a pleasant thing to deal with. Yet it is also the primary source of bugs in this module here.

The best suggestion I have been able to think of so far would be to replace that niggly part of the code with a 2-stage process; first re-write the output captured from netsh so that its in more desirable form. Not just the paramter names, but the values too (like profile 'all' mapping).

Then the 2nd stage would be a bit like what we have now, except because of the prior translation, we can make it as a much simpler direct comparison code. Matching against our own variable names and values instead of what was actualy being spat out be netsh cmd.

Its still a problematic area even so, because at least the command parameter values are different between the new / old windows versions. For example I'm on win10 pro only. So cant actually see the kinds of output that you guys see with the older windows server.

But yeah another API may exist too (for example in C# accessible through powershell, however I dont know / havent looked). Yet again may stumble if different or absent in older windows versions ^^. Hence why I feel a bit out of my depth here with such historical windows APIs have not been through. Being primarily a linux / mac person.

**Comment by widjah** [comment]
Hi,
@dreamcat4 You can take a look at the HNetCfg.FwPolicy2 COM object. 
I've been able to configure firewall rules on Windows 2008, 2008R2, 2012 and 2012R2.

```
$fw = New-Object -ComObject "HNetCfg.FwPolicy2"
$fw.Rules
```

**Comment by dreamcat4** [comment]
Thanks @widjah for the infos

**Comment by chrisjsmith** [comment]
Just a me too on this one. The profile property doesn't work any more on 2.0:

`fatal: [server.domain.com]: FAILED! => {"changed": false, "error": "The property 'profile' cannot be found on this object. Verify that the property exists.", "failed": true, "msg": ["The rule 'Team City Agent (9090)' exists."]}`

I'm not specifying profile in the config stanza:

``` yaml
- name: Allow port 9090 through firewall incoming
  win_firewall_rule:
    name: "Team City Agent (9090)"
    localport: 9090
    protocol: TCP
    action: allow
    direction: In
```

**Comment by ilpianista** [comment]
Could you please try my patch?

**Comment by ilpianista** [comment]
cc: @schwartzmx

**Comment by tcr-ableton** [comment]
I can confirm that @ilpianista patch fixes the problem mentioned by @chrisjsmith for me on Windows 7, 8 and 10 :+1: 

Please consider opening a PR with the patch!

**Comment by ghost** [comment]
Thanks for testing. I will try @ilpianista patch as well this week.
