### ISSUE TITLE
win_lineinfile to modify hosts, it changes file permission so process can't read it

### ISSUE THREAD

**Issue by dbpeng** [ansible/ansible-modules-extras#1440]
Does anyone have similar issue? 

I found others have this issue too in other thread https://github.com/ansible/ansible-modules-core/issues/2236

B

**Comment by robynbergeron** [comment]
Hi @dbpeng --

win_lineinfile is a core module; can you please file this issue in the appropriate repository, so we can route it to the maintainer? :) Thanks! https://github.com/ansible/ansible-modules-core

**Comment by nitzmahone** [comment]
duplicate of https://github.com/ansible/ansible-modules-core/issues/2236 - closing
