### ISSUE TITLE
zypper_repository: add "priority" argument

### ISSUE THREAD

**Issue by robinro** [ansible/ansible-modules-extras#1450]
Issue Type: Feature Idea

zypper can set a priority for each added repository. Packages will be taken from the repository with the highest priority (smallest number). See also https://en.opensuse.org/SDB:Zypper_manual_%28plain%29

This functionality should be available through ansible as well. Add an arguement `priority` to the zypper_repository module.

**Comment by robinro** [comment]
I might implement this myself. What kept me from implementing it immediately is that providing a correct `changed` state didn't seem obvious. If someone else implements it I'm also happy.

**Comment by robynbergeron** [comment]
[module: packaging/os/zypper_repository.py]
