### ISSUE TITLE
monitoring/monit.py won't recognize the name of a process which contains uppercase letters

### ISSUE THREAD

**Issue by TobiasPottgueter** [ansible/ansible-modules-extras#146]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2 (tested)
branch: devel (i looked into the code, see Possible Solution)
##### Environment:

Centos 6.6
##### Summary:

monitoring/monit.py won't recognize a process name if the name contains uppercase letters.
sorry, but that's all.
##### Steps To Reproduce:

```
- name: myMonitProcess
  monit: name=myMonitProcess state=unmonitored
```

will result in

```
msg: myMonitProcess process not presently configured with monit
```

if "monit summary" is displaying:

```
Process 'myMonitProcess'  Running
System 'localhost' Running
```
##### Expected Results:

I expect it to work with uppercase process names as it is working with lowercase only process names, and mixedcase process names self speaking.
##### Actual Results:

Unless i use completely lowercase process names it won't work.
##### Possible Solution:

Sorry, i don't have a test environment, but i managed to identify a possible solution:

line 78 and line 79

```
parts = line.lower().split()
if len(parts) > 2 and parts[0] == 'process' and parts[1] == "'%s'" % name:
```

'line' should NOT be converted to lower and 'process' should then be 'Process' (uppercase P)

**Comment by wimnat** [comment]
TobiasPottgueter can you please test my PR resolves your issue?

**Comment by bcoca** [comment]
closing via merged PR
