### ISSUE TITLE
win_feature module doesn't work with Windows 10 Pro

### ISSUE THREAD

**Issue by eoyslebo** [ansible/ansible-modules-extras#1464]
It looks like win_feature.ps1 uses Add-WindowsFeature to enable features, but this cmdlet is not available with Windows 10 Pro.

According to https://peter.hahndorf.eu/blog/WindowsFeatureViaCmd.html Enable-WindowsOptionalFeature or dism.exe might be suitable alternatives.

Examples:

Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All

dism.exe /Online /NoRestart /Enable-Feature:Microsoft-Hyper-V /All

**Comment by jhawkesworth** [comment]
That page makes an interesting read.
If there really are different names for the packages in dism it might be an idea to keep the existing win_feature module for windows server versions and have a different module for the dism-based packages.  That said, win_feature is a fairly small module at the moment so it could probably be expanded to handle this.

**Comment by robynbergeron** [comment]
Hi @eoyslebo:

win_feature is a core module; can you reopen this in the appropriate repository, so we can route it properly? Thanks! https://github.com/ansible/ansible-modules-core

(And thanks @jhawkesworth for your comments thus far :D)

**Comment by eoyslebo** [comment]
https://github.com/ansible/ansible-modules-core/issues/2792
