### ISSUE TITLE
ec2_elb_facts - returns no explicit error message when no ELB found

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible-modules-extras#1468]
##### Issue Type:
- Bugfix Pull Request #1469
##### Ansible Version:

ansible-1.9.4-1.el7.noarch
##### Ansible Configuration:

No changes.
##### Environment:

CentOS Linux release 7.2.1511 (Core)
##### Summary:

When no ELB marching names is fount in AWS, the returned error message is meaningless - it doesn't report the real reason.
##### Steps To Reproduce:

```
ansible localhost -m ec2_elb_facts -a "names=elb-name region=us-east-1" -vv
```
##### Expected Results:

```
127.0.0.1 | FAILED >> {
    "failed": true,
    "msg": "LoadBalancerNotFound: Cannot find Load Balancer elb-name"
}
```
##### Actual Results:

```
127.0.0.1 | FAILED >> {
    "failed": true,
    "msg": null
}
```

**Comment by robynbergeron** [comment]
[module: cloud/amazon/ec2_elb_facts.py]

**Comment by robynbergeron** [comment]
@Constantin07 Thanks for submitting this bug report, and your accompanying PR. 

@mjschultz -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module. It looks like #1469 fixes this and you already gave it the thumbs-up, so hopefully this issue should be fixed :)

**Comment by alikins** [comment]
Fixed with merge of https://github.com/ansible/ansible-modules-extras/pull/1469
