### ISSUE TITLE
zypper module doesn't iterate over items

### ISSUE THREAD

**Issue by coryrwagner** [ansible/ansible-modules-extras#148]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = /usr/share/ansible
##### Environment:

SLES 11 SP3
##### Summary:

I have some tasks that are supposed to install several packages via the zypper module. Since about Ansible 1.8 and specifically with version 1.8.2, the module appears to be broken, because it now tries to install a comma-separated list of modules and fails. It should install each package one-by-one. 
##### Steps To Reproduce:

```
- name: install openmotif-libs packages
  zypper: name={{ item }} state=latest
  with_items:
  - openmotif-libs
  - openmotif-libs-32bit
```
##### Expected Results:

```
ok: [hostname] => (item=openmotif-libs) => {"changed": false, "item": "openmotif-libs", "msg": "remote module does not support check mode", "skipped": true} skipping: [hostname] => (item=openmotif-libs)
ok: [hostname] => (item=openmotif-libs-32bit) => {"changed": false, "item": "openmotif-libs-32bit", "msg": "remote module does not support check mode", "skipped": true} skipping: [hostname] => (item=openmotif-libs-32bit)
```
##### Actual Results:

```
failed: [hostname] => (item=openmotif-libs,openmotif-libs-32bit) => {"failed": true, "item": "openmotif-libs,openmotif-libs-32bit"} msg: No provider of 'openmotif-libs,openmotif-libs-32bit' found.
```

**Comment by jimi-c** [comment]
This is actually an optimization for many of the package managers, it just does not appear to have been implemented correctly in the module code to split the items back out of the comma-separated list.

**Comment by bcoca** [comment]
I cannot seem to reproduce the problem in  current devel nor in 1.8.2, are you sure you are not using an older version of the zypper module?

**Comment by mpdehaan** [comment]
Sounds like an older version of the zypper module with a newer ansible to me.

**Comment by coryrwagner** [comment]
I would agree with your assessments, but it looks like I have the 1.8.x version of zypper.py. I compared the files on my system to those in this repo and only the devel branch differs. Ansible was installed from a make install of the latest tar ball (ansible-latest.tar.gz).

Am I comparing the wrong files or otherwise missing something?

**Comment by coryrwagner** [comment]
I found the older modules in /usr/share/ansible and current modules, for version 1.8.2, are installed to /usr/local/lib64/python2.6/site-packages/ansible-1.8.2-py2.6.egg. Removing/renaming /usr/share/ansible resolved the issue.

**Comment by jlec** [comment]
I can reproduce this with a clean installation.
- zypper: name=monitoring-plugins-{{ item }} state=installed
  with_items:
  - disk
  - dns
  - file_age
  - ldap

results in 

TASK: [icinga | zypper name=monitoring-plugins-{{ item }} state=installed] ***\* 
failed: [ics6008] => (item=disk,dns,file_age,ldap) => {"failed": true, "item": "disk,dns,file_age,ldap"}
msg: No provider of 'disk' found.
No provider of 'dns' found.
No provider of 'file_age' found.
No provider of 'ldap' found.

**Comment by coryrwagner** [comment]
That's a different problem, which can be fixed by quoting the name string.
