### ISSUE TITLE
Missing taiga_issue module from stable-1.9

### ISSUE THREAD

**Issue by lekum** [ansible/ansible-modules-extras#1490]
Hi,

I have noticed that the [taiga_issue](https://github.com/ansible/ansible-modules-extras/blob/stable-1.9/web_infrastructure/taiga_issue.py) module from '`stable-1.9` is missing in `stable-2.0` or in `devel`. Any plans on merging the commit?

Regards.

**Comment by bcoca** [comment]
no idea what happened, added it to devel/stable-2.0 so it will be included in subsequent releases
