### ISSUE TITLE
ec2_vpc_net_facts module missing from Ansible 2.0

### ISSUE THREAD

**Issue by l0neranger** [ansible/ansible-modules-extras#1516]
Ansible v2.0.0.2 on Ubuntu Trusty control machine.

Trying to use the module just throws a syntax error.

Either the module should be included if it was an oversight or the documentation [here](http://docs.ansible.com/ansible/ec2_vpc_net_facts_module.html) needs to be updated to not include "New in version 2.0."

**Comment by bcoca** [comment]
fixed in stable-2.0 it will appear on next 2.0.x release
