### ISSUE TITLE
at module: work on FreeBSD

### ISSUE THREAD

**Issue by lifanov** [ansible/ansible-modules-extras#153]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = /usr/local/share/ansible
##### Environment:

FreeBSD
##### Summary:

at.py constructs a command line for the "at" utility with positional arguments last.
Glibc allows this, but FreeBSD libc (and others) do not. This is a security feature.

So, this needs to be written as "at -f /tmp/cmd now + 1 minute" to be portable to non-glibc systems.

```
--- at.py.orig  2014-12-15 11:08:47.153125860 -0500
+++ at.py   2014-12-15 11:09:11.137125129 -0500
@@ -78,7 +78,7 @@


 def add_job(module, result, at_cmd, count, units, command, script_file):
-    at_command = "%s now + %s %s -f %s" % (at_cmd, count, units, script_file)
+    at_command = "%s -f %s now + %s %s" % (at_cmd, script_file, count, units)
     rc, out, err = module.run_command(at_command, check_rc=True)
     if command:
         os.unlink(script_file)
```
##### Steps To Reproduce:

On FreeBSD, do: ansible -m at -a 'command="touch /tmp/t" count=2 units="minutes"' 127.0.0.1
##### Expected Results:

There is a /tmp/t file touched two minutes from "now"
##### Actual Results:

```
127.0.0.1 | FAILED >> {
    "cmd": "/usr/bin/at now + 2 minutes -f /tmp/at47k09b", 
    "failed": true, 
    "msg": "at: garbled time", 
    "rc": 1, 
    "stderr": "at: garbled time\n", 
    "stdout": ""
}
```

**Comment by abadger** [comment]
Looks good -- would you care to submit a pull request for this?

**Comment by lifanov** [comment]
I submitted pull request #161 with this issue.

**Comment by abadger** [comment]
PR has been merged!  Thanks!
