### ISSUE TITLE
Working on a module - what's the policy on 3rd party lib dependencies?

### ISSUE THREAD

**Issue by cweagans** [ansible/ansible-modules-extras#1531]
I'm not as well versed in Python development as I ought to be, but I'm not seeing any way to add a 3rd party lib that my Ansible module can depend on. Is there something I'm missing? 

The library in question is https://github.com/ktdreyer/python-nfsn

Any suggestions for how to go about doing this?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

But to give you a quick answer:  no, currently modules need to use libs that are present in the target system, ansible has no way of copying libs to be used.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by cweagans** [comment]
Sorry about that! I'll ask my followup questions in IRC. Thanks for the info.
