### ISSUE TITLE
zypper module doesn't respect disable_gpg_check=yes option for state=latest

### ISSUE THREAD

**Issue by sdracerunner** [ansible/ansible-modules-extras#154]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
Based on code inspection, this is reproducible on the development branch as well.
##### Environment:

Ansible Host: Ubuntu 14.04.1 LTS
Target System: SUSE 11.3 (zypper 1.6.308)
##### Summary:

Using the following Ansible script:

```
zypper: name=package-name state=latest disable_gpg_check=yes
```

A previously-installed package will not be updated to the latest version, if the repository serving the update fails a certificate check.  It is expected that the `disable_gpg_check=yes` flag would bypass this, but it does not appear to work properly.
##### Steps To Reproduce:

Install an out-of-date package on the target system and check its version.
Create an Ansible task:

```
- name: install the zypper repository
  zypper_repository: name=myrepo repo=http://path_to_repo/ state=present

- name: update the component
  zypper: name=package-name state=latest disable_gpg_check=yes
```

Create the zypper repository, populate the repository with a newer version of the package, and ensure that the repository is unsigned.
Run the playbook.
Check the version of the package that's installed on the target system.
##### Expected Results:

It's expected that the component's package will be updated to the newest version, and that will be reflected in Ansible's output:

```
TASK: [component | install the zypper repository] ***************************** 
ok: [192.168.0.14]

TASK: [component | update the component] ************************************** 
changed: [192.168.0.14]
```
##### Actual Results:

The component's package remains at the old version, and there is no error or other indication of this in Ansible's output:

```
TASK: [component | install the zypper repository] ***************************** 
ok: [192.168.0.14]

TASK: [component | update the component] ************************************** 
ok: [192.168.0.14]
```
##### Notes:

In the zypper module it seems that the `package_latest()` function doesn't respect `disable_gpg_check=yes` like `package_present()` does.

This indicates that Ansible will generate this command:

```
/usr/bin/zypper --non-interactive update --auto-agree-with-licenses package-name
```

when it should generate this command:

```
/usr/bin/zypper --non-interactive --no-gpg-check update --auto-agree-with-licenses package-name
```

If I run the commands manually, the first fails as expected with:

```
File 'repomd.xml' from repository 'myrepo' is unsigned, continue? [yes/no] (no): no
Retrieving repository 'myrepo' metadata [error]
Repository 'myrepo' is invalid.
```

**Comment by abadger** [comment]
Thanks for the PR!  That's been merged so closing this.
