### ISSUE TITLE
Enhancement idea: Let's Encrypt module

### ISSUE THREAD

**Issue by davidjpeacock** [ansible/ansible-modules-extras#1545]
I've seen various people implement their own, but I'd love to see this as either an Extras module to start, or ideally a Core module in the long term.

HTTPS is viable, and free. :-)

**Comment by resmo** [comment]
afaik @mgruener is working on one

**Comment by mgruener** [comment]
I am indeed. My idea is based on what the ACME tiny client does. Just handle the actual ACME part, return the challange in a first task, let the user fulfill it by whatever means necessary (which is easy in ansible anyway) and then verify the challange during a second task. It _should_ be easy :wink:

**Comment by mgruener** [comment]
Current Work in progress: https://github.com/mgruener/ansible-modules-extras/blob/module-letsencrypt/web_infrastructure/letsencrypt.py

**Comment by mgruener** [comment]
letsencrypt/boulder#1435 is pretty much a show stopper for a clean let's encrypt module implementation. Right now there is no way to get the current state of authorizations or see if the requested certificate is already present between runs. During an ansible run I could pass around a datastructure containing all IDs and URIs between different executions of a letsencrypt task, but that is not possible between runs. Depending on the situation, each ansible run could create more and more authorizations without ever fulfilling them.

I will be able to finish the module but a release will only be feasible when the let's encrypt boulder server implements the current ACME spec.

**Comment by mgruener** [comment]
Updated the module code. Now it needs a lot of testing. I plan to create a WIP pull request for the module shortly, which hopefully will result in reviews and more tests. It is still a long way before I would call it generally usable.

**Comment by davidjpeacock** [comment]
Thank you; I'll take a closer look. :-)

**Comment by mgruener** [comment]
I have created some preliminary tests here: https://github.com/mgruener/ansible/tree/tests_letsencrypt/test/integration

As expected there is still a lot to do even for this simple case ;) I also hit a problem with fetch_url ansible/ansible#14915

The moment I or someone else manages to create a single certificate with the module I will create the initial pull request to ansible-modules-extras :smile:

**Comment by mgruener** [comment]
I was just able to successfully create a ssl certificate using the module and the preliminary tests :smile:. 

As long as the tests are executed on a system with a webserver with its document root at `/var/www/html` the module should work as is (or you could just change the document root used by the tests :wink:).

It only works for the `http-01` challenge, the module is still missing a lot of error checking and even the changed / not changed state is more or less a rough estimate. But it works and the boulder/ansible issues I stumbled upon while developing are being worked on.

Next stop: Pull request to get in more feedback, add the necessary polishing and eventually get it integrated into ansible-modules-extras.

**Comment by hryamzik** [comment]
For now you can use this [role](https://github.com/gitinsky/ansible-role-letsencrypt)

**Comment by morbidick** [comment]
if anyone is interested, i just ported an acme-tiny role to this module: https://github.com/morbidick/ansible-role-letsencrypt works like a charm, thx for the nice work

**Comment by hryamzik** [comment]
@morbidick [really](https://github.com/gitinsky/ansible-role-letsencrypt)?

**Comment by morbidick** [comment]
@hryamzik yeah i saw your role, i just wanted to post my role as an example because it specifically uses this build in module

**Comment by hryamzik** [comment]
Ah I see, I didn't mention module was already available, looks like release queue is more than 9 months now.

**Comment by morbidick** [comment]
@hryamzik available with ansible 2.2
