### ISSUE TITLE
Feature Idea: ec2_elb_facts should return hosted_zone_id

### ISSUE THREAD

**Issue by sunnyone** [ansible/ansible-modules-extras#1549]
I want to create a route53 record with "route53" module with alias=True after fetching information with ec2_elb_facts module. But I can't do it since Route53 requires hosted_zone_id to create an alias record and this module doesn't return it.

ec2_elb_facts module should return hosted_zone_id like the ec2_elb_lb module.

**Comment by ienliven** [comment]
+1
I have the same problem
