### ISSUE TITLE
yumrepo module needs to support the 'priority' parameter

### ISSUE THREAD

**Issue by ke3vin** [ansible/ansible-modules-extras#1563]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

yum_repository module
##### ANSIBLE VERSION

N/A
##### SUMMARY

For those that want to use the yum-plugin-priorities plugin, this plugin requires the 'priority' parameter to be specified in the repo file.  Please see:
https://wiki.centos.org/PackageManagement/Yum/Priorities
for additional information.

Thanks,
Kevin

**Comment by jtyr** [comment]
As discussed in PR #1415.

**Comment by jctanner** [comment]
[module: yum_repository]

**Comment by jtyr** [comment]
This has been implemented. Please close it.
