### ISSUE TITLE
bigip_pool_member state absent also removes node

### ISSUE THREAD

**Issue by caphrim007** [ansible/ansible-modules-extras#1569]
Hello,

I noticed that when I remove a pool member from a pool, its node is also deleted from the BIG-IP. This is different from the behavior that I see in the UI when I remove a pool member from a pool (it just disappears from the pool but remains as a node).

Relevant code is here
https://github.com/ansible/ansible-modules-extras/blob/devel/network/f5/bigip_pool_member.py#L360

Can I suggest adding a parameter or something to retain the node if said parameter is supplied? This would allow one to move members between pools, and drop and add them back, without needing to also re-create the node.

**Comment by mhite** [comment]
Sounds reasonable!

**Comment by gormeroth** [comment]
+1 on getting this fixed

**Comment by caphrim007** [comment]
closing because the feature was merged
