### ISSUE TITLE
__init__.py missed in windows directory

### ISSUE THREAD

**Issue by lenaten** [ansible/ansible-modules-extras#159]
as result, the *.py files don't installed and those plugins can't be detected.

**Comment by bcoca** [comment]
the windows plugins are powershell (.ps1) so there should be no problem detecting them w/o `__init__.py`

**Comment by sivel** [comment]
The .py files do hold the docs and examples though which would be needed for ansible-docs.

Unsure about any problems not detecting the module if the .py is missing.  For some reason I had remembered it being the case that both needed to exist.

**Comment by lenaten** [comment]
Look this function in ansible/lib/ansible/utils/plugins.py:

```
def find_plugin(self, name, suffixes=None, transport=''):
        ''' Find a plugin named name '''

        if not suffixes:
            if self.class_name:
                suffixes = ['.py']
            else:
                if transport == 'winrm':
                    suffixes = ['.ps1', '']
                else:
                    suffixes = ['.py', '']
```

As I see in debug, transport is always empty, even in winrm connection, so only .py files detected as plugins. 

We can also change the condition to "name.startswith("win_")" instead of "transport == 'winrm'", Both solve the problem. Anyway I think that transport shouldn't be coupled with file extension.

`__init__.py` missing only in windows directory , so you can reproduce the problem by use this playbook:

```
---
- hosts: windows
  tasks:
  - win_chocolatey:
      name: git
```

as result you will see this message: 
"ERROR: win_chocolatey is not a legal parameter in an Ansible task or handler"

**Comment by bcoca** [comment]
I'm not sure how that can be the case, If it loads the .py it would not do any work as the .ps1 are the ones with the actual code. I merged the PR anyways as it fixes the issue with ansible-doc. 

if the transport is not set to winrm these modules would do nothing as it would try to execute the doc only .py files.

**Comment by lenaten** [comment]
every plugin checked at start with:

```
def has_plugin(self, name):
        ''' Checks if a plugin named name exists '''

        return self.find_plugin(name) is not None
```

has_plugin call find_plugin without transport parameter so transport is always empty.
