### ISSUE TITLE
ec2_vpc_net_facts missing from 2.0.0.2 pip install

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible-modules-extras#1612]
Issue Type: Bug Report

Ansible Version: 2.0.0.2
however, the verbatim output of ansible --version is 2.0.0.0
[root@wsv-workspace ~]# ansible --version
ansible 2.0.0.0
  config file = 
  configured module search path = Default w/o overrides

Ansible Configuration:
Module is supposed to be new in 2.0, but is not present on my system.
Ansible was installed via pip
When I locate all modules starting with ec2_vpc I see that ec2_vpc_net_facts is missing
[root@wsv-workspace ~]# locate ec2_vpc_net_facts
[root@wsv-workspace ~]# locate ec2_vpc
/usr/lib/python2.6/site-packages/ansible/modules/core/cloud/amazon/ec2_vpc.py
/usr/lib/python2.6/site-packages/ansible/modules/core/cloud/amazon/ec2_vpc.pyc
/usr/lib/python2.6/site-packages/ansible/modules/core/cloud/amazon/ec2_vpc_net.py
/usr/lib/python2.6/site-packages/ansible/modules/core/cloud/amazon/ec2_vpc_net.pyc
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_igw.py
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_igw.pyc
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_route_table.py
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_route_table.pyc
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_route_table_facts.py
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_route_table_facts.pyc
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_subnet.py
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_subnet.pyc
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_subnet_facts.py
/usr/lib/python2.6/site-packages/ansible/modules/extras/cloud/amazon/ec2_vpc_subnet_facts.pyc

Environment:
Ansible running from RedHat 6.7 and play is running on localhost
[root@wsv-workspace ~]# cat /etc/*-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)
Red Hat Enterprise Linux Server release 6.7 (Santiago)

Summary:
ec2_vpc_net_facts missing from 2.0.0.2 pip install

Steps To Reproduce:
sudo pip install ansible==2.0.0.2
locate ec2_vpc_net_facts
or if you prefer, try to run the following task
    - action: ec2_vpc_net_facts

Expected Results:
expect locate to find the module, and the invocation of the module to return vpc facts

Actual Results:
    locate ec2_vpc_net_facts returns nothing
    play returns 
    TASK [aws : ec2_vpc_net_facts] *************************************************
    fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! The module ec2_vpc_net_facts was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."}

**Comment by wimnat** [comment]
This module wasn't in the 2.0 release.  The version_added in the module doc is wrong.

**Comment by MichaelBaydoun** [comment]
Ok, thanks.  I would be happy to submit a pull request fixing the documentation, if you know in what version it's slated to be released?

**Comment by wimnat** [comment]
2.1

**Comment by nitzmahone** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by nitzmahone** [comment]
Also merged to stable-2.0.
