### ISSUE TITLE
zabbix_host TypeError on host update without interfaces

### ISSUE THREAD

**Issue by rpettersen** [ansible/ansible-modules-extras#1616]
I get the following exception when updating a host without specifying interfaces:

> An exception occurred during task execution. The full traceback is:
> Traceback (most recent call last):
>   File "/home/plldp/.ansible/tmp/ansible-tmp-1454663921.27-43711125456205/zabbix_host", line 2430, in <module>
>     main()
>   File "/home/plldp/.ansible/tmp/ansible-tmp-1454663921.27-43711125456205/zabbix_host", line 464, in main
>     exist_interfaces, zabbix_host_obj, proxy_id):
>   File "/home/plldp/.ansible/tmp/ansible-tmp-1454663921.27-43711125456205/zabbix_host", line 334, in check_all_properties
>     if self.check_interface_properties(exist_interfaces, interfaces):
>   File "/home/plldp/.ansible/tmp/ansible-tmp-1454663921.27-43711125456205/zabbix_host", line 293, in check_interface_properties
>     if len(interfaces) >= 1:
> TypeError: object of type 'NoneType' has no len()

I would suggest checking if interfaces is set. Perhaps something like this in zabbix-host.py:

``` python
    # check the exist_interfaces whether it equals the interfaces or not
    def check_interface_properties(self, exist_interface_list, interfaces):
        interfaces_port_list = []
        if interfaces is not None:
          if len(interfaces) >= 1:
            for interface in interfaces
```

Line "if interfaces is not None:" was added.

**Comment by eikef** [comment]
This shouldn't crash, so your fix is a good idea. Running zabbix_host without specifying an interface should probably behave a bit differently than it does now (right now it acts as if no change was requested even if multiple interfaces are defined in Zabbix; you can't remove the last interface from a host in Zabbix though, so an empty list would be akin to state=absent if that were enforced.

In any case, thanks for your fix, I added it as PR #1753
