### ISSUE TITLE
Add force_basic_auth in modules zabbix_*

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-extras#1647]
Hello,

For Example, in module "uri" it's possible auth basic on option "force_basic_auth".

My zabbix server is setup with authentification basic (nginx).
The module "zabbix_host" don't authentication successfully (401 :/).

The module zabbix-api (https://github.com/gescheit/scripts/tree/master/zabbix) support auth basic.

Is it possible to integrate option "force_basic_auth" in all zabbix modules ?

Regards,

**Comment by thelan** [comment]
Hello,

I've build a patch from branch stable-2.0
https://github.com/ansible/ansible-modules-extras/compare/stable-2.0...thelan:patch-zabbix-httpauth

This needs a test

**Comment by ghost** [comment]
Hello thelan,

I am test feature Monday ;)

Thanx

**Comment by thelan** [comment]
See pull request #1665

**Comment by ghost** [comment]
The test is good,

option : 
http_login_user
http_login_password

Problem to very long password contact zabbix API : https://github.com/gescheit/scripts/pull/23

Regards,
