### ISSUE TITLE
rabbitmq_user: Ansible HEAD incorrectly treats permissions as a string instead of a list

### ISSUE THREAD

**Issue by bradwilson** [ansible/ansible-modules-extras#1668]
##### Issue Type:

Bug Report
##### Ansible Version:

Using ansible from source, commit @f6d2767ce9c05de2a0aefdc36e01ca95b74343a4.
##### Ansible Configuration:

There is no /etc/ansible/ansible.cfg.
##### Environment:

Ubuntu 14.04 (though this is presumably not environment specific)
##### Summary:

We move forward with ansible to use new features, and we discovered that a recent commit somewhere (unsure where) has caused `rabbitmq_user` to be broken when setting permissions. The issue appears to be that `AnsibleModule` is taking the `arg_spec` for `permissions`, which defaults to `list()`, and treating it as a string. The simple fix is to add `type = 'list'` to the specification.
##### Steps To Reproduce:

Any playbook which attempts to use `rabbitmq_user` with individual permissions will yield the error. For example:

``` yml
rabbitmq_user:
  vhost: /
  user: Administrator
  password: SuperSecretPassword
  configure_priv: .*
  read_priv: .*
  write_priv: .*
  tags: administrator
```
##### Expected Results:

Creates the user, with the given permission set for the given vhost.
##### Actual Results:

`fatal: [HOSTNAME]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "rabbitmq_user"}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1455569966.79-87099881650599/rabbitmq_user\", line 2345, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1455569966.79-87099881650599/rabbitmq_user\", line 289, in main\r\n    rabbitmq_user.set_permissions()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1455569966.79-87099881650599/rabbitmq_user\", line 206, in set_permissions\r\n    if permission not in self.permissions:\r\nTypeError: 'in <string>' requires string as left operand, not dict\r\n", "msg": "MODULE FAILURE", "parsed": false}`

**Comment by bcoca** [comment]
fixed by merged #1669
