### ISSUE TITLE
win_webpicmd_module doc error

### ISSUE THREAD

**Issue by taraslayshchuk** [ansible/ansible-modules-extras#1678]
##### ISSUE TYPE

Documentation Report
##### ANSIBLE VERSION

N/A
##### SUMMARY

There is proposal at win_webpicmd_module [description](http://docs.ansible.com/ansible/win_webpicmd_module.html#notes) to use win_reboot module, but I cannot find it in ansible [win modules list](http://docs.ansible.com/ansible/list_of_windows_modules.html)
By the way most of modules contains information about features which were added in 2.1, but 2.1 has not been released yet.

**Comment by jctanner** [comment]
@taraslayshchuk since this affects ansible documentation, could you please re-file it at https://github.com/ansible/ansible/issues ?

**Comment by nitzmahone** [comment]
@taraslayshchuk - nevermind, docs with win_reboot had been written, just hadn't been pushed when you filed this. It's listed normally with the others now.
