### ISSUE TITLE
datacenter/dc parameter is not available on modules consul_session, consul_kv respectively

### ISSUE THREAD

**Issue by tadanki** [ansible/ansible-modules-extras#1693]
##### Issue Type:
- Bug Report
  ##### Plugin Name:
  consul_kv
  consul_session
  ##### Ansible Version:
  2.0.0

```
ansible 2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Please mention any settings you've changed/added/removed in ansible.cfg
(or using the ANSIBLE_\* environment variables).
##### Environment:

Ubuntu Trusty Tahr: 14.04 (up to date)
##### Summary:

Unable to use the "**datacenter**" for consul_session/ consul_kv
- name: register basic session with consul
  consul_session:
    host: "{{consul_server_name}}"
    name: "trialsession"
    datacenter: "{{consul_datacenter}}"

Output: 
fatal: [ip]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: datacenter"}

**Comment by mscherer** [comment]
Indeed, seems the support is missing. Can you check my PR ( #1721 ) to see if that fix the issue ? I do not have consul installed nor a idea on how to test it.
