### ISSUE TITLE
Managing systemd timers

### ISSUE THREAD

**Issue by exploide** [ansible/ansible-modules-extras#1695]
##### Issue Type:
- Feature Idea
##### Plugin Name:

systemd_timer
##### Description:

As far as I know, there is no idempotent way to manage (start, stop, enable, disable) systemd timers, yet (pls correct me if I'm wrong). The service module is only able to handle service units but systemd supports much more (e.g. timers, sockets, ...).

I would need a module capable to manage timer units, in my case to have an idempotent way to enable and start dnf-automatic.timer. I don't know if I have time to build such a module soon, but I would anyway like to know if this is something Ansible would appreciate.

I ask this because I can think of different ways to achieve the goal.
- Modifying the service module (IMHO bad because already complex, not systemd centric, ...)
- One systemd module (may conflict with service module, may be complex)
- Several systemd_xxx modules (i.e. _timer, _socket, ...)

Personally I prefer the last one, because it is the most simple (so one (maybe I) can start with one particular unit support, e.g. timer) and it looks similar to the way other complex modules are structured (e.g. mysql_db, mysql_user, mysql_variables). But I would like to hear the opinion of experienced Ansible devs and users.

**Comment by djmattyg007** [comment]
The `service` module can absolutely start, stop, enable and disable timer units, socket units, etc. When passing in the name of the service, just pass in "sshd.socket" or "ntp.timer" or whatever it is.

**Comment by exploide** [comment]
Oh, your are right. I thought I checked that earlier and it did not work, but apparently this is a solution.

Thanks, I'll close this ticket now.
