### ISSUE TITLE
mongodb_user always says changed

### ISSUE THREAD

**Issue by Dufgui** [ansible/ansible-modules-extras#1731]
##### Ansible Configuration:

Nothing
##### Environment:

N/A
##### Summary:

When i execute twice time the plugin, he always say the plugin has changed something.
Even with update_password=on_create
##### Steps To Reproduce:

```

---
- mongodb_user: login_user={{ mongodb3_admin_user }} login_password={{ mongodb3_admin_password }} login_port={{ mongodb3_mongos_port }} login_database=admin database={{ item.db }} name={{ item.name }} password={{ item.passwd }} roles={{ item.roles | join(",") }} state=present update_password=on_create
  with_items: mongodb3_users
  run_once: true

- mongodb_user: login_user={{ mongodb3_admin_user }} login_password={{ mongodb3_admin_password }} login_port={{ mongodb3_mongos_port }} login_database=admin database={{ item.db }} name={{ item.name }} password={{ item.passwd }} roles={{ item.roles | join(",") }} state=present update_password=on_create
  with_items: mongodb3_users
  run_once: true


```
##### Expected Results:

when the second play is executed we must have "ok" status.
I see it's complicated du to mongo python wich not return any status on add user. But we can do a usersInfo command before and compare result (except for password)
##### Actual Results:

the second call return changed status

**Comment by raffomania** [comment]
I'm experiencing this too on version 2.0.0.2-2.

**Comment by Dufgui** [comment]
i try to do a patch

**Comment by Dufgui** [comment]
it's not perfect, because we cannot manage in case of update password but it's better

**Comment by raffomania** [comment]
Thanks @Dufgui, that's something at least. If I understand it right then the real problem here is pymongo's `add_user` function not giving any information regarding changes that happened.
