### ISSUE TITLE
Fix Argument Specs for arguments without `type`

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-modules-extras#1732]
In https://github.com/ansible/ansible/commit/62765858825173dd532827fe4c1dfb246eb8db47 we made a change to default all arguments without an explicit `type` to be `'str'` type.

This has been known to cause issues in numerous modules.

Here is a list of modules that do not supply `type`, and that have a default that is not an instance of `basestring`:
- a10_server.py
- a10_service_group.py
- a10_virtual_server.py
- airbrake_deployment.py
- alternatives.py
- bigip_monitor_http.py
- bigip_monitor_tcp.py
- bigpanda.py
- blockinfile.py
- boundary_meter.py
- bower.py
- bundler.py
- bzr.py
- campfire.py
- capabilities.py
- circonus_annotation.py
- clc_aa_policy.py
- clc_alert_policy.py
- clc_blueprint_package.py
- clc_firewall_policy.py
- clc_group.py
- clc_loadbalancer.py
- clc_modify_server.py
- clc_server.py
- clc_server_snapshot.py
- cloudtrail.py
- composer.py
- consul.py
- consul_acl.py
- consul_kv.py
- consul_session.py
- cpanm.py
- cronvar.py
- crypttab.py
- cs_account.py
- cs_affinitygroup.py
- cs_domain.py
- cs_facts.py
- cs_firewall.py
- cs_instance.py
- cs_instancegroup.py
- cs_ip_address.py
- cs_iso.py
- cs_loadbalancer_rule.py
- cs_loadbalancer_rule_member.py
- cs_network.py
- cs_portforward.py
- cs_project.py
- cs_securitygroup.py
- cs_securitygroup_rule.py
- cs_sshkeypair.py
- cs_staticnat.py
- cs_template.py
- cs_user.py
- cs_vmsnapshot.py
- cs_volume.py
- datadog_event.py
- datadog_monitor.py
- deploy_helper.py
- dnf.py
- dnsimple.py
- dnsmadeeasy.py
- docker_login.py
- dpkg_selections.py
- ec2_elb_facts.py
- ec2_eni.py
- ec2_eni_facts.py
- ec2_remote_facts.py
- ec2_vol_facts.py
- ec2_vpc_igw.py
- ec2_vpc_net_facts.py
- ec2_vpc_route_table.py
- ec2_vpc_route_table_facts.py
- ec2_vpc_subnet.py
- ec2_vpc_subnet_facts.py
- ec2_win_password.py
- ecs_cluster.py
- ecs_service.py
- ecs_service_facts.py
- ecs_task.py
- ecs_taskdefinition.py
- elasticsearch_plugin.py
- expect.py
- filesystem.py
- firewalld.py
- flowdock.py
- getent.py
- github_hooks.py
- gluster_volume.py
- haproxy.py
- hipchat.py
- homebrew_cask.py
- homebrew_tap.py
- irc.py
- jabber.py
- jboss.py
- jira.py
- kernel_blacklist.py
- layman.py
- librato_annotation.py
- locale_gen.py
- logentries.py
- lvg.py
- lvol.py
- macports.py
- mail.py
- modprobe.py
- mongodb_user.py
- monit.py
- mqtt.py
- mysql_replication.py
- nagios.py
- netscaler.py
- newrelic_deployment.py
- nexmo.py
- npm.py
- open_iscsi.py
- openbsd_pkg.py
- openvswitch_bridge.py
- openvswitch_db.py
- openvswitch_port.py
- opkg.py
- os_keystone_domain.py
- os_project.py
- osx_defaults.py
- osx_say.py
- ovirt.py
- pagerduty.py
- pagerduty_alert.py
- patch.py
- pear.py
- pingdom.py
- pkg5_publisher.py
- pkgin.py
- pkgutil.py
- portage.py
- portinstall.py
- postgresql_ext.py
- postgresql_lang.py
- profitbricks.py
- profitbricks_datacenter.py
- profitbricks_nic.py
- profitbricks_volume.py
- profitbricks_volume_attachments.py
- proxmox.py
- proxmox_template.py
- puppet.py
- pushover.py
- rabbitmq_parameter.py
- rabbitmq_plugin.py
- rabbitmq_policy.py
- rabbitmq_user.py
- rabbitmq_vhost.py
- rax_clb_ssl.py
- rax_mon_alarm.py
- rax_mon_check.py
- rax_mon_entity.py
- rax_mon_notification.py
- rax_mon_notification_plan.py
- redis.py
- riak.py
- rollbar_deployment.py
- route53_facts.py
- route53_health_check.py
- route53_zone.py
- s3_bucket.py
- s3_lifecycle.py
- s3_logging.py
- selinux_permissive.py
- sendgrid.py
- seport.py
- snmp_facts.py
- sns.py
- solaris_zone.py
- sqs_queue.py
- stackdriver.py
- sts_assume_role.py
- svc.py
- svr4pkg.py
- swdepot.py
- taiga_issue.py
- twilio.py
- typetalk.py
- ufw.py
- uptimerobot.py
- urpmi.py
- vca_fw.py
- vca_nat.py
- vca_vapp.py
- vertica_configuration.py
- vertica_facts.py
- vertica_role.py
- vertica_schema.py
- vertica_user.py
- virt.py
- virt_net.py
- virt_pool.py
- vsphere_copy.py
- webfaction_app.py
- webfaction_db.py
- webfaction_domain.py
- webfaction_mailbox.py
- webfaction_site.py
- yumrepo.py
- zabbix_group.py
- zabbix_maintenance.py
- znode.py
- zypper_repository.py

There may be more, but this list is a start.

**Comment by thaumos** [comment]
Are we expecting type to be required for all modules args going forward?

**Comment by jeinwag** [comment]
It looks like the docker module itself is also broken because of this:

```
TASK [deploy container] ********************************************************
fatal: [myhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

**Comment by thaumos** [comment]
@jeinwag, can you provide a snippet of the task?

**Comment by jeinwag** [comment]
@thaumos sure:

```
- name: start docker container
  hosts: 127.0.0.1
  tasks:      
    - name: start container
      docker:
        name: nginx-test
        image: nginx
        state: reloaded

```

Result:

```
PLAY [start docker container] **************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [start container] *********************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

Adding an explicit int type to the parameters `memory_limit`, `memory_swap` and  `cpu_shares` in the docker module fixes the problem for me.

**Comment by mscherer** [comment]
So, I have been trying to look at the list, but I most of the time fail to understand the exact issue. Could you tell us how you did generate it ?

**Comment by sivel** [comment]
@mscherer the issue is that recently, per the commit referenced in the initial comment, if a `type` is not specified, we default the type to `str`.  As such, where a `bool` would have been allowed previously, no longer works, as we are casting the value of that arg to a string now.

@abadger has improved upon my detection method which can be found at https://github.com/ansible/ansible-modules-core/issues/3111#issuecomment-190061027

Effectively, we modify `basic.py` and `test-module` so that we can echo out arguments we need to look into further for each module.

**Comment by sivel** [comment]
> Are we expecting type to be required for all modules args going forward?

@thaumos we haven't come to that conclusion yet.  Effectively we have "changed" the default of `type` to `str`, so we need to ensure that we resolve all places where the `type` should be something other than `str` and where it is not explicitly set.

**Comment by fdemmer** [comment]
@sivel 

> Effectively, we modify basic.py and test-module so that we can echo out arguments we need to look into further for each module.

i am wondering why this issue was closed with just a mention of some issue with docker and only a single reference to a commit. does this mean all the modules, that do not define a type from the published list have been reviewed, tested and found to be working as before https://github.com/ansible/ansible/commit/62765858825173dd532827fe4c1dfb246eb8db47?

webfaction_app is definitely broken now, when not using the "machine" parameter, which defaults to `False`, which is now `"False"` a truthy value.
