### ISSUE TITLE
Composer module won't work as expected

### ISSUE THREAD

**Issue by jnardiello** [ansible/ansible-modules-extras#175]
On `ansible 1.7.2` whenever I try to use `composer: command=install working_dir=/path/to/project` the task fails:

```
TASK: [Running composer install] **********************************************
failed: [default] => {"failed": true}
msg: unsupported parameter for module: command

FATAL: all hosts have already failed -- aborting
```

**Comment by daysofwineandroses** [comment]
It seems the command parameter was only added in 1.8: http://docs.ansible.com/composer_module.html

**Comment by bcoca** [comment]
closign as per @daysofwineandroses comment, this is not supposed to work in 1.7

**Comment by jnardiello** [comment]
Agree, thanks to both.
