### ISSUE TITLE
zabbix modules use deprecated "exists" api methods that are removed in zabbix 3.0

### ISSUE THREAD

**Issue by kepstin** [ansible/ansible-modules-extras#1759]
##### Issue Type:
- Bug Report
##### Plugin Name:

I hit the error in:
zabbix_maintenance

These modules also appear to be affected:
zabbix_group
zabbix_host
zabbix_hostmacro
##### Ansible Version:

```
ansible 1.9.4 (stable-1.9 309996504f) last updated 2015/11/26 11:27:04 (GMT -400)
  lib/ansible/modules/core: (detached HEAD eda33a45e0) last updated 2015/06/17 11:13:07 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 8c01513e1e) last updated 2015/06/17 11:13:07 (GMT -400)
  configured module search path = None
```

(I've confirmed that the issue still exists in the current ansible-modules-extra via source inspection)
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

When using the zabbix_\* modules listed above against a zabbix 3.0 server, you get errors like the following:

```
TASK: [zabbix_maintenance ] *************************************************** 
failed: [host.example.com -> localhost] => {"failed": true}
msg: Failed to check maintenance Ansible host.example.com existance: (u'Error -32602: Invalid params., Incorrect method "maintenance.exists". while sending {"params": {"name": "Ansible host.example.com"}, "jsonrpc": "2.0", "method": "maintenance.exists", "auth": "REDACTED", "id": 1}', -32602)
```

This is because the module is calling the "exists" method that was deprecated in zabbix 2.4, and removed in zabbix 3.0:
https://www.zabbix.com/documentation/3.0/manual/api/changes_2.4_-_3.0

There isn't really a direct replacement; it might make sense to do a 'get', then depending on the status either take no action, or do an 'update' or 'create'. (This shouldn't reduce compatibility with older zabbix versions, I think.)

**Comment by eikef** [comment]
When those 3 PRs are committed the issue should be solved. Thanks :-)

**Comment by gregdek** [comment]
Thanks @eikef!

**Comment by wellumies** [comment]
.exists still in use in ansible (2.0.2.0)

`fatal: [proxy.test.fi -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "zabbix_host"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/wellumies/.ansible/tmp/ansible-tmp-1463131327.88-166717803723139/zabbix_host\", line 2479, in <module>\n    main()\n  File \"/home/wellumies/.ansible/tmp/ansible-tmp-1463131327.88-166717803723139/zabbix_host\", line 437, in main\n    is_host_exist = host.is_host_exist(host_name)\n  File \"/home/wellumies/.ansible/tmp/ansible-tmp-1463131327.88-166717803723139/zabbix_host\", line 166, in is_host_exist\n    result = self._zapi.host.exists({'host': host_name})\n  File \"/usr/local/lib/python2.7/dist-packages/zabbix_api.py\", line 314, in method\n    return self.universal(\"%s.%s\" % (self.data[\"prefix\"], name), opts[0])\n  File \"/usr/local/lib/python2.7/dist-packages/zabbix_api.py\", line 71, in wrapper\n    return self.do_request(self.json_obj(method, opts))['result']\n  File \"/usr/local/lib/python2.7/dist-packages/zabbix_api.py\", line 321, in do_request\n    return self.parent.do_request(req)\n  File \"/usr/local/lib/python2.7/dist-packages/zabbix_api.py\", line 272, in do_request\n    raise ZabbixAPIException(msg, jobj['error']['code'])\nzabbix_api.ZabbixAPIException: (u'Error -32602: Invalid params., Incorrect method \"host.exists\". while sending {\"params\": {\"host\": \"proxy.test.fi\"}, \"jsonrpc\": \"2.0\", \"method\": \"host.exists\", \"auth\": \"0ffe794c53bc1a13380403b7f6c42729\", \"id\": 2}', -32602)\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}`
