### ISSUE TITLE
yum_repository use with_items to manage multiple files

### ISSUE THREAD

**Issue by ofsole** [ansible/ansible-modules-extras#1781]
##### Issue Type:

Please pick one and delete the rest:
- Feature Idea
##### Plugin Name:

yum_repository
##### Ansible Version:

2.1
##### Summary:

```
- name: Add repository
  yum_repository:
    name: "{{item.name}}"
    file: "{{item.file}}"
    description: "{{item.desc}}"
    baseurl: "{{item.baseurl}}"
  with_items:
  - {
    name: 'car'
    file: 'file1'
    desc: 'ceshi1'
    baseurl: 'http://ceshi1.com'
  }
  - {
    name: 'bus'
    file: 'file2'
    desc: 'ceshi2'
    baseurl: 'http://ceshi2.com'
  }
```

didn't work.
##### Steps To Reproduce:

ERROR: Syntax Error while loading YAML script, /etc/ansible/roles/proxy/tasks/main.yml
Note: The error may actually appear before this position: line 24, column 9

```
name: car
file: file1
```
##### Expected Results:

create multiple repo files
##### Actual Results:

What actually happened?

```
(Paste verbatim command output here)
```

**Comment by bcoca** [comment]
invalid yaml, you are mixing shorthand and normal format, just remove the  { } and it will work

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ofsole** [comment]
Hi Bcoca
Thanks for your quick response, It works.
