### ISSUE TITLE
Change status of an issue is not working (for me only?)

### ISSUE THREAD

**Issue by offlinehoster** [ansible/ansible-modules-extras#1791]
##### Issue Type:
- Bug Report
##### Plugin Name:

jira
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

default
##### Environment:

N/A
##### Summary:

Would like to change the status of an issue from open to close.
##### Steps To Reproduce:

```
- name: Close the issue
  jira: uri={{jiraserver}} username={{admin_account}} password={{admin_password}}
        issue={{issue.meta.key}} operation=transition status="Done"
```
##### Expected Results:

I would expect that the given issue is marked as Done
##### Actual Results:

```
}, "module_name": "jira"}, "msg": "Failed find valid transition for "Done""}

```

Is there a better shown "example" what to use for "status=" ? I also tried the id of the transition, the german name..but i dont get it.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

From my Jira knowledge the message is basically saying that according to Jira workflow rules you cannot put the issue into state 'Done' from it's current state as the workflow does not allow for it.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by offlinehoster** [comment]
Closed because of what. This module is not working as expected.
