### ISSUE TITLE
win_updates: undefined property

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible-modules-extras#1803]
##### Issue Type:
- Bug Report
##### Plugin Name:

win_updates
##### Ansible Version:

2.0

the updates module will try to kill a task that is already running. BUT on some systems the (tested with 2008R2 and 2012R2) the $task_to_stop.InstanceId is not available. Therefore $task_to_stop.InstanceGuid should be used, which is available on all server systems 

```
$schedserv = New-Object -ComObject Schedule.Service
Write-DebugLog "Connecting to scheduler service..."
$schedserv.Connect()
Write-DebugLog "Getting running tasks named $job_name"
$running_tasks = @($schedserv.GetRunningTasks(0) | Where-Object { $_.Name -eq $job_name })

Foreach($task_to_stop in $running_tasks) {
  Write-DebugLog "Stopping running task $($task_to_stop.InstanceId)..."
  $task_to_stop.Stop()
}
```

**Comment by h0nIg** [comment]
ping: @petemounce @nitzmahone

**Comment by nitzmahone** [comment]
fixed in https://github.com/ansible/ansible-modules-extras/commit/5abb914315864b714395863af99c0ac1bd66a7ba
