### ISSUE TITLE
Connect to windows host timed out port 22

### ISSUE THREAD

**Issue by sparkvilla** [ansible/ansible-modules-extras#1810]
##### Plugin Name:

win_ping
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

```
[defaults]
hostfile = ./hosts
```
##### Environment:

Ubuntu15.10 as localhost

Windows10 virtual machine (VM) target host running on Ubuntu server
##### Summary:

Hi, I am trying to use win_ping to connect to a windows10 host (this is a virtual machine on a server running ubuntu) through Ansible.

I followed the Ansible windows support (http://docs.ansible.com/ansible/intro_windows.html#inventory) and create a folder containing the 
`hosts` inventory file:
    [testserver]
    # This is Win10 VM on testserver 
    win2 ansible_host=IP

and a subfolder `group_vars` containing windows.yml:
    ansible_user: my_user
    ansible_password: my_pass
    ansible_port: 5986
    ansible_connection: winrm
    # The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
    ansible_winrm_server_cert_validation: ignore

I also run the ConfigureRemotingForAnsible.ps1 on windows10 host to configure WinRM. However, when I run the `win_ping` module it does not connect to the host.  
##### Steps To Reproduce:

Here is the command that I run with the debugging mode on:

```
ansible win2 -m win_ping -vvvv
```

and that is my output:

```
    win2 | UNREACHABLE! => {
        "changed": false, 
        "msg": "SSH encountered an unknown error. The output was:\nOpenSSH_6.9p1 Ubuntu-2ubuntu0.1, OpenSSL 1.0.2d 9 Jul 2015\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r    \ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/diego/.ansible/cp/ansible-ssh-130.60.25.228-22-diego\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to 130.60.25.228 [130.60.25.228] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 130.60.25.228 port 22: Connection timed out\r\nssh: connect to host 130.60.25.228 port 22: Connection timed out\r\n", 
        "unreachable": true
}

```

I would also like to mention that on my server I have other ubuntu VMs which I can ping from my localhost . Any help? thank you

**Comment by jhawkesworth** [comment]
Ok so the name of the file in your group_vars folder (windows.yml) needs to agree with the group name in your inventory.

So either change your host group name from [testserver] to [windows]
or rename your group_vars/windows.yml to be group_vars/testserver.yml

If you are interested, the clue here is that ansible is still trying to connect via SSH, which implies that your group vars aren't being taken into consideration.

**Comment by sparkvilla** [comment]
I changed the name of the file in group_var to testserver.yml but still not working. The problem is  the ConfigureRemotingForAnsible.ps1 does not run properly, i.e. it throws an error. Sorry but I didn't notice that before. Unfortunately my windows10 is in german so is gonna take me some time to understand the error..

**Comment by nitzmahone** [comment]
@sparkvilla still having trouble with this, or shall we close?

**Comment by sparkvilla** [comment]
@nitzmahone not anymore you can close it. Thank you

**Comment by jhawkesworth** [comment]
Closed at the request of @sparkvilla
