### ISSUE TITLE
Feature Idea: Use expect with with_items

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible-modules-extras#1820]
##### Issue Type:
- Feature Idea
##### Module Name:

[Expect Module](http://docs.ansible.com/ansible/expect_module.html)
##### Ansible Version:

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:
- Amazon Linux 

```
NAME="Amazon Linux AMI"
VERSION="2015.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.09"
PRETTY_NAME="Amazon Linux AMI 2015.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```
- Python 2.7.10
##### Summary:

I am trying to use `expect` module with `with_items`
##### Steps To Reproduce:

This is a samle 

``` yaml
- expect:
    command: /some/script {{ item }}
    with_items: 
      - hello
      - me
    responses:
      "some_response": 'yes'
```
##### Expected Results:

`with_items` should work like in any other module
##### Actual Results:

What actually happened?

```
fatal: [my_server]: FAILED! => {"failed": true, "msg": "ERROR! 'item' is undefined"}
```

**Comment by sivel** [comment]
Your `with_items` is indented too far.  It should be at the same level as the word `expect` not nested inside it.

**Comment by vikas027** [comment]
@sivel Thanks for catching that. It works now. Not sure if this can be put in a check with some meaningful error like in other modules.
