### ISSUE TITLE
Getent module's fail_key parameter does not work correctly with False or equivalents

### ISSUE THREAD

**Issue by daysofwineandroses** [ansible/ansible-modules-extras#183]
##### Issue Type:

Bug Report
##### Ansible Version:

Both stable and devel:

ansible 1.8.2
  configured module search path = None

ansible 1.9 (devel fe53d86a83) last updated 2015/01/06 08:46:10 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 0d551d8d24) last updated 2015/01/06 08:50:12 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD d4f5b6d41a) last updated 2015/01/06 08:50:12 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/12/16 07:51:34 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/12/16 07:51:45 (GMT +200)
  configured module search path = None
##### Environment:

Running from Debian Testing.

Managing RHEL 6.6.
##### Summary:

Getent module fails looking up a nonexistent database entry when using fail_key=False parameter, while the expected behaviour is to succeed.
##### Steps To Reproduce:

Use getent to retrieve a nonexistent key in a database:

```
- name: getent test
  getent: database=passwd key=nonexistent fail_key=False

- debug: var=getent_passwd
```
##### Expected Results:

```
TASK: [getent test] ************************ 
ok: [<<REDACTED>>]

TASK: [debug var=getent_passwd] **********************************
ok: [<<REDACTED>>] => {
    "getent_passwd": {
        "nonexistent": null
    }
}
```
##### Actual Results:

```
TASK: [getent test] ************************ 
failed: [<<REDACTED>>] => {"failed": true}
msg: One or more supplied key could not be found in the database.

FATAL: all hosts have already failed -- aborting
```
##### Fix

The argument_spec entry for fail_key is missing "type='bool'":

```
diff --git a/system/getent.py b/system/getent.py
index 7da1be4..bb6d162 100644
--- a/system/getent.py
+++ b/system/getent.py
@@ -86,7 +86,7 @@ def main():
             database = dict(required=True),
             key      = dict(required=False, default=None),
             split    = dict(required=False, default=None),
-            fail_key = dict(required=False, default=True),
+            fail_key = dict(required=False, type='bool', default=True),
         ),
         supports_check_mode = True,
     )
```

**Comment by bcoca** [comment]
fix merged
