### ISSUE TITLE
Blockinfile module : Documentation mistake

### ISSUE THREAD

**Issue by schms** [ansible/ansible-modules-extras#1849]
##### Issue Type:
- Documentation Report
##### Plugin Name:

Blockinfile module
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file = /data/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

n.a.
##### Environment:

n.a
##### Summary:

Wrong spacing in official documentation
##### Steps To Reproduce:

```
https://docs.ansible.com/ansible/blockinfile_module.html
Chapter Example, last example using < with_items >
```
##### Expected Results:

Expression with_items: should be level with blockinfile:
##### Actual Results:

```
Example does not work as expression < with_items: > is not level with  <blockinfile:> 
```

**Comment by bcoca** [comment]
closed via merged #1873
