### ISSUE TITLE
no module named rpm ?

### ISSUE THREAD

**Issue by smilejay** [ansible/ansible-modules-extras#1920]
##### OS / ENVIRONMENT

CentOS 5 and CentOS 7.
##### SUMMARY

There's a 'yum' module in ansible, but I didn't find a module only for manipulating RPM packages. For example, I want 'rpm -V' command to verify a package, or use 'rpm -i --force' to install a package forcefully. 
I want to use existing ansible modules instead of writing a new one. (I know 'shell' module should work, but I don't think it's a good way.)
Any suggestion for me?  Thanks in advance.

**Comment by resmo** [comment]
please use mailing list or irc for questions.
