### ISSUE TITLE
Ansible 1.8.2, module: lvg. Creation of volume group with symlink in pvs list is not idempotent.

### ISSUE THREAD

**Issue by iprok** [ansible/ansible-modules-extras#197]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Ansible on Gentoo amd64. 
##### Summary:

Creation of volume group with symlink in pvs list is not idempotent. When symlink is in pvs list should check vg members with real devices not link name.
##### Steps To Reproduce:

ls -l /dev/md/raid1 
lrwxrwxrwx 1 root root 8 Jan 12 18:26 /dev/md/raid1 -> ../md127

Repeat the task at least twice:
- name: create raid1 vg
  
  lvg: vg=raid1 pvs=/dev/md/raid1
  
  tags: storage
##### Expected Results:

Create at the first run, ok on the second and next runs.
##### Actual Results:

TASK: [create raid1 vg] ******************************************************\* 
failed: [s1.ifab.ru] => {"err": "  Can't initialize physical volume \"/dev/md/raid1\" of volume group \"raid1\" without -ff\n", "failed": true, "rc": 5}
msg: Creating physical volume '/dev/md/raid1' failed

**Comment by silvax** [comment]
Please fix this. This is a big problem for one of my projects. Thanks

**Comment by wimnat** [comment]
@silvax did you try using the PR i submitted above?
