### ISSUE TITLE
mkfs.xfs uses -f instead of -F flag

### ISSUE THREAD

**Issue by jravetch** [ansible/ansible-modules-extras#20]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

1.7.2
##### Environment:

Ubuntu 14.04
##### Summary:

mkfs.xfs uses the -f instead of -F flag to force creating a filesystem on devices that have an existing filesystem #18 
##### Steps To Reproduce:

filesystem: fstype=xfs dev=/dev/sdb1 force=yes
##### Expected Results:

device formatted as xfs
##### Actual Results:

xfs uses the -f flag to force creating a filesystem on a devices that have an existing filesystem; however, -F flag is being passed, which mkfs.xfs doesn't accept.

**Comment by Jmainguy** [comment]
https://github.com/ansible/ansible-modules-extras/pull/18

Addressed this issue. I believe this can be closed.

**Comment by jravetch** [comment]
Yeah, just got the Ansibot complaining at me that I didn't format the issue properly.
