### ISSUE TITLE
blockinfile: check mode and create: yes does not work when file does not exist yet

### ISSUE THREAD

**Issue by AdamAtCSD** [ansible/ansible-modules-extras#2021]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

ansible 2.0.1.0  
  config file = /etc/ansible/ansible.cfg  
  configured module search path = Default w/o overrides 
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

CentOS 7.1.1503
##### SUMMARY

ansible-playbook ... --check
Fails my blockinfile task because the file(s) do not exist yet. The create=yes is properly set and during the run the system responds with "no such file or directory" errors.
##### STEPS TO REPRODUCE

Create a playbook that simply deals with a non-existent file:
- name: just testing
  blockinfile:
      dest: /etc/foobar.conf
      create: yes
      block: |
          Just for fun
          Another line 

Now run ansible-playbook --check on the file
##### EXPECTED RESULTS

The --check will fail because the file doesn't exist.
##### ACTUAL RESULTS

Here's the results from the above with --check -vvv:

```
ESTABLISH LOCAL CONNECTION FOR USER: root                                                                                                             
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626 `" && echo "` echo $HOME/.ansib 
le/tmp/ansible-tmp-1460553033.3-236522183380626 `" )'                                                                                                 
localhost PUT /tmp/tmpjnUhnA TO /root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile                                               
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1460553033.3-23 
6522183380626/blockinfile; rm -rf "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/" > /dev/null 2>&1'                                    
An exception occurred during task execution. The full traceback is:                                                                                   
Traceback (most recent call last):                                                                                                                    
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 2457, in <module>                                              
    main()                                                                                                                                            
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 292, in main                                                   
    msg, changed = check_file_attrs(module, changed, msg)                                                                                             
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 166, in check_file_attrs                                       
    if module.set_file_attributes_if_different(file_args, False):                                                                                     
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 1308, in set_file_attributes_if_different                      
    return self.set_fs_attributes_if_different(file_args, changed)                                                                                    
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 1300, in set_fs_attributes_if_different                        
    file_args['path'], file_args['mode'], changed                                                                                                     
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 1135, in set_mode_if_different                                 
    path_stat = os.lstat(path)                                                                                                                        
OSError: [Errno 2] No such file or directory: '/etc/foobar.conf'                                                                                      

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "blockinfile"}, "parsed": false} 
```

**Comment by aaakbar** [comment]
2.0.2 also has the same problem

**Comment by der-ali** [comment]
ansible 2.1.1.0
The problem is still present

> fatal: [TestVM]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_isHUX1/ansible_module_blockinfile.py\", line 313, in <module>\r\n    main()\r\n  File \"/tmp/ansible_isHUX1/ansible_module_blockinfile.py\", line 306, in main\r\n    msg, changed = check_file_attrs(module, changed, msg)\r\n  File \"/tmp/ansible_isHUX1/ansible_module_blockinfile.py\", line 178, in check_file_attrs\r\n    if module.set_file_attributes_if_different(file_args, False):\r\n  File \"/tmp/ansible_isHUX1/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1144, in set_file_attributes_if_different\r\n  File \"/tmp/ansible_isHUX1/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1136, in set_fs_attributes_if_different\r\n  File \"/tmp/ansible_isHUX1/ansible_modlib.zip/ansible/module_utils/basic.py\", line 958, in set_mode_if_different\r\nOSError: [Errno 2] No such file or directory: '/root/.ssh/config'\r\n", "msg": "MODULE FAILURE", "parsed": false}
