### ISSUE TITLE
Add install instructions to README

### ISSUE THREAD

**Issue by bittner** [ansible/ansible-modules-extras#206]
**Issue Type:** Documentation Report

**Ansible Version:** 1.8.2

**Environment:** N/A

**Summary:** Add install instructions to README. Neither the documentation nor the README of this repo mention how to install the extras-modules.

**Steps To Reproduce:** Go to the [README](https://github.com/ansible/ansible-modules-extras/blob/devel/README.md), [modules docs](http://docs.ansible.com/modules.html), [dev docs](http://docs.ansible.com/developing_modules.html) and try to find installation instructions for extras-modules.

**Expected Results:** The README should have an "Installation" chapter describing how to install the extras-modules (e.g. "pip install ansible-modules-extras" if there were such a pip package).

**Actual Results:** (see "_Steps To Reproduce_" above) -- nowhere installation of modules is mentioned.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.
- The modules in the ansible-modules-extras do not require extra install steps (hence the lack of instructions), they are already added to the base install along with ansible-modules-core in all the supported installation methods.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by larryon** [comment]
I have just installed ansible on ubuntu/trusty64 with vagrant and a lot of the extras-modules are not installed. 
vagrantfile :
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
#config.vm.box = "ubuntu/trusty64"
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.define "debian" do |debian|
  debian.vm.box = "ubuntu/trusty64"
  debian.vm.network "private_network", ip: "192.168.0.2"
  debian.vm.hostname ='debian1'
  debian.hostmanager.enabled = true
  debian.hostmanager.manage_host = true
  debian.vm.provision "shell", inline: <<-SHELL
  sudo apt-get -y update
  sudo apt-get -y install python-pip
  sudo apt-get -y install software-properties-common
  sudo apt-add-repository ppa:ansible/ansible
  sudo apt-get -y update
  sudo apt-get -y install python-dev libkrb5-dev
  sudo apt-get -y install ansible
  sudo pip install "pywinrm>=0.1.1"
  sudo pip install kerberos
  SHELL

end
end
