### ISSUE TITLE
iptables module incorrectl specifies --destination-port instead of --dport

### ISSUE THREAD

**Issue by Daemoen** [ansible/ansible-modules-extras#2100]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

iptables
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /srv/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
# Ansible Defaults
[defaults]
command_warnings=True
deprecation_warnings=True
display_skipped_hosts=False

# Optimization Settings
forks=25
gathering=explicit
timeout=5

# SSH Controls
control_path=/srv/ansible/sck/%%h-%%
host_key_checking=False
pipelining=True
scp_if_ssh=False

# Path Settings
local_tmp=/srv/ansible/tmp
log_path=/srv/ansible/logs/ansible.log
retry_files_save_path=/srv/ansible/retries
roles_path=/srv/ansible/roles

# Color/Cowsay
nocows=1
nocolor=0
```
##### OS / ENVIRONMENT

Ansible running from OSX (should be irrelevant)
Ansible managing EL6 (should be irrelevant)
##### SUMMARY

Destination port is not represented correctly, should be --dport not --destination-port, unless this varies by os.
##### STEPS TO REPRODUCE

```
- name: accept port 80 connections
  iptables:
    chain: INPUT
    source: 0.0.0.0/0
    ctstate: NEW,ESTABLISHED
    destination_port: 80
    jump: ACCEPT

```
##### EXPECTED RESULTS

Iptables rule created with port 80 accepted with connection states new and established from source anywhere.
##### ACTUAL RESULTS

```
fatal: [centos6-x64]: FAILED! => {"changed": false, "cmd": "/sbin/iptables -t filter -A INPUT -s 0.0.0.0/0 -j ACCEPT --destination-port 80 -m state --state NEW,ESTABLISHED", "failed": true, "msg": "iptables v1.4.7: unknown option `--destination-port'\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.7: unknown option `--destination-port'\nTry `iptables -h' or 'iptables --help' for more information.\n", "stdout": "", "stdout_lines": []}
```

**Comment by Oneiroi** [comment]
@Daemoen I hit this bug today, unsure why this report was closed as it still appears to be an issue ? 

```
failed: [vault1] (item=***.***.***.***) => {"cmd": "/sbin/iptables -t filter -A INPUT -s ***.***.***.*** -j ACCEPT --destination-port 8301 -m comment --comment Consul", "failed": true, "item": "***.***.***.***", "msg": "iptables v1.4.21: unknown option \"--destination-port\"\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.21: unknown option \"--destination-port\"\nTry `iptables -h' or 'iptables --help' for more information.\n", "stdout": "", "stdout_lines": []}
```

**Comment by sayantandas** [comment]
I also faced the same problem..

``FAILED! => {"changed": false, "cmd": "/sbin/iptables -t filter -A INPUT -p tcp -j ACCEPT --to-ports 5800 -m comment --comment 'Allow Real VNC' -m state --state ESTABLISHED", "failed": true, "msg": "iptables v1.4.7: unknown option`--to-ports'\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.7: unknown option`--to-ports'\nTry `iptables -h' or 'iptables --help' for more information.\n", "stdout": "", "stdout_lines": []}`

ansible code:

```
- name: open ports on firewall
  iptables: chain=INPUT protocol=tcp ctstate=ESTABLISHED state=present to_ports=5800 jump=ACCEPT comment="Allow Real VNC"
  become: yes
```

`

**Comment by shevasv** [comment]
When I tried to run next ansible code:
- name: open ports on firewall
  iptables: chain=INPUT  source="8.8.8.8" destination_port=53 jump=ACCEPT 

and got the same error .
After adding two parameters  "protocol=tcp match=tcp " the code running successfully.

**Comment by dglinder** [comment]
# For anyone coming back to this I didn't notice the answer in the above comments, so I'll re-address it here.

The error message that iptables provides is a bit misleading (correct, but misleading).  IPtables requires the "protocol" to be set, so you must set the protocol field (presumably "tcp").

Working example after adding "protocol:" field:

```
- name: accept port 80 connections
  iptables:
    chain: INPUT
    source: 0.0.0.0/0
    ctstate: NEW,ESTABLISHED
    destination_port: 80
    protocol: tcp
    jump: ACCEPT
```
