### ISSUE TITLE
extra modules update schedule at pypi

### ISSUE THREAD

**Issue by hdsiles** [ansible/ansible-modules-extras#2152]
Forgive any ignorance on my part, I was hopeful that someone could tell me how frequently pypi's package of ansible will be updated with changes to these ansible-modules-extras.  There are some updates that were put in place just a few hours ago, but before I start recommending people patch independently of doing a pip upgrade, I wanted to make sure that I have my facts straight.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
