### ISSUE TITLE
CI failing due to f5 folder missing __init__.py

### ISSUE THREAD

**Issue by rcarrillocruz** [ansible/ansible-modules-extras#2246]
I'm seeing the following failure consistently when pushing PRs on Travis:

```
============================================================================
./f5
============================================================================
ERROR: Ansible module subdirectories must contain an __init__.py
The command "ansible-validate-modules ." exited with 1.
```

A full test output can be seen on https://travis-ci.org/ansible/ansible-modules-extras/builds/130771932 .

This seems to be caused by commit 677a2dd66d5e1788eacc5d849ce6e1cc7d799833, it added a new module for f5 devices but lacks an **init**.py file.

**Comment by resmo** [comment]
#2247 has been merged. closing.
