### ISSUE TITLE
iptables: option to configure Source NAT

### ISSUE THREAD

**Issue by washingtoneg** [ansible/ansible-modules-extras#2291]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

system/iptables
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (devel de7b0e9da1) last updated 2016/05/24 15:42:31 (GMT -400)
  lib/ansible/modules/core: (devel aa995806b9) last updated 2016/05/24 15:46:14 (GMT -400)
  lib/ansible/modules/extras: (devel d1a4f703ce) last updated 2016/05/24 15:47:24 (GMT -400)
  config file = /Users/elenawashington/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux
##### SUMMARY

In order to change the source address of connections to something different, you have to pass `iptables` the `--to-source` option (more information can be found [here](http://www.netfilter.org/documentation/HOWTO/NAT-HOWTO-6.html#ss6.1)). According to the [`iptables` module documentation](https://docs.ansible.com/ansible/iptables_module.html) there is no option available to Source NAT. This option should be available in the `iptables` Ansible module.
##### EXPECTED RESULTS

This `iptables` command

```
iptables -t nat -A POSTROUTING -o eth0 -p tcp --dport 80 -d 10.0.0.0 -j SNAT --to-source 192.168.0.0
```

should be able to be defined like so:

<pre>
- name: Modify the packet's source address to forward traffic back to firewall to forward on to the client
  iptables:
    chain: POSTROUTING
    destination: 10.0.0.0 # IP of server behind firewall
    destination_port: 80
    jump: SNAT
    out_interface: eth0
    protocol: tcp
    table: nat
    <b>to_source: 192.168.0.0 # firewall IP</b>
  become: yes
</pre>

**Comment by nitzmahone** [comment]
closing: addressed by #2292
