### ISSUE TITLE
aws_mfa_devices returning bad results

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible-modules-extras#2313]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

aws_mfa_devices
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 7b5513cf22) last updated 2016/05/25 20:01:12 (GMT -400)
  lib/ansible/modules/core: (detached HEAD fb77ab49ab) last updated 2016/05/25 20:01:18 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 0e4a023a7e) last updated 2016/05/25 20:01:23 (GMT -400)
```
##### CONFIGURATION

[defaults]
retry_files_enabled = False
##### OS / ENVIRONMENT

OS X El Capitan Version 10.11.5
boto (2.39.0)
boto3 (1.3.0)
botocore (1.4.23)
##### SUMMARY

Error with aws_mfa_devices results
##### STEPS TO REPRODUCE

```
- name: retrieve mfa device info
  aws_mfa_devices:
    region: "us-east-1"
    user_name: testuser
  register: mfa_devices

- debug:
    var: "{{ mfa_devices.devices }}"

- debug:
    var: "{{ mfa_devices.devices[0].serial_number }}"
```
##### EXPECTED RESULTS

Expected to see valid results including token information
##### ACTUAL RESULTS

```
TASK [aws : retrieve mfa device info] ******************************************
changed: [localhost]

TASK [aws : debug] *************************************************************
ok: [localhost] => {
    "<type 'list'>": "VARIABLE IS NOT DEFINED!"
}

TASK [aws : debug] *************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "template error while templating string: expected token 'end of print statement', got ':'. String: {{arn:aws:iam::123456789:mfa/testuser}}"}
```

tagging module author @pwnall

**Comment by pwnall** [comment]
@MichaelBaydoun -- I think you need `var: mfa_devices.devices` -- as far as I know, `var` takes in the variable name, not the value. Can you try again after removing the brackets, and let me know what the output is?

**Comment by MichaelBaydoun** [comment]
@pwnall -- of course!  I'm so used to eliminating the bare variable deprecation warnings ... guess I got carried away.  Thanks!
