### ISSUE TITLE
win_regmerge does not verify command success, fails when reporting success

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible-modules-extras#2333]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_regmerge
##### ANSIBLE VERSION

v2.1
##### SUMMARY

The win_regmerge module does not report back if a command worked or failed, and does not return the command output. Not understanding why my Curses.reg was not working, I found out that the module could not find the file and actually returned:

```
ERROR: Error opening the file. There may be a disk or file system error.
```

It simply didn't look in `files/` as I was expecting. Despite this important error, the module reports:

```
changed: [windows1] => {"changed": true, "compared": false, "invocation": {"module_name": "win_regmerge"}}
```

That's rather important. If we want the Windows support in Ansible to shine, things like this basically kills the user experience.

PS I have similar problems with other modules, if things are not exactly as the module expects it silently fails with no clue to the user.

**Comment by jhawkesworth** [comment]
I originally wanted to add the ability to merge registry entries to the template module but discussion on the google group persuaded me to keep this separate.  I will investigate to see if it can be made to operate like copy (and even template) and use a source file on the ansible controller.
