### ISSUE TITLE
ec2_snapshot_facts sorting?

### ISSUE THREAD

**Issue by cheddarwhizzy** [ansible/ansible-modules-extras#2351]
I wrote my own ec2_snapshot_facts module before this was an official module, but mine was very simple in that it just returned the latest snapshot ID from a tag combination. Is there a way to get the latest snapshot using this module? Would just sorting by the start_time before returning the result set be sufficient?

Basically what I did was 

`self.snaps = self.ec2.get_all_snapshots(filters=tags)

 if len(self.snaps):
     sorted_snaps = sorted([(s.id, s.start_time) for s in self.snaps], key=lambda k: k[1])`

Then I returned 'sorted_snaps'

**Comment by nitzmahone** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
