### ISSUE TITLE
link_names option in Slack module doesn't work from the cli

### ISSUE THREAD

**Issue by futurekill** [ansible/ansible-modules-extras#240]
Hi,

I was just playing around with the Slack notification module before I put it into production and I ran into this weird behavior:

```
ansible -i hosts monitor\* -m slack -a "domain=myorg.slack.com token='REMOVED' msg=\"This should not be a link @james\" link_names=0"
monitor.myorg.com | FAILED >> {
    "failed": true,
    "msg": "value of link_names must be one of: 0,1, got: 0"
}
```

I can't seem to turn linking off from the command line.

**Comment by ramondelafuente** [comment]
@bcoca This seems to be a type-casting thing as this parameter is an `int` but doesn't seem to be accepted that way. But my python-fu is weak so I don't know the proper pythonic solution to this :(

**Comment by bcoca** [comment]
fixed via https://github.com/ansible/ansible/commit/2c9d1257ba59e01c093a901cf53a7323c56f4f85

check against choices array  was made before type check and conversion
