### ISSUE TITLE
Can't specify destination_port with iptables v1.4.7

### ISSUE THREAD

**Issue by danschmidt5189** [ansible/ansible-modules-extras#2423]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

`system/iptables.py`
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 62e6f6b885) last updated 2016/06/13 16:49:02 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 1d0f408897) last updated 2016/06/13 16:49:52 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 146c969c07) last updated 2016/06/13 16:50:29 (GMT -700)
  config file = <...>
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT
- Ansible machine: Mac OSX El Capitan (10.11.5)
- Target machines: Red Hat Enterprise Linux Server release 6.8 (Santiago)
##### SUMMARY

Ansible sends `destination_port` as `--destination-port`, but iptables v1.4.7 expects `--dport`. This is a new bug — previous Ansible versions sent `--dport` (and resulted in the expected output to `/etc/sysconfig/iptables`).

Other parameters (e.g. source_port) are probably also broken, but I haven't tested them.
##### STEPS TO REPRODUCE

Execute the `iptables` module with a `destination_port` parameter against a host running iptables v1.4.7 or lower:

```
- hosts: all
  tasks:
    - iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
```

Ansible will print an error like the following:

```
failed: [...] {"cmd": "/sbin/iptables -t filter -A INPUT -j ACCEPT --destination-port 80", "failed": true, "msg": "iptables v1.4.7: unknown option `--destination-port'\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.7: unknown option `--destination-port'\nTry `iptables -h' or 'iptables --help' for more information.\n", "stdout": "", "stdout_lines": []}
```

The key line is from iptables:

```
iptables v1.4.7: unknown option `--destination-port'
Try `iptables -h' or 'iptables --help' for more information.
```
##### EXPECTED RESULTS

Send the `destination_port` parameter as iptables expects. For iptables v1.4.7, that looks something like:

``` bash
iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
```

The result from the perspective of the Ansible runner should be that the iptables rules are added as expected, without error.

**Comment by danschmidt5189** [comment]
Ah, never mind, this is an iptables thing — you have to specify the protocol, which I hadn't in my actual example. And the API hasn't changed in ages. 👍 

Carry on...

**Comment by andreaskring** [comment]
@danschmidt5189 I am having the same problem. If possible, could you please provide the iptables task that resolved your issue?
