### ISSUE TITLE
Monit doesn't take pending state into consideration for whether a process is running

### ISSUE THREAD

**Issue by gaqzi** [ansible/ansible-modules-extras#244]
When determining whether a process is running through monit the module only checks for the presence of the string "running", which can lead to false positives when the process is waiting to be stopped.

The module should be updated to ensure that "stop pending" is not present as well.

Now monit doesn't support waiting for an action to finish, so if we wanted to then ensure the process was started then we would have to wait until the pending goes away and then re-evaluate. With some kind of timeout to determine whether monit has hung. 
Initializing is also a state that is not covered and also probably should we waited for.

I'm willing to write a patch for this if the approach of adding a loop if pending/initialized is part of the status string would be acceptable. If either is in status then sleep for 1s and try status again. If it reaches a max retries/timeout without a state changed then it fails. If either string is not part of status then continue processing as today.

**Comment by mpeters** [comment]
I've been hit by this bug several times. It's super frustrating because it's a race condition that can pop up at any time and fail on some nodes but not others. I'll probably be working on a patch in the not too distant future if nothing is fixed in the meantime.

**Comment by gaqzi** [comment]
@mpeters I have a patch prepared, I just need to get an approval to release it from my client. Will be bugging them about it this week!

**Comment by mpeters** [comment]
That would be great. Please keep bugging them and keep us informed :)

**Comment by mpeters** [comment]
Just to verify that it covers all the cases that I'm interested in, I just had this failure happen (on 1 node of 4, so seems like a race-condition):

Tried to tell monit to restart processes

`monit: name=foo state=restarted`
and received the following failure:
`{"failed": true, "status": "not monitored"}`

If I'm restarting the process then monit shouldn't care that it was previously not monitored, but should restart it and monit it, correct?

**Comment by gaqzi** [comment]
@mpeters hm, I don't think I've seen that particular state before. Was monit monitoring before you started the run?

Either way I've made a PR now and if you could please try it out in your environment as well to see if it covers all the use cases that would be awesome :)

**Comment by mpeters** [comment]
@gaqzi While I can't prove a negative (and race conditions are such negatives), this is working for me. Using your module I haven't experienced a single failure that I used to. And without it I still see random failures.

I do have two comments though, on a possible improvements/extensions of your work:
1. When `state="reloaded"` the module issues a reload command to monit, but then doesn't stick around looking at the status to make sure name given is present. Should it?
2. I've seen cases where status() sometimes will return an empty string even though I know the process is present. This happens after a reload. I'm wondering if fixing the above will fix this, or if perhaps `monit summary` is returning something weird sometimes right after a reload.

But if you think they are separate issues and should be different patches/PRs, then I'm ok with that.

**Comment by gaqzi** [comment]
@mpeters thanks for testing :D

I hadn't thought about reloaded at all and I agree that it should be handled. I'll have a look at this and try and make a patch that goes together with the current commits!

**Comment by gaqzi** [comment]
@mpeters I've added a commit for this, although it's currently completely theoretical as I don't have a playbook that uses monit available at home and I haven't used reloaded on a service at all. 

I'll try it out when I get into the office, but in hope that you could do some trial runs and see if it seems to be working I pushed it anyway. :)

As you say, it's hard to prove a negative, and with that in mind I guess the best we can do is just run it for a couple of days and see. I'll add some reloaded into our playbook and see that it continues to work as if it wasn't there with the patched version.

Commit [83f1ac6](https://github.com/gaqzi/ansible-modules-extras/commit/83f1ac60b37701f6f40fb8d01f7109ab845ec1ab).

**Comment by mpeters** [comment]
@gaqzi This is looking good, except for my comment about "unmonitor pending" in the PR.

**Comment by robynbergeron** [comment]
@gaqzi : I'm guessing this is now resolved with #806 -- I'm going to go ahead and close this issue. If it's not, let me know and we can reopen it. Thanks!

**Comment by mpeters** [comment]
Yes, I think #806 takes care of this.
