### ISSUE TITLE
Add 'force' option to redhat_subscription register options.

### ISSUE THREAD

**Issue by alikins** [ansible/ansible-modules-extras#2448]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

packaging/os/redhat_subscription
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel f9007d2d6d) last updated 2016/06/17 12:16:51 (GMT -400)
  lib/ansible/modules/core: (detached HEAD f0f5272f90) last updated 2016/06/17 12:17:09 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 6cb6829384) last updated 2016/06/17 12:17:09 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides


```
##### OS / ENVIRONMENT

RHEL
##### SUMMARY

Add 'force' option to redhat_subscriptions register ala 'subscription-manager register --force'

(moved from original https://github.com/ansible/ansible/issues/16343 submitted by @huiser)

**Comment by jctanner** [comment]
This is covered by https://github.com/ansible/ansible-modules-core/pull/3976, correct?
