### ISSUE TITLE
Chocolatey 0.9.10 and exit codes - win_chocolatey is now reporting successful package installs as failures

### ISSUE THREAD

**Issue by ferventcoder** [ansible/ansible-modules-extras#2451]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_chocolatey 
##### ANSIBLE VERSION

Any current
##### OS / ENVIRONMENT

Windows 
##### SUMMARY

Related to #19, but better context.

I mentioned this before in April - https://github.com/chocolatey/choco/issues/512. 0.9.10 just released today and folks are going to start reporting breakages even though we noted it in our release notes and tried to give plenty of notice to folks that it was coming (2 months notice in this case).

Here is the relevant portion of the [ChangeLog](https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0910-june-17-2016) (under breaking changes):

> - Exit with the same exit code as the software being installed - see [#512](https://github.com/chocolatey/choco/issues/512)
> 
> There are more exit codes from Chocolatey now that indicate success -`0`, `1605`, `1614`, `1641`, and `3010`. You may need to adjust anything you were using that would only check for 0 and nonzero.
> If you need the previous behavior, be sure to disable the feature `usePackageExitCodes` or use the `--ignore-package-exit-codes` switch in your choco commands.
##### STEPS TO REPRODUCE

Install Chocolatey 0.9.10 and then try to install a package that would indicate a reboot (3010 exit code).
##### EXPECTED RESULTS

Report success
##### ACTUAL RESULTS

This will need to be verified by someone to ensure it does error.

**Comment by ferventcoder** [comment]
cc @elventear @trondhindenes @nitzmahone

**Comment by nitzmahone** [comment]
@ferventcoder Thanks for the heads up!

**Comment by ferventcoder** [comment]
@nitzmahone I gave @elventear a heads up back in April. I guess I didn't realize at the time who all I needed to provide the notice to. 👍

**Comment by nitzmahone** [comment]
Too bad we _just_ shipped 2.1.1 RC1 about an hour ago - I coulda had this in. :)

**Comment by nitzmahone** [comment]
Fixed in https://github.com/ansible/ansible-modules-extras/commit/5cd3e328f3d5459d39a6f88bd331f362dca96d5f, cherry-picked to stable-2.1 (should appear in 2.1.1RC2). Will also add support for new reboot_required return arg in devel (target 2.2). 

Thanks!
