### ISSUE TITLE
win_ping fails: ssl Connection aborted error104

### ISSUE THREAD

**Issue by sparkvilla** [ansible/ansible-modules-extras#2468]
##### ISSUE TYPE
- Bug Report
  ##### COMPONENT NAME
  win_ping
##### ANSIBLE VERSION

```
ansible 2.1.0.0

```
##### CONFIGURATION

```
ansible.cfg:
[defaults] 
hostfile = ./hosts
log_path = ./ansible.log

group_vars/win_clones.yml
ansible_user: user
ansible_port: 5986
ansible_connection: winrm
ansible_password: pass
# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

hosts:
[win_clones]
cl1 ansible_host=172.20.100.44
cl2 ansible_host=172.20.100.46
```
##### OS / ENVIRONMENT

Ansible is managed from ubuntu 15.10 server
Target machine is a windows10 client
##### SUMMARY

To ensure the remote connection with windows client machine:

Set-execution policy Unrestricted
Run the latests version (1.3) of ConfigureRemotingForAnsible.ps1
Note: When I run the script I get no output. I just get the prompt back. Isn't suppose to create SSL certificate?

I then tried to ping the windows client:

```
ansible win_clones -m win_ping -vvv
```
##### ACTUAL RESULTS

```
Using /home/diego/gitlab_repo/ansible-software-deployment/ansible.cfg as config file
<172.20.100.44> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO     172.20.100.44
<172.20.100.46> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO 172.20.100.46
cl1 | UNREACHABLE! => {
"changed": false, 
"msg": "ssl: ('Connection aborted.', error(104, 'Connection reset by peer'))", 
"unreachable": true
}
cl2 | UNREACHABLE! => {
"changed": false, 
"msg": "ssl: ('Connection aborted.', error(104, 'Connection reset by peer'))", 
"unreachable": true
}
```

Any help please?

**Comment by jhawkesworth** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
