### ISSUE TITLE
zypper module get_package_state() don't work for type=pattern

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-extras#2496]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

zypper module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

openSUSE 42.1
##### SUMMARY

When using zypper module with type=pattern the module always return { "changed": true }. The reason is the package name is not found in installed_state returned by get_package_state() which looks just for installed RPM packages via rpm --query. Pattern is in fact meta-package with actual RPM name e.g. patterns-openSUSE-base instead of just base. List of installed patterns can be obtained via zypper patterns --installed.
##### STEPS TO REPRODUCE

Just repeatedly run this task against any openSUSE host.

```
zypper: name=base state=present type=pattern
```
##### EXPECTED RESULTS

For the first time or when the pattern is not installed the module should report { "changed": true }. Otherwise is should return { "changed": false }
##### ACTUAL RESULTS

Module always reports { "changed": true } because the module always execute zypper install command.

**Comment by alxgu** [comment]
Please test it with the devel(`2.2`) version of zypper. It isn't based on rpm queries anymore

**Comment by ghost** [comment]
You are right. With devel(2.2) it works as it should.
