### ISSUE TITLE
patch module is requiring both src and dest

### ISSUE THREAD

**Issue by sanchom** [ansible/ansible-modules-extras#258]
`runner/action_plugins/patch.py` requires both `src` and `dest`, but `modules/extras/files/patch.py` declares `dest` as not required.

**Comment by jirutka** [comment]
One of the `dest`, or `basedir` must be provided. It’s described in documentation [here](https://github.com/ansible/ansible-modules-extras/blob/9ea179697d4b88daf25634488a8cbaedb80d8bc0/files/patch.py#L34).
