### ISSUE TITLE
Ability to change state of node in F5

### ISSUE THREAD

**Issue by perzizzle** [ansible/ansible-modules-extras#276]
Issue Type:

Feature Idea

Ansible Version:

ansible 1.8.2

Environment:

RHEL 6.5

Summary:

As part of the bigip_node module I would like the ability to set the state of a node. This would accomplish the equivalent of going to Local Traffic>Nodes>$nodeName>State=enabled|disabled|forced offline from the web interface.

Steps To Reproduce:

Not applicable

Expected Results:

Not applicable

Actual Results:

Not applicable

**Comment by mhite** [comment]
I should be able to implement this for you. (I'm the original author of the module.) Stay tuned.

**Comment by msabramo** [comment]
:+1:  We want this too and willing to help.

**Comment by mhite** [comment]
I have implemented session and monitor state enable/disable functionality into both the node and pool_member module. Please see the following pull requests:

https://github.com/ansible/ansible-modules-extras/pull/282
https://github.com/ansible/ansible-modules-extras/pull/288

(UPDATE: Fixed "pool" vs. "pool_member" typo in comment.)

**Comment by msabramo** [comment]
Sorry, I'm kind of a newbie to F5 stuff. What is the difference between the two PRs? Which one do I need to disable a node temporarily from a pool? This sounds to me like it could be either the **node** change or the **pool** change.

**Comment by mhite** [comment]
Imagine a node is a member of 3 pools. If you change the status on the node, it will impact their status in all three pools. 

Alternatively, if you wanted to only impact a node's status in 1 out of 3 pools, you should not modify the attributes using the node module. Rather, use the pool_member module. (I mistakenly said "pool" rather than "pool_member" module previously.)

Does that clarify?

**Comment by msabramo** [comment]
@mhite: Yes, very helpful, thank you!

**Comment by mhite** [comment]
If you can, please test the two pull requests so we can get these merged and closed.

**Comment by robynbergeron** [comment]
@perzizzle: Thanks for submitting this feature idea. Much appreciated! And thanks to @msabramo for weighing in, and to @mhite for being the kind maintainer of this module for implementing these features, which have now been merged and should be available for you to use. :)

(Sorry it took us a while to triage this issue, but glad that it got resolved in the interim!)
