### ISSUE TITLE
vmware_guest.py testing offer 

### ISSUE THREAD

**Issue by ikkaro** [ansible/ansible-modules-extras#2889]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

vmware_guest.py
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I've available a decent vmware environment where I can help troubleshooting the current module.
If you want, contact me privately to see how can work together. I see that this module is relatively new and needs some testing and improvements.
##### STEPS TO REPRODUCE

N/A
##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

**Comment by jctanner** [comment]
@ikkaro reporting any bugs you find would be a great help. Exposure so far has been limited and I welcome any and all feedback on what to improve.

**Comment by jctanner** [comment]
@ikkaro I reached out over email, so let's continue this conversation there.
