### ISSUE TITLE
crypttab module isnt recognised by ansible

### ISSUE THREAD

**Issue by erindru** [ansible/ansible-modules-extras#304]
Hello,

I am using Ansible 1.8.4 and trying to use the crypttab module as [explained here](http://docs.ansible.com/crypttab_module.html). I have a task in my playbook like so:

``` yml
    - name: add to crypttab
      crypttab: name={{ project_name }} password={{ storage_file_password }} state=present
      sudo: true
```

However, trying to run the playbook results in:

```
[erin@laptop m2t]$ vagrant provision backend-1
==> backend-1: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/src/m2t/.vagrant/machines/backend-1/virtualbox/private_key --user=vagrant --connection=ssh --limit='backend-1' --inventory-file=/src/m2t/.vagrant/provisioners/ansible/inventory backend.yml
ERROR: crypttab is not a legal parameter in an Ansible task or handler
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I believe that ansible-modules-extras are included in the core ansible distribution. What am I doing wrong?

Thanks,
Erin

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

It seems you don't have a full ansible installation, core and extra modules should be installed when using any of the official installation methods.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
