### ISSUE TITLE
Update the README with installation instructions

### ISSUE THREAD

**Issue by bartfeenstra** [ansible/ansible-modules-extras#305]
There is currently no mention in the README on how to install/configure/use these modules.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

The modules should be installed by default when installing ansible as documented, there is nothing to configure and installing the modules independently does not make much sense.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bartfeenstra** [comment]
I had a typo in my playbook, which made me think a module wasn't installed and made me end up here looking for instructions.

Thanks for the answer. Maybe adding "The modules should be installed by default when installing ansible as documented" to the README will helpful to people in the future.

**Comment by bcoca** [comment]
done

**Comment by bartfeenstra** [comment]
That's quick, and a very clear message too :)
