### ISSUE TITLE
composer: command=dump-autoload fails because it doesn't recognize the --no-progress option

### ISSUE THREAD

**Issue by zsoldosp** [ansible/ansible-modules-extras#323]
## repro

If the following two tasks are executed after each other

```
 - composer: command=update working_dir={{ your_php_app_dir }} 
# assuming {{ your_php_app_dir }} has a valid composer.json
 - composer: command=dump-autoloads working_dir={{ your_php_app_dir }}
```

The second one fails with the following error:

```
failed: [localhost] => {"failed": true}
msg: [RuntimeException] The "--no-progress" option does not exist. dump-autoload [-o|--optimize] [--no-dev]
```
## guess at the root cause

always appended default options. As per http://docs.ansible.com/composer_module.html

> Default options that are always appended in each execution are –no-ansi, –no-progress, and –no-interaction
## Versions, environment
- Composer version 1.0-dev (829199c0530ea131262c804924f921447c71d4e8) 2015-03-16 13:11:02
- ansible 1.8.4
- ubuntu/trusty64

**Comment by abondis** [comment]
got this issue too, some composer commands don't support --no-progress, ie: 'clear-cache' or 'info'
