### ISSUE TITLE
copy target does not work on windows guests

### ISSUE THREAD

**Issue by retrogradeorbit** [ansible/ansible-modules-extras#333]
Using the latest development checkout version of ansible, using a 'copy' method to a windows target fails with:

task yaml looks like:

```
- name: copy over deployment key
  copy: src="id_preview_image"
        dest="c:\Users\Administrator\.ssh\id_rsa"
```

Verbose error is:

```
TASK: [templatepreview | copy over deployment key] **************************** 
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5985 TO 127.0.0.1
<127.0.0.1> WINRM REUSE EXISTING CONNECTION: vagrant:********@127.0.0.1:5985
<127.0.0.1> EXEC If (Test-Path -PathType Leaf "c:\Users\Administrator\.ssh\id_rsa") { $sp = new-object -TypeName System.Security.Cryptography.SHA1CryptoServiceProvider; $fp = [System.IO.File]::Open("c:\Users\Administrator\.ssh\id_rsa", [System.IO.Filemode]::Open, [System.IO.FileAccess]::Read); [System.BitConverter]::ToString($sp.ComputeHash($fp)).Replace("-", "").ToLower(); $fp.Dispose(); } ElseIf (Test-Path -PathType Container "c:\Users\Administrator\.ssh\id_rsa") { Write-Host "3"; } Else { Write-Host "1"; }
<127.0.0.1> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'SQBmA...QAiADsACgB9AA==']
<127.0.0.1> WINRM RESULT <Response code 0, out "1 ", err "">
<127.0.0.1> EXEC (New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1427085818.0-23596017243820").FullName | Write-Host -Separator '';
<127.0.0.1> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'KABO...OwA=']
<127.0.0.1> WINRM RESULT <Response code 0, out "C:\Users\Administrat", err "">
<127.0.0.1> PUT /home/crispin/dev/newdev/signiq8-deploy/provisioning/roles/templatepreview/files/id_preview_image TO C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1427085818.0-23596017243820\source
<127.0.0.1> WINRM PUT /home/crispin/dev/newdev/signiq8-deploy/provisioning/roles/templatepreview/files/id_preview_image to C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1427085818.0-23596017243820\source (offset=0 size=1679)
fatal: [windows] => module copy not found in configured module paths.  Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.

FATAL: all hosts have already failed -- aborting
```

Ansible is 1.9.0-0.2rc2

~/ansible$ git describe
v1.9.0-0.2.rc2
~/ansible$ git rev-parse HEAD
5d28d46b166014a544910151bf2b18af654a1940

Submodule versions:

~/ansible$ git submodule foreach git rev-parse HEAD
Entering 'lib/ansible/modules/core'
d52e12a0aae6da4b512c8343fd1e4aaef58ca6df
Entering 'lib/ansible/modules/extras'
f86e3841d708f5cc1f21af35d3ffaf99370043fb
Entering 'v2/ansible/modules/core'
34784b7a617aa35d3b994c9f0795567afc6fb0b0
Entering 'v2/ansible/modules/extras'
46e316a20a92b5a54b982eddb301eb3d57da397e

host is ubuntu 14.04

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

In any case copy does not work with windows, there is a PR for a win_copy module that does work.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jhawkesworth** [comment]
For info, there's a windows-specific win_copy module in the works
https://github.com/ansible/ansible-modules-core/pull/384

The module hasn't yet been merged for technical reasons - for details see
the discussion here:
https://groups.google.com/forum/#!topic/ansible-devel/Jl5qP73CiKo

Jon
