### ISSUE TITLE
known_hosts module not installed with 1.8.4

### ISSUE THREAD

**Issue by timrcase** [ansible/ansible-modules-extras#336]
The known_hosts module wasn't included when installing 1.8.4 using pip.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

I don't believe this is a bug as the known_hosts module won't be released until version 1.9.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
