### ISSUE TITLE
mongodb user delete doesn't delete if authentication fails

### ISSUE THREAD

**Issue by solomongifford** [ansible/ansible-modules-extras#362]
The code below assumes that if the username and password combination fails to authenticate and the state is "absent", the user must not exist.  However, this assumption is false.  The password could potentially be incorrect in the task.  

```
try:
           client[db_name].authenticate(user, password)
           if state == 'present':
              module.exit_json(changed=False, user=user)
        except OperationFailure:
           if state == 'absent':
              module.exit_json(changed=False, user=user)
```

I will be issuing a patch to fix this.

**Comment by gregdek** [comment]
Fixed by #365.
