### ISSUE TITLE
mongodb_user's login_password with missing login_user not caught

### ISSUE THREAD

**Issue by solomongifford** [ansible/ansible-modules-extras#363]
The message in the code below around line 225 seems to indicate that if either the login_password or login_user is provided, the other must also be provided. However, the logic only tests to verify the password is given and fails to capture the scenario where the password is given without a username. 

'''
elif login_password is None and login_user is not None:
            module.fail_json(msg='when supplying login arguments, both login_user and login_password must be provided')
'''

I will be submitting merge request to fix.

**Comment by bcoca** [comment]
this pertains to what?

**Comment by solomongifford** [comment]
Updated title to specify mongodb

**Comment by gregdek** [comment]
Closed by #365.
