### ISSUE TITLE
gluster_volume should support multiple bricks

### ISSUE THREAD

**Issue by rnowling** [ansible/ansible-modules-extras#403]
Issue Type:
Feature idea

Ansible Version:
    ansible 2.0.0
    configured module search path = None

Environment:
N/A

Summary:
The `gluster_volume` module currently only supports one brick per volume. (In Gluster distributed file system terms, bricks are backing directories on the storage nodes.)  However, it is not uncommon to have multiple bricks per storage node (e.g., in cases where each brick is on a different disk.)  For example:

```
$ gluster volume create gv0 replica 2 server1:/data/brick1 server2:/data/brick1 server1:/data/brick2 server2:/data/brick2
```

will create a single volume `gv0` with two bricks, each of which is mirrored between the two servers.

I want to add support for multiple bricks.  This will require changing the `gluster_volume` API.  Possible options include:
- Modifying the `brick` keyword to take one or more bricks.
- Adding a new `bricks` keyword alongside `brick` that can take 1 or more bricks.  Deprecate `brick` going forward.

In Ansible, which are preferable:  lists of strings or string with comma-separated values?

The order of the bricks is important since Gluster uses the order to group replicas.  For now, I suggest noting this in the documentation instead of using a more advanced data structure.

Steps To Reproduce:
Just look at code.

Expected Results:
Be able to pass multiple bricks into `gluster_volume`.

Actual Results:
Assumes `brick` is a single item.

**Comment by Jmainguy** [comment]
Yeah its very common to have multiple bricks, this would be a great feature to add

**Comment by bcoca** [comment]
closing via #403

**Comment by coderlol** [comment]
Is this feature available for ansible 1.9.2-1 ?

**Comment by rnowling** [comment]
@coderlol No, it's not in 1.9.x.  It's currently only in the -devel branch on GitHub -- not in a release yet.  Please try using the [devel version](http://docs.ansible.com/ansible/intro_installation.html#running-from-source).  You can run the devel version from any directory -- no need to install system wide.  Or, you can just copy the gluster_volume.py from the devel version and place it in your current installation.

**Comment by coderlol** [comment]
Great...thx

**Comment by eventbase-web** [comment]
When will the next stable point release be? I'm using the devel branch at the moment for these commits but would prefer to be on a stable release.
