### ISSUE TITLE
IRC Module issues

### ISSUE THREAD

**Issue by AzzAToTV** [ansible/ansible-modules-extras#429]
For some reason i can't get the irc module to work. It just hangs. I ran ansible with debug -vvv, and the irc module is reporting it timed out waiting for the join event. 

The bot does join the channel, but never says anything. It must be the way it detects that it has joined.

Can anyone help me with a solution?

**Comment by sivel** [comment]
it is possible that the IRC module is not compatible with your IRC network.  It has been successfully tested with InspIRCd and ircd-seven (freenode) but has been known to fail on other networks.

**Comment by AzzAToTV** [comment]
I thought the same, but I'm running the latest InspIRCd

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Also note that while IRC has a 'standard' many of the IRC servers choose to add/remove parts making interoperability 'interesting' at the very least. 

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by offlinehoster** [comment]
Got connect issues (timeouts) on 
- Unreal3.2.6-uf-network (https://www.unrealircd.org/)
- charybdis-4-7272518  (https://github.com/charybdis-ircd/charybdis)

Why is this plugin called "irc_module" if it is only working with some special irc server?
