### ISSUE TITLE
lvg is not idempotent -- attempts to create VG that already exists

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible-modules-extras#455]
**Issue Type:** Bug Report

**Ansible Version:** 1.9.1

**Environment:** CentOS 7.1 x86_64

**Summary:** lvg module attempts to create volume group that already exists

**Steps to Reproduce:**

```
- name: Create LVM VolumeGroup
  lvg:
    vg: "something"
    state: present
    pvs: "/dev/md/something"
```

Run it twice.

**Expected Result:** lvg module would detect VG already exists and be happy that "state=present" is satisfied.

**Actual Results:** lvg module attempts to create VG and gets an error from vgcreate.

```
TASK: [lvm | Create LVM VolumeGroup] ****************************************** 
failed: [prd] => {"err": "  Can't initialize physical volume \"/dev/md/something\" of volume group \"something\" without -ff\n", "failed": true, "rc": 5}
msg: Creating physical volume '/dev/md/something' failed
```

**Comment by alxgu** [comment]
@gtirloni does https://github.com/ansible/ansible-modules-extras/pull/562 fix your issue?
So maybe that issue can be closed.

**Comment by gtirloni** [comment]
Yep, thanks!

**Comment by xelor81** [comment]
I have the very same issue here, all mentioned fixes are in place however the system still trying either to create the vg on the physical device or (when devices are not defined in the pvs array) reports that none of the physical volumes has been given.

```
[support@us000832 playbooks]$ ansible us000832 -s -m lvg -a "vg=other state=present"
us000832.eu.tieto.com | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "No physical volumes given."
}

[support@us000832 playbooks]$ ansible us000832 -v -s -m lvg -a "vg=other state=present pvs=/dev/md/something"
Using /etc/ansible/ansible.cfg as config file
us000832.eu.tieto.com | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Device /dev/md/something not found."
```
