### ISSUE TITLE
Modules not using ansible.module_utils.urls

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-modules-extras#478]
The following modules are using urllib2 directly and not using `fetch_url` as provided by `ansible.module_utils.urls`
- monitoring/librato_annotation.py
- monitoring/uptimerobot.py
- notification/campfire.py 
- notification/sendgrid.py
- notification/typetalk.py

The above should likely be modified to utilize `fetch_url` instead so that they utilize a standard interface like the other modules.

**Comment by robynbergeron** [comment]
Hi @sivel -- the following things were fixed as listed below w/accompanying PR referenced. Thanks to @abadger for doing this! :) And (again) sorry it's taken a while to address this in the issue itself.

Going to go ahead and close this out -- let us know if somehow anything has gone awry :)

librato_annotation - #733 
uptimerobot - #734 
campfire - #735 
sendgrid - #736 
typetalk: #738
