### ISSUE TITLE
Mail module fails to connect to Postfix (Connection Refused)

### ISSUE THREAD

**Issue by runar** [ansible/ansible-modules-extras#483]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
##### Environment:

OS X 10.10.3 managing Ubuntu 14.04.
##### Summary:

Attempting to send emails using the [mail](http://docs.ansible.com/mail_module.html) module results in a «Connection refused» error message. Postgres is running, and I can successfully send emails using the command line tool `mail`:

```
echo "This is the body of the email" | mail -s "This is the subject line" root
```
##### Steps To Reproduce:

https://gist.github.com/runar/fbfe0d5a2c10efe40bb5
##### Expected Results:

Email being delivered to recipient.
##### Actual Results:

```
TASK: [mail | Send test email] ************************************************
<127.0.0.1> REMOTE_MODULE mail host="localhost" subject="System lorem has been successfully provisioned." to=
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431440506.99-223437599721220 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1431440506.99-223437599721220 && echo $HOME/.ansible/tmp/ansible-tmp-1431440506.99-223437599721220']
<127.0.0.1> PUT /var/folders/rq/jd33p0q52w70wz4w44jmdq6h0000gn/T/tmpznhv5a TO /Users/runar/.ansible/tmp/ansible-tmp-1431440506.99-223437599721220/mail
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/opt/python/bin/python2.7 /Users/runar/.ansible/tmp/ansible-tmp-1431440506.99-223437599721220/mail; rm -rf /Users/runar/.ansible/tmp/ansible-tmp-1431440506.99-223437599721220/ >/dev/null 2>&1']
failed: [lorem -> 127.0.0.1] => {"failed": true, "rc": 1}
msg: Failed to send mail to server localhost on port 25: [Errno 61] Connection refused

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case the mail command does not use the smtp protocol, it just injects mail directly into the queue, check netstat and see if postfix is actually listening on port 25 on localhost (it can be running and NOT do that).

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by runar** [comment]
I would like to add that the problem was … me. I was setting up Postfix on my remote server, and attempting to send emails using my local machine. Obviously this did not work out. Thank you for pointing me in the right direction and helping me out on IRC, @bcoca!
