### ISSUE TITLE
cloudstack cs_iso module failing on get_zones

### ISSUE THREAD

**Issue by kbroughton** [ansible/ansible-modules-extras#493]
Issue Type:
Bug Report

Ansible Version:

```
 ansible --version
ansible 2.0.0 (modified-ansible-playbook d45a4fcedb) last updated 2015/05/14 16:53:36 (GMT -500)
  lib/ansible/modules/core: (devel aab13daa6a) last updated 2015/05/10 21:55:06 (GMT -500)
  lib/ansible/modules/extras: (devel 19b345932a) last updated 2015/05/10 21:57:23 (GMT -500)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/04 00:29:33 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 650d740a3a) last updated 2015/03/04 00:29:48 (GMT -500)
  configured module search path = None
```

Ansible Configuration:
merge_strategy: hash

Environment:

Summary:
OSX 10.10.3 (Yosemite)

Steps To Reproduce:

```
- name: ensure iso image exists
  local_action:
    module: cs_iso
    name: Debian 7 64-bit
    url: http://mirror.switch.ch/ftp/mirror/debian-cd/current/amd64/iso-cd/debian-7.7.0-amd64-netinst.iso
    os_type: Debian GNU/Linux 7(64-bit)
```

Expected Results:
A clean error message (not a stack trace) or successful put for the image

Actual Results:

```
TASK: [softlayer | ensure iso image exists] *********************************** 
failed: [localhost -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/kestenbroughton/.ansible/tmp/ansible-tmp-1431643484.78-88361562274071/cs_iso", line 2300, in <module>
    main()
  File "/Users/kestenbroughton/.ansible/tmp/ansible-tmp-1431643484.78-88361562274071/cs_iso", line 686, in main
    iso = acs_iso.register_iso()
  File "/Users/kestenbroughton/.ansible/tmp/ansible-tmp-1431643484.78-88361562274071/cs_iso", line 567, in register_iso
    iso = self.get_iso()
  File "/Users/kestenbroughton/.ansible/tmp/ansible-tmp-1431643484.78-88361562274071/cs_iso", line 602, in get_iso
    args['zoneid'] = self.get_zone_id()
  File "/Users/kestenbroughton/.ansible/tmp/ansible-tmp-1431643484.78-88361562274071/cs_iso", line 373, in get_zone_id
    return self.get_zone(key='id')
  File "/Users/kestenbroughton/.ansible/tmp/ansible-tmp-1431643484.78-88361562274071/cs_iso", line 381, in get_zone
    zones = self.cs.listZones()
  File "/usr/local/lib/python2.7/site-packages/cs.py", line 104, in handler
    return self._request(command, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cs.py", line 126, in _request
    data = response.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by resmo** [comment]
Hi, thanks for reporting. The error seems more related to be in the `cs` package. It seems the response is not in json format. Do other modules work? Or do you see this all over the modules? Did you check the endpoint URL is correct?

`cs` version do you use? 

```
$ pip show cs 
---
Name: cs
Version: 0.6.6
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests
```

Could you print the output of cli

```
$ cs listZones
```

Could you print the cloudstack version?

```
$ cs listCapabilities
```

**Comment by bcoca** [comment]
in any case we consider an exception to the user a bug, the module should handle and capture it and return a 'friendly' message to display.

**Comment by kbroughton** [comment]
rene, you are correct.  The problem is at the cs lib level.  Investigating still.

**Comment by resmo** [comment]
@kbroughton I need more infos to debug it. Did you use http method post? If yes, did the endpoint configured to handle it correctly?

**Comment by kbroughton** [comment]
Hi rene,

My apologies.  It is all on my end.  I am using softlayer and from some of
their blog posts, was under the impression that SL used CS under the hood.
This appears not to be the case.  I think, as brian suggested, that the
call to the cs lib should be wrapped in a try/catch and if it fails, print
a message like
"unable to connect to cloudstack endpoint %s, please check your credentials"

On Sat, May 16, 2015 at 4:51 AM, René Moser notifications@github.com
wrote:

> @kbroughton https://github.com/kbroughton I need more infos to debug
> it. Did you use http method post? If yes, did the endpoint configured to
> handle it correctly?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-extras/issues/493#issuecomment-102599122
> .

## 

kesten broughton
devops @ cognitivescale

**Comment by resmo** [comment]
Okay, no problem. Could you close the bug please? I plan to improve the error reporting in the lib `cs`, I already did some work 0f884ead4088933d2a28940e2fd7b0e7b4926fbb in the modules.
