### ISSUE TITLE
LVG module: Device xxx not found when using multiple devices

### ISSUE THREAD

**Issue by filipenf** [ansible/ansible-modules-extras#50]
I'm getting the error: `Device /dev/xvdb /dev/xvdc not found` when using multiple devices. It appears to be a list being treated as a string separated by spaces. The problem appears to be in this line: https://github.com/ansible/ansible-modules-extras/blob/devel/system/lvg.py#L145

**Comment by filipenf** [comment]
The problem isn't where I previously suggested but on line 190. I fixed it in this PR: https://github.com/ansible/ansible-modules-extras/pull/56

**Comment by bcoca** [comment]
closing this as we can keep track through the PR
