### ISSUE TITLE
Modules missing GPL header

### ISSUE THREAD

**Issue by resmo** [ansible/ansible-modules-extras#508]
```
find -name '*.py' -not -name '__*.py' -type f -exec grep -rL 'GNU General Public License' {} \;
```

```
./monitoring/bigpanda.py
./monitoring/datadog_event.py
./monitoring/pagerduty.py
./monitoring/pingdom.py
./monitoring/stackdriver.py
./monitoring/circonus_annotation.py
./monitoring/uptimerobot.py
./database/postgresql/postgresql_lang.py
./system/locale_gen.py
./system/svc.py
./notification/campfire.py
./notification/typetalk.py
./notification/hipchat.py
./notification/jabber.py
./notification/grove.py
```

**Comment by bcoca** [comment]
I wrote both svc and jabber, took care of those via 307424c69419a57d7be50b2a85fb109293f5d91f

**Comment by bcoca** [comment]
remaining authors:

```
monitoring/bigpanda.py : BigPanda
monitoring/datadog_event.py : Artūras 'arturaz' Šlajus <x11@arturaz.net>
monitoring/pagerduty.py : Justin Johns
monitoring/pingdom.py : Justin Johns
monitoring/stackdriver.py : Ben Whaley
monitoring/circonus_annotation.py : "Nick Harring (@NickatEpic)"
monitoring/uptimerobot.py : Nate Kingsley
database/postgresql/postgresql_lang.py : Jens Depuydt
system/locale_gen.py : "Augustus Kling (@AugustusKling)"
notification/campfire.py : Adam Garside <adam.garside@gmail.com>
notification/typetalk.py : Takashi Someda <someda@isenshi.com>
notification/hipchat.py : WAKAYAMA Shirou
```

**Comment by gregdek** [comment]
If we can't get these knocked down, we should probably make individual tickets out of each of these.

If we can't get this resolved, do we pull the modules?

**Comment by hlieberman** [comment]
Some of these are more concerning than others.  The postgresql_lang module, for example, explicitly states its copyright, so it can't considered to be licensed as all the others that are merely missing it.  This has blocked Ansible 1.9.1 from Debian for the last couple of months, and I am now uploading a copy with it removed.

**Comment by bcoca** [comment]
cc @zimbatm, can you add GPLv3 header to the groove module?

**Comment by bcoca** [comment]
@brian-brazil can you add GPLv3 header to dpkg_selections module?

**Comment by bcoca** [comment]
cc @rickmendes can you add gpl header to ec2_win_password

**Comment by ghost** [comment]
@bcoca Added here https://github.com/ansible/ansible-modules-extras/pull/1056

**Comment by brian-brazil** [comment]
I'm okay with GPLv3 or later for dpkg_selections.

**Comment by zimbatm** [comment]
I'm ok with GPLv3 as well

**Comment by bcoca** [comment]
closing via fcb143e0f9b83a7839cf7388f5b49164fa78b2cd
