### ISSUE TITLE
Module missing GPL version

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible-modules-extras#509]
##### Issue Type:

Bug Report
##### Ansible Version:

git master
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

cloud/misc/virt.py does not specify GPL version.  If the intention is to apply any GPL license to it, that's OK, but it should be specified as "version 1 or, at your option, any later version".  I would be shocked if that's the actual licensing terms that Red Hat signed off on, though.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by abadger** [comment]
So... Looking back through git history, that's the license header that we received with the code when we accepted the module.  We're okay with an ansible module being GPL any version (we'd prefer GPLv3+ but don't have a problem with an unspecified GPL version in a module) so it's not really a problem.

If you know that the code should be licensed under a more specific version than that I'll be happy to update the header to reflect the reality but until then I think I have to defer to the sumitter of the code knowing what license to apply to it.

**Comment by abadger** [comment]
I'll close this in a few days if there's no further information about whether a more specific license version is documented somewhere.

**Comment by hlieberman** [comment]
It's not a problem for me; GPL-1+ is DFSG free, so I don't really mind. It's just very unusual, so I wanted to reach out in case it was a mistake.

**Comment by abadger** [comment]
<nod>  Thanks.  Since it's the license we received the code under I think we'll keep it unless someone reaches out to us to say that it's a mistake and the license header should be updated.
