### ISSUE TITLE
GPL Incompatibility

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible-modules-extras#515]
##### Issue Type:

Bug Report
##### Ansible Version:

git master
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

The module extras/monitoring/nagios.py is licensed under GPL v2 exclusively, rather than GPL v2 or any later version.  As a result, it is not compatible with Ansible itself which is licensed under the GPL v3.

The module should be either re-licensed or removed.

**Comment by wenottingham** [comment]
cc @tbielawa

**Comment by timlnx** [comment]
Hmmm. Uh-oh.

Submitted PR w/ fix.

**Comment by tgerla** [comment]
This is not a GPL violation at all--the module code that the modules import is BSD-licensed for this exact reason, and the modules themselves never link to any Ansible GPLv3 code.

**Comment by hlieberman** [comment]
It is my understanding that it would end up making the play files that clients make be a violation, as they would cause the link to happen.  Am I incorrect in that?

**Comment by abadger** [comment]
IANAL so I can't speak to that aspect but on the technical side there's no link happening to GPLv3 code.  The module is combined with code in module_utils.  All of the module_utils code should be BSD licensed.  That combination is then sent over the wire by ansible and run on the remote machine as a separate process.

**Comment by tgerla** [comment]
Playbooks don't link to Ansible either--they are loaded and parsed by Ansible, but there is no linking happening.

**Comment by hlieberman** [comment]
@abadger, for what it's worth, lib/ansible/module_utils/splitter.py is GPL-3+, not BSD.

Either way, this is resolved -- thanks!

**Comment by abadger** [comment]
@hlieberman Thanks for mentioning that. I'll ping @jimi-c about fixing it... We had talked about fixing it earlier (discovered it when v2 was branched off)  but it must have slipped from his radar.
