### ISSUE TITLE
Possible Proprietary Module Distributed

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible-modules-extras#516]
##### Issue Type:

Bug Report
##### Ansible Version:

git master
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

The module extras/database/postgresql/postgresql_lang.py has a copyright header, but has no licensing information.  As a result, it must be assumed to be proprietary -- and cannot be distributed with a GPLv3 package.

The license should be clarified or it should be removed.

**Comment by wenottingham** [comment]
cc @jensdepuydt

**Comment by bcoca** [comment]
closing as duplicate of #508
