### ISSUE TITLE
haproxy feat.req: check status of a backend. If its not the expected state, fail the task.

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible-modules-extras#528]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.9.1
##### Ansible Configuration:

default
##### Environment:

Debian 7 64bit
##### Summary:

I have a need for a feature where I can check if the backend is active after I enable it. 
My use case is rolling updates, where I use the module to disable a backend, do the upgrade and enable it. Then I move on.

But I have no check to actually check if the backend I updated and enabled goes up ok, I just enable it and expect it to work and become active in haproxy
##### Expected Results:

If I use this feature the play will end with failed status if the updated server doesnt come up ok as a backend in haproxy, which will result that my env will contiune to use the other backend and my service will continue tor work. (if no check ansible will iterate over all backends and essentially take the service offline)

```
haproxy: host=backend1 expected_status=active
```

**Comment by kiranos** [comment]
I got this behaviour through the shell module (its not very nice,) but might give someone a tip and also how to gather the info from the ansible socket.

If you enable through:

```
 - name: enable core-api backend on haproxy
   haproxy: state=enabled host="{{ ansible_hostname }}_www1" backend="backends" socket=/run/haproxy/admin.sock

```

You can use this to verify its UP state.

```
 - name: check status after enabling backend
   shell: /bin/echo "show stat" |/usr/bin/socat /var/run/haproxy/admin.sock stdio |/bin/grep backends |/bin/grep {{ ansible_hostname }}_www1 |awk -F ',' '{print $18}'
   register: backend_status
   failed_when: backend_status.stdout.find('UP') == -1
```

**Comment by ggermis** [comment]
I added a pull request for this: https://github.com/ansible/ansible-modules-extras/pull/622. Usage:

```
- name: enable some-service
  haproxy: state=enabled host="{{ ansible_hostname }}" backend="some-service" wait=yes
```

Extra options added:
- wait - wait for service to reach 'UP' status on state=enabled and 'MAINT' status on state=disabled
- wait_retries - how many times to check for status
- wait_interval - how long between checks

**Comment by robynbergeron** [comment]
Hi @kiranos -- thanks for your feature idea. Sorry it took us a while to get it triaged.  :)

It looks like @ggermis's PR, #622, has been merged (thanks for that work, @ggermis!) -- so I'm going to close this out.
