### ISSUE TITLE
lvol attribute error

### ISSUE THREAD

**Issue by sean-abbott** [ansible/ansible-modules-extras#538]
When attempting to use lvol with ansible 1.9.1, I get an AttributeError.

```
  sample play:
  - name: shrink /u0
    sudo: yes
    sudo_user: root
    lvol: vg=ubuntu-vg
          lv=u0
          size=2G
          force=yes
    notify: start jenkins
```

results in this error:
failed: [build] => {"failed": true, "parsed": false}
BECOME-SUCCESS-cnvmkzuaevlhozekezstizuukgdnsjky
OpenSSH_5.9p1 Debian-5ubuntu1.4, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /home/name/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
  File "<stdin>", line 1838, in <module>
  File "<stdin>", line 220, in main
AttributeError: 'str' object has no attribute 'append'

**Comment by sean-abbott** [comment]
So, I modified lvol at line 220 as follows:

```
            elif size < this_lv['size']:
                if not force:
                    module.fail_json(msg="Sorry, no shrinking of %s without force=yes." % (this_lv['name']))
                tool = module.get_bin_path("lvextend", required=True)
                tool += " --force"
```

Which now returns the error:  

 New size given (512 extents) not larger than existing size (3154 extents)\n  Run `lvextend --help' for more information.\n", "failed": true, "rc": 3}
msg: Unable to resize u0 to 2g

Which of course led me to ask...why are we trying to use lvextend to reduce the volume size?

So I changed that to 

```
            elif size < this_lv['size']:
                if not force:
                    module.fail_json(msg="Sorry, no shrinking of %s without force=yes." % (this_lv['name']))
                tool = module.get_bin_path("lvreduce", required=True)
                tool += " --force"
```

and now it works.

So I guess I'll start working on a PR to that effect, unless I'm missing something.

**Comment by bcoca** [comment]
looks correct, it seems that the shrinking is not the normal use case, thanks for catching and debugging this

**Comment by sean-abbott** [comment]
it's already fixed in devel 

```
                tool = module.get_bin_path("lvreduce", required=True)
                tool = '%s %s' % (tool, '--force')
```

So unless there's a way to backport it to 1.9, then probably nothing more to see here.

**Comment by bcoca** [comment]
we are about to release a 1.9 bugfix minor release, the fix seems to be there already, so closing this ticket
