### ISSUE TITLE
win_chocolatey module could use install args

### ISSUE THREAD

**Issue by legleux** [ansible/ansible-modules-extras#540]
There are a few packages I would like to use directly with win_chocolatey but I need to customize the install. 
Is there a way to provide arguments to the choco command in win_chocolatey or do I just have to use "script" and call choco manually?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
