### ISSUE TITLE
zypper feature request: name=* state=latest

### ISSUE THREAD

**Issue by lndevnull** [ansible/ansible-modules-extras#546]
To replicate the yum module functionality please allow for updating all packages.  Arguments to replicate this functionality would be "name=\* state=latest".   The command result would be "zypper update"

**Comment by robynbergeron** [comment]
Hi @lndevnull: Thanks for submitting this feature idea. Sorry it's taken us a while to get around to triaging it. :)

@dirtyharrycallahan & @alxgu -- Pinging you to bring this feature request for your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by robynbergeron** [comment]
[module: packaging/os/zypper.py]

**Comment by andytom** [comment]
I have opened up a pull request that implements this feature. If you have any comments/suggestions please let me know.

**Comment by andytom** [comment]
I believe that PR is ready to be merged. What is the process for getting it merged?

**Comment by dirtyharrycallahan** [comment]
I am glad SuSE is getting some attention but unable to contribute due to corporate policy and internet connection. Please remove me as author or however this is tied to me.

**Comment by blutgens** [comment]
any  update on this? is there any chance we'll get this feature? I'd also like to see some analog to "zypper patch", and 'zypper ref'
