### ISSUE TITLE
npm: install package from repo

### ISSUE THREAD

**Issue by kharandziuk** [ansible/ansible-modules-extras#615]
Is it possible to install something from github repo with npm module.
I tried to do something like this:

```
    - name: install app
      npm: name="git+ssh://git@github.com:kharandziuk/deploy-node-starter#silly-sample" global=true
```

But the task never finishes or runs to long

**Comment by kharandziuk** [comment]
I looked at source and it looks like there is no way to do that. Can I create the PR with this feature?
If so, should I use `name` parameter or add the other one(e.g.: `from-git`)?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by kharandziuk** [comment]
@bcoca Did you ever read a question?

**Comment by bcoca** [comment]
yes, which is why i added mailing list: https://groups.google.com/forum/#!forum/ansible-devel

**Comment by kharandziuk** [comment]
@bcoca Please, look at my comment below the question. Isn't it about PR?

**Comment by gregdek** [comment]
@kharandziuk you are always free to submit a PR, and we will ask the module owner to review it. It's good to send a note to the ansible-devel list to find out if people agree.

**Comment by kharandziuk** [comment]
@gregdek What is the reason to create useless PRs? Maybe it make sense to ask before? I sent a note  to ansible-devel. But I believe the Issue Tracker is a right place feature requests and PR propositions.

**Comment by gregdek** [comment]
Fair point. We're still sorting through our ideal workflow.

I think the right answer is: 
- Find the person who wrote the module you want to edit; their Github ID should be in the "author:" field in the module.
- Mention them in the issue and ask their opinion here.
- File a PR or not, depending on their response.

**Comment by kharandziuk** [comment]
thanks @gregdek.
So @chrishoffman I need you:)
The question is:
with npm I can do something like this `npm install -g https://github.com/kharandziuk/node-starter-deploy.git\#silly-sample`. Can I achieve the same behavior with ansible npm module?(I guess no)
I tried to run a task like:

```
- name: install app
  npm: name="npm install -g https://github.com/kharandziuk/node-starter-deploy.git#silly-sample" global=true
```

but it runs forever. Can I create a PR with this feature? Or if there a way to do that can I add the example to docstring?

**Comment by cemulate** [comment]
@kharandziuk Did any discussion ever happen about this on a different thread or anything? I'm also interested in this feature.
