### ISSUE TITLE
alternatives should allow link priorty as an optional parameter

### ISSUE THREAD

**Issue by zlalanne** [ansible/ansible-modules-extras#632]
**Issue Type:**  “Feature Idea”
**Ansible Version:** 1.9.1
**Ansible Configuration:** Stock configuration
**Environment:** Ubuntu 14.04 x64 managing an Ubuntu 14.04 x64 machine

**Summary:** The alternatives module should allow you to pass in the link priority as an optional parameter. Currently the link priority is hard coded in the module as highlighted below:

https://github.com/ansible/ansible-modules-extras/blob/devel/system/alternatives.py#L61

Ansible should only report a change when the priority and link stayed the same.

**Steps To Reproduce:** None, feature idea

**Comment by gregdek** [comment]
cc: @DavidWittman @mulby

**Comment by robynbergeron** [comment]
[module: system/alternatives.py]

**Comment by robynbergeron** [comment]
Hi @zlalanne -- Thanks for submitting this feature idea. It looks like @gregdek did some pinging back in June -- he and I are currently going through and triaging outstanding issues in extras, so I'm just going to put some extra context in here for anyone who may see this in the future, and to re-ping the module owners just in case they have a moment of inspiration :)

@DavidWittman & @mulby -- Pinging you to bring this feature request for your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.
