### ISSUE TITLE
locale_gen fails on Ubuntu fresh install

### ISSUE THREAD

**Issue by xals** [ansible/ansible-modules-extras#656]
I installed an Ubuntu Trusty on a server (actually used debootstrat on a Ganeti KVM instance, not sure if this information is releavant). I installed locales package too.

The file /var/lib/locales/supported.d/local does not exist and the plugin is not able to determine that we are on Ubuntu system. I think the best way to determine th file to edit is:
- pass it as a paremeter of locale_gen module
- OR use /etc/lsb-release file
- OR use ansible_distribution variable

**Comment by mscherer** [comment]
Can you explain a bit more ? 
For example, how can it be reproduce, what do you see and what you would want to see ?

**Comment by mscherer** [comment]
Ok, so answering to myself ( after some coffee ), the more interesting question is "where does your kvm image come from", as I am not sure we should work around "breakage" from random hosters. But if the breakage is on the official cloud image, we could just switch on adding the file if it is missing.

**Comment by mgedmin** [comment]
This affects Ansible 1.9.4 too.  Do you plan to backport the fix for 1.9.5?
