### ISSUE TITLE
gluster_volume couldn't probe peer

### ISSUE THREAD

**Issue by d3vil-st** [ansible/ansible-modules-extras#659]
I use ansible version 1.9.2 from ppa:ansible/ansible and gluster version 3.6.3.
So, when i create task like this:

``` yml
- name: create gluster volume
  gluster_volume: state=present name=repl1 brick=/mnt/gluster_bricks/repl1 rebalance=yes replicas=2 cluster="{{ groups['gluster']|join(',') }}"
  run_once: true
```

When this task runs, I get error:

```
TASK: [gluster | create gluster volume] ***************************************
<192.168.7.89> ESTABLISH CONNECTION FOR USER: root
<192.168.7.89> REMOTE_MODULE gluster_volume state=present name=repl1 brick=/mnt/gluster_bricks/repl1 rebalance=yes replicas=2 cluster=192.168.7.89,192.168.7.84
<192.168.7.89> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.7.89 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1435586293.82-83471934034045 && echo $HOME/.ansible/tmp/ansible-tmp-1435586293.82-83471934034045'
<192.168.7.89> PUT /tmp/tmpfTQiQg TO /root/.ansible/tmp/ansible-tmp-1435586293.82-83471934034045/gluster_volume
<192.168.7.89> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.7.89 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1435586293.82-83471934034045/gluster_volume; rm -rf /root/.ansible/tmp/ansible-tmp-1435586293.82-83471934034045/ >/dev/null 2>&1'
failed: [192.168.7.89] => {"failed": true}
msg: failed to probe peer 192.168.7.89

FATAL: all hosts have already failed -- aborting
```

My inventory is:

```
[gluster]
192.168.7.89
192.168.7.84
```

**Comment by abuzze** [comment]
The peer probing "fails" if the hosts probes it's own IP. I used the host parameter and delegate_to to get around this problem. But it would be easier, if the peer probing would just ignore the localhost error message from gluster.

This worked for me:
`gluster_volume: state=present name=repl1 brick=/mnt/gluster_bricks/repl1 
 replicas=2 cluster="{{ groups['gluster']|join(',') }}" host=192.168.7.89
deletegate_to: 192.168.7.89`

**Comment by bcoca** [comment]
or this might work `"{{ (groups['gluster']|difference([inventory_hostname]))|join(',') }}"`

**Comment by bcoca** [comment]
so i was thinking of ways to make gluster module not probe itself, but this is something the user should just avoid by not adding that ip to the module option. Closing this ticket as the module is not really doing anything wrong, it is just being given information that will make gluster fail.

**Comment by nadley** [comment]
As I'm also encountering this situation, trying to make gluster volume replicated with two bricks, if I apply this suggestion https://github.com/ansible/ansible-modules-extras/issues/659#issuecomment-120559263 I got a volume but set to be distributed. I specify a replica in the module arguments then I have to specify all bricks, I can't have less brick than my number of replica. As I only have two node like describe on the initial bug report, if I specify both in cluster argument it failed as it is impossible to had himself to prob. So we need to think about a solution...

**Comment by coderlol** [comment]
I think the module should be improved to not have a host in the cluster probing itself.
All hosts in the specified cluster should probe all other hosts.

It's convenient to just specify all hosts in a cluster in one go.  It would be nice if the module was smart enough to do proper "cluster" propbing.

It's sufficient to have one host hode probing all other nodes.  However, gluster peer status provides hostnames, in addition to IPs, of other nodes if the nodes mutually probe each other.

**Comment by jeinwag** [comment]
I'm currently having the same issue as https://github.com/ansible/ansible-modules-extras/issues/659#issuecomment-120976117. I'm unable to use the ansible module to create a replicated volume.

**Comment by sklaus** [comment]
@bcoca :
I think you are wrong here.
To create a replicated volume, you also have to hand in the IP of the local machine.
If you just use the remote one and replica=2, then you get:

`msg: error running gluster (/sbin/gluster volume create gv0 replica 2 transport tcp 10.0.170.127:/data force) command (rc=1): number of bricks is not a multiple of replica count`

(having two machines with 
When I do manually:
`gluster volume create gv0 replica 2  10.0.73.108:/data 10.0.170.127:/data force`

I get the right setup:

```
gluster> volume info all
Volume Name: gv0
Type: Replicate
Volume ID: 3dbfcd15-4d8d-4c8f-8abc-160d4dcff013
Status: Created
Number of Bricks: 1 x 2 = 2
Transport-type: tcp
Bricks:
Brick1: 10.0.73.108:/data
Brick2: 10.0.170.127:/data
Options Reconfigured:
performance.readdir-ahead: on
```

With your suggested way, only specifying the remote IP I can only make a distributed setup

On the 10.0.73.108 machine:

```
gluster> volume info all
Volume Name: gv0
Type: Distribute
Volume ID: ca7500b7-8bc1-429c-94f5-76862b99dc0c
Status: Started
Number of Bricks: 1
Transport-type: tcp
Bricks:
Brick1: 10.0.170.127:/data
Options Reconfigured:
performance.readdir-ahead: on
```

I do it now "by hand" via the shell now, since gluster_volume doesn't work.

**Comment by vishr** [comment]
I tried `"{{ (groups['gluster']|difference([inventory_hostname]))|join(',') }}"` as @bcoca suggested, but then it creates brick on all hosts but the current. Somehow setting host to current IP is working, I don't know why. Please reopen the issue.

**Comment by fredrikwidlund** [comment]
"Closing this ticket as the module is not really doing anything wrong, it is just being given information that will make gluster fail."

I tripped over this as well just now. From what I can see gluster does not fail, "gluster peer probe localhost" will report success but warn that it is not needed. Exit status is 0.

**Comment by fredrikwidlund** [comment]
Also the above suggested workaround does not work, the probe stage succeeds, but the volume is not created correctly since the local node is excluded from the set. From our perspective this module is broken with a catch-22 issue. All nodes need to be listed for the volume to be created, but the local node can't be listed since the module bails on the gluster warning that the localhost probe is unnecessary.

**Comment by sklaus** [comment]
shouldn't then not the module to be written as such, that:
a.) takes all IPS for creation
b.) probes only the other nodes?

Why doing a module at all when it doesn't work in all cases?

**Comment by gmaruzz** [comment]
fredrikwidlund is right

**Comment by roryirvine** [comment]
I struggled with this issue for a while, but now I think I've worked out what was going on.

I was supplying a list of cluster member IP addresses, and not setting a value for 'host'.

If host isn't set explicitly, the module sets it using 'socket.gethostname()' - ie. it's using a hostname, not an IP address.

Setting 'host' explicitly to be the host's own IP address causes it to correctly be excluded from the list of peers to probe, and suddenly the module works correctly!

For reference, my task looks something like this:

```
- name: Configure gluster volume
  gluster_volume:
    state: present
    name: "{{ gluster_volume_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: 2
    cluster: "{{ gluster_nodes }}"
    host: "{{ ansible_default_ipv4.address }}"
    transport: tcp
  run_once: true
```

**Comment by gmaruzz** [comment]
thx!!!!

On Fri, Nov 20, 2015 at 3:32 PM, Rory Irvine notifications@github.com
wrote:

> I struggled with this issue for a while, but now I think I've worked out
> what was going on.
> 
> I was supplying a list of cluster member IP addresses, and not setting a
> value for 'host'.
> 
> If host isn't set explicitly, the module sets it using
> 'socket.gethostname()' - ie. it's using a hostname, not an IP address.
> 
> Setting 'host' explicitly to be the host's own IP address causes it to
> correctly be excluded from the list of peers to probe, and suddenly the
> module works correctly!
> 
> For reference, my task looks something like this:
> - name: Configure gluster volume
>   gluster_volume:
>     state: present
>     name: "{{ gluster_volume_name }}"
>     brick: "{{ gluster_brick_dir }}"
>     replicas: 2
>     cluster: "{{ gluster_nodes }}"
>     host: "{{ ansible_default_ipv4.address }}"
>     transport: tcp
>   run_once: true
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-extras/issues/659#issuecomment-158416619
> .

## 

Sincerely,

Giovanni Maruzzelli
Cell : +39-347-2665618

**Comment by violuke** [comment]
roryirvine's solution with setting the host didn't work for me, but it did prompt me to try:

```
host: "{{ inventory_hostname }}"
```

Which did work, so thanks. Hopefully this helps someone else.

**Comment by karimtabet** [comment]
@bcoca 's solution seems to have syntax issues. I managed to get it to work with this:

`{{ groups.glusterssl|difference([inventory_hostname]) }}`

**Comment by freephile** [comment]
I'm still running into this exact problem, and no suggested workaround is helping.  I'm using the latest versions of gluster, ansible, and using the exact same playbook code that has been published here and elsewhere.  I can execute the probe by hand, but when ansible tries to probe, it fails.  So this proves it's not a firewall or permission problem

`fatal: [10.0.50.161]: FAILED! => {"changed": false, "failed": true, "msg": "failed to probe peer 10.0.50.165 on 10.0.50.161"}`
v.
`[meza-ansible@ip-10-0-50-161 ~]$ sudo gluster peer probe 10.0.50.165
peer probe: success. Host 10.0.50.165 port 24007 already in peer list`
