### ISSUE TITLE
ufw document issue: no src/dest in options section

### ISSUE THREAD

**Issue by linbo** [ansible/ansible-modules-extras#669]
http://docs.ansible.com/ufw_module.html

Examples use src/dest option, but they don't explain in Options section, only can find from_ip and to_ip, are they same thing?

```
ufw: rule=deny route=yes src=1.2.3.0/24 dest=4.5.6.0/24
```

**Comment by bcoca** [comment]
they are aliases, which are documented in the module but not shown in the docs (need to fix that)
