### ISSUE TITLE
Slack module fail for private tokens to private channels ? 

### ISSUE THREAD

**Issue by ofreshy** [ansible/ansible-modules-extras#675]
Hi there, 
I recently started using the slack ansible module. 
I generated a _private_ token webhook from here :
  http://my.slack.com/services/new/incoming-webhook
so I can test my code. 

I tested the token by sending a message from a web requester and it works. 

However, when using Ansible to send the message, the task fails, and I get a 500 error (but no output).
The task is quite simple : 

```
      local_action: slack username=offer channel="@offer"  msg="Test Integration Ansible" token="XXX/YYY/ZZZ"
```

error message is ;

```
msg:  failed to send payload={"username": "offer", "text": "Test Integration Ansible", "link_names": 1, "channel": "#@offer", "icon_url": "http://www.ansible.com/favicon.ico"} to https://hooks.slack.com/services/[obscured]: HTTP Error 500: Server Error
```

Notice that ansible prepend # to the channel name - this may try and send the message as public. Could that be the problem? 

Looking forward to hearing from you.

Best, 
Offer

**Comment by ofreshy** [comment]
Update: 
When testing the same task / code with a public token , it works. 
So it seems that this is a valid issue.

**Comment by gregdek** [comment]
cc: @ramondelafuente

**Comment by bcoca** [comment]
can you run with -vvvv?

**Comment by ramondelafuente** [comment]
This seems to be fixed in https://github.com/ansible/ansible-modules-extras/pull/218

**Comment by ofreshy** [comment]
Running with -vvvv below: 

```
<host_name> ESTABLISH CONNECTION FOR USER: root
<host_name> REMOTE_MODULE slack username=offer channel= msg="Testing Ansible Integration - private to private token" token="/XXX/YYY/ZZZ"
<host_name> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/osharabi/.ansible/cp/ansible-ssh-%h" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 host_name /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436190335.3-79444504505227 && echo $HOME/.ansible/tmp/ansible-tmp-1436190335.3-79444504505227'
<host_name> PUT /var/folders/z5/wjbt340j3d55qrrm69wg07400000gn/T/tmptwTGPe TO /root/.ansible/tmp/ansible-tmp-1436190335.3-79444504505227/slack
<host_name> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/osharabi/.ansible/cp/ansible-ssh-%h" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 host_name /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1436190335.3-79444504505227/slack; rm -rf /root/.ansible/tmp/ansible-tmp-1436190335.3-79444504505227/ >/dev/null 2>&1'
failed: [host_name] => {"failed": true}
msg:  failed to send payload={"username": "offer", "text": "Testing Ansible Integration - private to private token", "link_names": 1, "channel": "#@offer", "icon_url": "http://www.ansible.com/favicon.ico"} to https://hooks.slack.com/services/[obscured]: HTTP Error 500: Server Error
```

**Comment by ofreshy** [comment]
Thanks @ramondelafuente, 
I guess this is not in production yet?
 I am using Ansible version 1.9.0.1

**Comment by ramondelafuente** [comment]
No, as far as I can tell this is fixed in devel (mind you I haven't _tested_ this fix, but it looks to me that it  addresses your exact problem) but not in any released version. I expect it to be in the next release. @gregdek ?

**Comment by ofreshy** [comment]
OK, thanks guys. 
I have generated a public key since which I use to notify public channels, so this is not a blocking issue for me anymore, but wanted you to be aware. Since you are already and fixed this, I think that I can close this issue. Thanks for your help !
