### ISSUE TITLE
Are you interested in a module for editing plist files?

### ISSUE THREAD

**Issue by fgimian** [ansible/ansible-modules-extras#679]
Hey there folks, I'm currently [automating my Mac build](https://github.com/fgimian/macbuild) using Ansible (which I love btw) and have recently found the need for a module that modifies plist files.

As such, I've begun developing a module which does this and was wondering if this is something that might be of interest?

The main reason I ask specifically is because all libraries which can edit binary plist files require Python 2.6+, however, I should be able to successfully backport a library called biplist to Python 2.4 so that it may work with Ansible.

Naturally, the questions that arise are:
- Would this library be included in Ansible?
- I doubt the original author cares about Python 2.4 support, would we simply maintain our own fork?

The module would work something like this roughly (still some design work going on):

``` yaml
- name: modify a plist attribute
  plist: domain=com.apple.dock key=magnification value=true state=present
```

Please let me know your thoughts
Fotis

**Comment by bcoca** [comment]
you should post questions like this to the ansible-devel mailing list or IRC.

I believe there was already an effort to do this but named it 'defaults' IIRC, in any case i can see how those managing OS X workstations would like this, so I would say yes.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- Development list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
