### ISSUE TITLE
Add abilit for known_hosts module to manage multiple keys per host

### ISSUE THREAD

**Issue by letompouce** [ansible/ansible-modules-extras#691]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
  configured module search path = None
##### Ansible Configuration:

Default
##### Environment:

N/A
##### Summary:

The known_hosts module seems to replace the file instead of editing it.
##### Steps To Reproduce:

```
- name: tell the host about our servers it might want to ssh to
  known_hosts:
    host='example.com'
    path='/etc/ssh/ssh_known_hosts'
    key="{{ item }}"
  with_items:
    - "example.com ssh-rsa AAAAAxxxxxxxx"
    - "example.com ssh-ed25519 AAAAAyyyyyyyy"
```
##### Expected Results:

The known_host file should have both keys added in.
##### Actual Results:

The known_hosts file only has the last key added in, the first one has been overwritten.

**Comment by bcoca** [comment]
the file gets copied, the copy gets edited and put back into place, with_ happens serially so the 2nd instance should copy the file with the first instance already there. 

The only thing i can think of is the OS returning that the copy was successful before it actually was and creating a race condition that the 2nd item in loop is hitting.

**Comment by abadger** [comment]
The current code of the known_hosts module manages a single key per host.  In your example you are trying to register two keys for the host.  So known_hosts ends up removing the first newly added key and replacing it with the second.

If someone has time, they could add an `exclusive` parameter similar to what authorized_keys has: http://docs.ansible.com/authorized_key_module.html to allow multiple keys.

**Comment by bcoca** [comment]
hosts are allowed to have a key per type, so unique on host is incorrect
