### ISSUE TITLE
SSL issue using Hipchat

### ISSUE THREAD

**Issue by ssenaria** [ansible/ansible-modules-extras#759]
Running v1.9.2  and running into an issue with Hipchat's module. It was working prior to me updating all the modules.

```
# ansible --version
ansible 1.9.2 (stable-1.9 f074c6ad35) last updated 2015/07/24 15:57:48 (GMT -400)
    lib/ansible/modules/core: (detached HEAD eda33a45e0) last updated 2015/07/24 16:08:00 (GMT-400)
    lib/ansible/modules/extras: (detached HEAD 8c01513e1e) last updated 2015/07/24 16:08:00 (GMT -400)
    v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/07/24 16:08:03 (GMT-400)
    v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/07/24 16:08:08 (GMT -400)
    configured module search path = None
```

Output of task:

```
TASK: [client_install | announce_hipchat] *************************************
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
File "/home/deployment/.ansible/tmp/ansible-tmp-1437769014.82-134926666743109/hipchat", line 1871, in ?
PROTOCOL = ssl.PROTOCOL_TLSv1
NameError: name 'ssl' is not defined
```

**Comment by bcoca** [comment]
it seems you are running 1.9.2 checkout of ansible but current devel of modules, that will create incompatibilities when the modules are expecting code that only exists in the devel version of ansible.

for 1.9.2, these are the expected refs for the submodules:
  lib/ansible/modules/core: (detached HEAD b35f1421d4) last updated 2015/07/17 23:02:26 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f8f2ba8c35) last updated 2015/07/17 23:02:26 (GMT -400)

**Comment by abadger** [comment]
This might also be caused by not having the ssl module (for instance, on older versions of python) on the managed node.  I've just pushed a fix for that to the ansible/ansible repository.  Since hipchat uses an https:// url, though, I'm not sure if you'll be able to use the hipchat module without an ssl module available on the machine.

**Comment by ssenaria** [comment]
I'll try what Brian suggest but nothing on the machine has changed other than updating the ansible working directory.

On Fri, Jul 24, 2015 at 3:12 PM -0700, "Toshio Kuratomi" <notifications@github.com<mailto:notifications@github.com>> wrote:

This might also be caused by not having the ssl module (for instance, on older versions of python) on the managed node. I've just pushed a fix for that to the ansible/ansible repository. Since hipchat uses an https:// url, though, I'm not sure if you'll be able to use the hipchat module without an ssl module available on the machine.

##
