### ISSUE TITLE
no monitor defined for node causes stack trace bigip_facts

### ISSUE THREAD

**Issue by perzizzle** [ansible/ansible-modules-extras#771]
Ansible Version: 1.8.2

Ansible Configuration: n/a

Environment: RHEL 6.5

Summary:
If there is no monitor defined for a node, bigip_facts returns the following stack trace. 

```
ServerError: Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/NodeAddressV2::get_monitor_instance()
Exception: Common::OperationFailed
        primary_error_code   : 16908342 (0x01020036)
        secondary_error_code : 0
        error_string         : 01020036:3: The requested monitor instance (/Common/icmp 192.168.1.1 0 node) was not found.'
```

Suggest wrapping in a try/catch to handle this condition.

Steps To Reproduce:

Create node with no monitor defined then run bigip_facts against it with include=node

Expected Results:

I would expect it to return a status of unknown.

**Comment by bcoca** [comment]
cc @mhite

**Comment by mhite** [comment]
What version of BIG-IP LTM software are you having this problem with? Thanks.

**Comment by perzizzle** [comment]
I am on 11.5.1 build 7.0.167

**Comment by mhite** [comment]
I am unable to recreate this with the steps provided.

Specifically, I created a node with no monitor:

```
ltm node /NETLAB/1.1.1.1 {
    address 1.1.1.1
    description test
    monitor none
    partition NETLAB
    session monitor-enabled
}
```

I then ran the following playbook:

```
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Collect BIG-IP facts
    local_action: >
      bigip_facts
      server=mybigip
      user=myuser
      password=mypass
      session=true
      include=node
```

I launched the playbook with the following command:

```
ansible-playbook -i ./inv ../ansible-playbooks/f5/facts.yml
```

The play succeeded:

```
PLAY ****************************************************************************

TASK [Collect BIG-IP facts] *****************************************************
ok: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

Upon closer examination of the BIG-IP API exception, this actually looks like the F5 is unable to resolve what it thinks is the associated monitor ("/Common/icmp") while it is composing the API response. I'd guess that the BIG-IP's internal configuration data structure became corrupt. Perhaps a restart may help? (I know that's a terrible suggestion, but I'm at a loss.)

What does the exact configuration for your node look like from tmsh output? Let's make sure we are comparing apples to apples. Do a 'list ltm node NODENAME' and paste it in this ticket.

If the configuration indeed looks sane, you might try this:

https://support.f5.com/kb/en-us/solutions/public/13000/000/sol13030.html

(Obviously make sure you do stuff like this under a maintenance window with appropriate caution. Caveat emptor, etc.)

Good luck and let me know how it goes.

**Comment by perzizzle** [comment]
Here is the output of the tmsh command:

# list ltm node NodeName

ltm node NodeName {
    address 123.456.789
    monitor gateway_icmp
    session monitor-enabled
    state up
}

It has state up so I would have thought the monitor is working... I'm not sure what this means. I realize this is a different node than my original complaint but it appeared interesting. It has a monitor defined but causes the same stack trace.

**Comment by perzizzle** [comment]
Furthermore I can get the status with tmsh just fine

show ltm node NodeName

---

## Ltm::Node: NodeName (123.456.789)

Status
  Availability   : available
  State          : enabled
  Reason         : Node address is available
  Monitor        : gateway_icmp
  Monitor Status : up
  Session Status : enabled

Traffic                ServerSide  General
  Bits In                  765.6M        -
  Bits Out                   3.6G        -
  Packets In                 1.0M        -
  Packets Out                1.1M        -
  Current Connections           1        -
  Maximum Connections          35        -
  Total Connections        131.2K        -
  Total Requests                -   170.0K
  Current Sessions              -        0

**Comment by perzizzle** [comment]
I can reproduce it by doing:

api.LocalLB.NodeAddressV2.get_monitor_instance(['NodeName'])

Exception: Common::OperationFailed
        primary_error_code   : 16908342 (0x01020036)
        secondary_error_code : 0
        error_string         : 01020036:3: The requested monitor instance (/Common/icmp 123.456.789 0 node) was not found.'

One discrepancy I noticed is the monitor name configured for the node is gateway_icmp but it appears to be trying monitor icmp according to the stack trace.

**Comment by mhite** [comment]
Yeah, I'm definitely thinking there is some weird internal consistency/corruption issue with your system. Also, I'm presuming you are not literally passing  'NodeName'.

**Comment by perzizzle** [comment]
Tangent, have you thought of supporting a name option in the fact module. Rather than grabbing the info on every node in the system grab the info for just the node you specify by name (something similar could be done with pool, virtual servers etc)

**Comment by perzizzle** [comment]
Lol, I just realized you can do this with the filter parameter. Disregard above.

**Comment by mhite** [comment]
Yeah, the 'filter' parameter is available and mostly accomplishes what you want.

**Comment by perzizzle** [comment]
I'll still need to look into what is causing the discrepancy with our configuration. The fact tmsh returns a proper status and I don't see any issues with the modules logic mean I'm gonna close this issue. We have a maintenance window next Wednesday I can do some more drastic troubleshooting measures. Thanks for the help.

**Comment by kamranayub** [comment]
@perzizzle did you ever figure this out? I'm running into the same thing (TOTALLY unrelated to ansible) where we're querying monitor instance state and the F5 GUI has a monitor defined but the API thinks it doesn't (same exact error). Something must be on F5's end here.

**Comment by perzizzle** [comment]
Sorry, this email slipped through the cracks. In our instance I believe it was the result of upgrading our gear from old versions and the api not supporting old health monitors. I changed our health monitors to use icmp instead of gateway icmp and it started to work. THat and I use the filter parameter to only get the status of devices I care about. @kamranayub
