### ISSUE TITLE
Fatal error trying to create glusterfs volume

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-extras#774]
I'm running into an issue trying to create a volume where I'm getting a fatal error as follow:

```
TASK: [create gluster volume] ************************************************* 
failed: [gluster-node01] => {"failed": true}
msg: failed to probe peer gluster-node01

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 

gluster-node01             : ok=10   changed=0    unreachable=0    failed=1   
gluster-node02             : ok=10   changed=0    unreachable=0    failed=1  
```

However in the cmd_history.log on the gluster-node01 host I see the following:

```
: peer probe gluster-node01 : SUCCESS : Probe on localhost not needed
```

Ansible Task:

```
  - name: create gluster volume
    gluster_volume: state=present name=gv0 brick=/export/sdb1/brick rebalance=yes cluster='gluster-node01,gluster-node02'
    run_once: true
```

This is almost verbatim out of the examples so I'm not sure what I'm doing wrong here.

**Comment by bcoca** [comment]
are you adding the node itself to the cluster option? this won't work, each node need the cluster option to only include other nodes.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by elouanKeryell-Even** [comment]
I encountered the exact same issue, with a `SUCCESS` log line in `/var/log/glusterfs/cmd_history.log`. Mysteriously, I just re-executed the playbook and this time it worked fine. My playbook usually executes without a problem, dunno why it failed this time.

**Comment by metal3d** [comment]
Exactly the same, the volume is started but ansibles says it failed
