### ISSUE TITLE
test issue, please ignore

### ISSUE THREAD

**Issue by gregdek** [ansible/ansible-modules-extras#800]
Hi. This is a test issue for determining parseability.

:shipit: 

:warning:

**Comment by gregdek** [comment]
Reviewers who think a PR is good should upvote with the text "shipit" with colons on both sides, so that the following icon appears: :shipit:

Reviewers who think a PR is not good should downvote with the text "warning" with colons on both sides, so that the following icon appears: :warning:  Also be sure to enumerate the changes required.

**Comment by resmo** [comment]
:shipit: now

**Comment by gregdek** [comment]
Argh! It doesn't work; Google just includes the emoji. That makes me sad.

**Comment by gregdek** [comment]
(That is to say, I can't search my gmail for it.)

**Comment by gregdek** [comment]
OK, so I'm opting for the plain text: "shipit" or "needs_revision". I'll update my workflow to include these instructions. We'll see if that helps. Thanks for testing!
