### ISSUE TITLE
maven_artifact not working

### ISSUE THREAD

**Issue by carcarlo** [ansible/ansible-modules-extras#813]
Hello
I've installed ansible 2.0 from GitHub building this RPM ansible-2.0.0-0.git201508070432.48840ad.devel.noarch.rpm.

When I try to download an artifact whit the command:
ansible 1.1.2.195 -m maven_artifact -a "group_id=org.apache.commons artifact_id=commons-collections dest=/tmp/commons-collections-latest.jar"  -u root  -k

I get the following error:

atal: [1.1.2.195]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1438940214.19-9647185694305/maven_artifact\", line 2825, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1438940214.19-9647185694305/maven_artifact\", line 313, in main\r\n    downloader = MavenDownloader(module, repository_url, repository_username, repository_password)\r\nTypeError: **init**() takes at most 3 arguments (5 given)\r\n", "parsed": false}

**Comment by bcoca** [comment]
cc @chrisisbeef

**Comment by sirkubax** [comment]
ansible -i ~/ansible/etc/inv/inventory-qa some-host -m maven_artifact -a "group_id=org.jmxtrans artifact_id=jmxtrans version=251 repository_url=http://central.maven.org/maven2 dest=/tmp" -vvv

msg": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1439822083.39-247708723227590/maven_artifact\", line 2645, in <module>\r\n    main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1439822083.39-247708723227590/maven_artifact\", line 309, in main\r\n    downloader = MavenDownloader(module, repository_url, repository_username, repository_password)\r\nTypeError: **init**() takes at most 3 arguments (5 given)\r\nOpenSSH_6.7p1 Ubuntu-5ubuntu1.2, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data

**Comment by sirkubax** [comment]
quick print in line 309:
print '%s, %s, %s' % (repository_url, repository_username, repository_password)
gives output:
http://central.maven.org/maven2, None, None

while the provided class requires:
class MavenDownloader:
      def **init**(self, module, base="http://repo1.maven.org/maven2"):

**Comment by sirkubax** [comment]
so as a Quick fix
    -    downloader = MavenDownloader(module, repository_url,  repository_username, repository_password)
    +   downloader = MavenDownloader(module, repository_url)

and few line later, the extension is NoneType when empty, so when running the module, be sure to provide argument 'extension=deb" (or something)

   if os.path.isdir(dest):
          dest = dest + "/" + artifact_id + "-" + version + "." + extension

**Comment by chrisisbeef** [comment]
I'll look at this this week. Thanks!

**Comment by chrisisbeef** [comment]
In case you missed my comment on the PR - this is a good find and the PR is +1 by me.

**Comment by bcoca** [comment]
fixed via merged #845
