### ISSUE TITLE
Consul - retrieve value from KV store

### ISSUE THREAD

**Issue by kai11** [ansible/ansible-modules-extras#818]
Issue Type: Feature Idea
Ansible Version: 2.0
Environment: Ubuntu 12.04

Both documentation http://docs.ansible.com/ansible/consul_kv_module.html 
and code https://github.com/ansible/ansible-modules-extras/blob/devel/clustering/consul_kv.py
don't have suggest way to retrieve value without modifying it.
Acquire\Release pattern don't work for my use case - I need value to pass it to other module.
I can use consul API directly, but this module is "cleaner" solution.

I think best option to retrieve values will be state=present and empty value.

**Comment by kai11** [comment]
lookup('consul_kv', 'url,key') probably better choice for retrieval API.

**Comment by bcoca** [comment]
closing as dupe of https://github.com/ansible/ansible/issues/11042

**Comment by bcoca** [comment]
closing as the feature was added in https://github.com/ansible/ansible/pull/10078
