### ISSUE TITLE
[bug] [locale_gen] Unable to manage locales with spaces

### ISSUE THREAD

**Issue by NielsH** [ansible/ansible-modules-extras#823]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 1.9.2
##### Ansible Configuration:

No custom changes
##### Environment:

Ansible is running from Debian 8 amd64 - it is being used to manage another host with Debian 8.1.
##### Summary:

When using locale_gen it is possible to add locales as that are represented in one word. However it not possible to add locales that contain spaces.
For example this one:

```
$ grep 'en_US ISO-8859-1' /usr/share/i18n/SUPPORTED         
en_US ISO-8859-1
```
##### Steps To Reproduce:
- Start a new Debian 8 server. I use Linode myself with Debian 8.1 and the following kernel: `(Latest 64 bit (4.1.0-x86_64-linode59))`
- Run the following playbook: https://gist.github.com/NielsH/73b3c0db415c250541dd
  with the following options: `$ ansible-playbook -s main.yml -i hosts -u root --ask-pass -C`  
  The issue will also appear without the -C flag
##### Expected Results:

I expect all 3 locales to be generated correctly.
##### Actual Results:

The first 2 items work correctly, as they do not have spaces. The third one has a space, so it does not work, even though it is quoted in the playbook:

```
$ ansible-playbook -s main.yml -i hosts -u root --ask-pass -C
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [139.162.154.71]

TASK: [Generate required locales] ********************************************* 
changed: [139.162.154.71] => (item=en_GB.UTF-8)
ok: [139.162.154.71] => (item=en_US.UTF-8)
failed: [139.162.154.71] => (item=en_US ISO-8859-1) => {"failed": true, "item": "en_US ISO-8859-1"}
msg: this module requires key=value arguments (['name=en_US', 'ISO-8859-1', 'state=present', 'CHECKMODE=True'])

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/main.retry

139.162.154.71             : ok=1    changed=0    unreachable=0    failed=1   
```

As you can see it interprets the space in the locale incorrectly, they become 2 separate words.

I have also tried double-quoting it as can be seen in this playbook: https://gist.github.com/NielsH/23dc2fb64c1b4d3064f8
The results then become as such: 

```
ansible-playbook -s main.yml -i hosts -u root --ask-pass -C
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [139.162.154.71]

TASK: [Generate required locales] ********************************************* 
changed: [139.162.154.71] => (item=en_GB.UTF-8)
ok: [139.162.154.71] => (item=en_US.UTF-8)
failed: [139.162.154.71] => (item='en_US ISO-8859-1') => {"failed": true, "item": "'en_US ISO-8859-1'"}
msg: The locales you've entered is not available on your system.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/main.retry

139.162.154.71             : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by sistemasdistal** [comment]
The file /usr/share/i18n/SUPPORTED is a two column file with the first column containing the name of the locale and the second column the corresponding encoding.

Take for instance my country (Argentina). There is es_AR.UTF-8 with encoding UTF-8 and there is es_AR with encoding ISO-8859-1:

```
 $ grep es_AR /usr/share/i18n/SUPPORTED
  es_AR.UTF-8 UTF-8
  es_AR ISO-8859-1
```

This means that if I want to use the ISO-8859-1 locale the name parameter for locale_gen es 'es_AR', and not the full line 'es_AR ISO-8859-1'.

In your case, this should work as expected:

```

---

- hosts: all
  tasks:
    - name: Generate required locales
      locale_gen: name={{ item }} state=present
      with_items:
        - "en_GB.UTF-8"
        - "en_US.UTF-8"
        - "en_US"
```

**Comment by NielsH** [comment]
Thanks for the clarification on how this works. I've adjusted my playbooks and it works correctly now, cheers!
