### ISSUE TITLE
Support for "git config" and "git remote" wanted?

### ISSUE THREAD

**Issue by jarmoni** [ansible/ansible-modules-extras#835]
I use Ansible to 'prepare' many developer-workstations which includes cloning several git-repositories from different origin (github, bitbucket, partner- and inhouse-repositories,...) and also have to set different per-repository config and remotes. The existing git module mainly deals with cloning of repositories and has little support for manipulating config and remotes. I'd like to introduce 2 small modules (git_config and git_remote) to handle these use-cases.

Are there any interrests to have this functionality inside the 'offiicial' core-module? If so, I would make a pull-request. But maybe these tasks are 'too trivial' for most users and I better deploy my modules locally only. So what's your opinion?

Cheers,
Micha

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by djmattyg007** [comment]
Was there any follow-up to this? It's very difficult to find out what discussions took place when they're redirected to another place of discussion without any reference to where those discussions were moved to. You're just doomed to have the same questions asked over and over, or worse, more people with bigger and better ideas not spreading them due to no desire to go elsewhere to detail their idea.

**Comment by djmattyg007** [comment]
Looks like the discussion was followed up here: https://groups.google.com/forum/#!searchin/ansible-devel/git$20config/ansible-devel/IFakssRxdA4/w83PBS-5EAAJ

Personally I think it's ridiculous that questions regarding development of the repository are redirected elsewhere, with zero personal response provided when doing so.
