### ISSUE TITLE
Can't pass token to Consul lookup plugin?

### ISSUE THREAD

**Issue by ssenaria** [ansible/ansible-modules-extras#857]
With ACL enable, I'm not able to query for the value of a key I'm looking up. If I disable ACL, it works fine.

Works fine:

```
 {{ lookup('consul_kv', item, token="mysecretoken") }}
```

Thinking I have the wrong paramter, I tried to force an error. However, no errors are thrown?

```
{{ lookup('consul_kv', item, token123="mysecretoken") }}
```

**Comment by abadger** [comment]
From looking at the code, I think that this would work if you do it like this:

```
{{ lookup('consul_kv', item, 'token=mysecretoken') }}
```

If so, this is a different module but the same idea as:
https://github.com/ansible/ansible-modules-core/issues/1968

Could you test if that works?

**Comment by ssenaria** [comment]
```
fatal: [127.0.0.1] => Failed to template deploy_list="{{ item | replace("deploylist/REL-134/",'') }}-{{ lookup('consul_kv', item, 'token=f45cbd0b-5022-47ab-8640-4eaa7c1f40f1') }}": 

Unexpected error in during lookup: run() got multiple values for keyword argument 'inject'
```

**Comment by abadger** [comment]
Oh... You're on 1.9.2?  Try this:

```
{{ lookup('consul_kv', item + ' token=mysecretoken') }}
```

Sorry, I've been working on devel nonstop for a few weeks and so I forgot that anyone might be running releases ;-)

**Comment by abadger** [comment]
@ssenaria Did that work?

**Comment by ssenaria** [comment]
YES! That did it. Thanks a lot!
