### ISSUE TITLE
Firewalld - adding IP to zone doesn't work

### ISSUE THREAD

**Issue by Sh4d** [ansible/ansible-modules-extras#894]
Pretty simple line like this just isn't working:

`- firewalld: source=1.2.3.4 state=enabled zone=trusted`

Adding the rule manually with firewall-cmd results in ansible showing OK instead of changed, so it's checking the existing state properly but isn't adding new rules.

This is with a centos 7 machine (up to date) running firewalld 0.3.9

**Comment by abadger** [comment]
@maxamillion do you have time to look into what's going wrong here?

**Comment by maxamillion** [comment]
This appears to fix. https://github.com/analogbyte/ansible-modules-extras/commit/39eb3807f3497fffeea19183691b54489a811239
