### ISSUE TITLE
VMware - Add Support for Maintenance Mode and Offline Bundle Install

### ISSUE THREAD

**Issue by jjahns** [ansible/ansible-modules-extras#895]
I have added a couple of modules that will aid in the support of installing an offline bundle, as well as placing a host into maintenance mode / VSAN-compliant maintenance mode.

**Comment by jjahns** [comment]
Commit is at.
https://github.com/jjahns/ansible-modules-extras/commit/3dcdbce793da77e74b60bc097f7532ac573b220c

**Comment by abadger** [comment]
@jjahns If you'd care to submit a pull request with the modules someone will be happy to take a look.

**Comment by chrrrles** [comment]
@jjahns - Commented on your commit.  May you take a look?  There have been changes to the vmware code in devel, and it would be nice to align new code with this.

**Comment by jjahns** [comment]
I am closing the request because of some internal items that have prevented me from working on this.
