### ISSUE TITLE
ec2_eni should allow security groups to be specified by name

### ISSUE THREAD

**Issue by bretmartin** [ansible/ansible-modules-extras#927]
I'm opening this as an issue for discussion before I prepare a pull request. `ec2_eni` has a `security_groups` parameter which takes a list of security group IDs. I want to add support for specifying security groups by name. If I were writing the whole module, I'd probably match the `ec2` parameters of `group` and `group_id` but I assume `security_groups` was chosed to be more explicit and match AWS terminology (makes sense to me). So how should I implement this?
- Should `security_groups` accept either names or IDs? That seems messy.
- Should there be another parameter like `security_group_names` that is mutually exclusive with `security_groups`?
- Should we move to `group` and `group_id` to match `ec2` and have `security_groups` be an alias? But the fuller parameter name seems correct...

@wimnat @evanccnyc @rickmendes

**Comment by bretmartin** [comment]
I took a whack at this: https://github.com/h3biomed/ansible-modules-extras/commit/be9da023831594318947eb295fb6a4021c2a11d8

But I'm not wedded to doing it this way.

**Comment by wimnat** [comment]
I'm not opposed to the PR but from a ideological point of view, I don't see it as necessary.

People seem to treat Ansible as a scripting language to do stuff but I don't see it that way.  I see it as a Desired State Configuration tool.  Therefore, if you were creating a playbook defining an ENI that refers to a particular sec_group, you should also be defining the sec_group itself.  If you did that, then you'd get back the ID every time you ran the playbook and it could just be passed to the eni module.

Anywho, i know lots of people don't think that way so i'll take a look at your code when i get a chance, probably thurs.

Regarding the naming, i always look at matching the boto parameters and most other modules do to.  The ec2 module is not really a good point of reference for many Ansible things!

**Comment by bretmartin** [comment]
@wimnat I completely understand your viewpoint and I agree in general. Let me explain my use case a little bit. I have a playbook that defines my VPC and most of the networking-related entities in it, including security groups. I have a separate playbook that provisions EC2 instances.
- I could certainly combine those two playbooks so I could store all the SG IDs from their creation tasks. (I assume I could set a fact that was a dict of names to IDs? I haven't tried anything like that yet.) I have them separated for a variety of reasons -- reduced blast radius; they're likely to be modified and run by different people; keeping playbooks runs reasonable length; etc.
- I could certainly look up SG IDs in the second playbook and pass those to `ec2_eni`. I thought about doing this too, but once it became clear how many lines of playbook this was, vs. how many lines of module code, I leaned toward the module.

I guess my thinking was that when I see something of general utility for a module, within reason, it makes sense to try to add it to the module. Some stuff would clearly be over the line -- like, say, creating an EC2 instance to go along with your ENI. That would be too much overlap with `ec2` and clearly outside scope here.

**Comment by evanccnyc** [comment]
I can see both sides of this argument. I have found times where I would prefer to keep everything in one large desired state configuration, but have had to run one off scripts that I would prefer to have the Security Group name.

I tend towards giving people more options, so if they have to run one off stuff it can be used.

**Comment by ghost** [comment]
I am guilty of adding security name support to the ec2_elb module so I wouldn't mind having it on the ec2_eni module. The reason this comes in handy from my team's perspective is we have several environments where we use 'static' inventory to build things out. In those cases, we always know the name so names work well.

I can go the other way too as we are currently adding persistence support to our playbooks so each playbook can persist the aws_resource_id our roles expose when they create something. This allows us to have more modular playbooks because each one can do one thing knowing it can get its inputs from the persistence layer. This is to replace one of the things we like best about CloudFormation.

In the ec2_elb_lb case I added security_group_names as a separate list from the existing security_group_ids parameter.

So it won't bother me at all if this goes up as a PR or not. Thanks.

**Comment by bretmartin** [comment]
Thanks everyone! I'll give my current work another close look and then PR this.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
