### ISSUE TITLE
Any plans to create a LXD module?

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible-modules-extras#970]
Hi,
Is anyone working on creating something similar to lxd_container_module but for LXD (http://www.ubuntu.com/cloud/tools/lxd)?

Given LXD's easy of use in scenarios with remote servers behind firewall, it looks very well suited for execution on jumphosts.
Thx

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
