### ISSUE TITLE
Add a mysql_query module

### ISSUE THREAD

**Issue by tersmitten** [ansible/ansible-modules-extras#980]
I would be nice to have a module to execute queries. For instance:
- From a variable
- From a local file (same as `archive` module)
- From a remote file (same as `archive` module)

**Comment by robynbergeron** [comment]
@tersmitten --  Thanks for submitting this feature idea. Much appreciated!

We encourage all Ansible community members to submit pull requests to satisfy feature requests. If anyone is interested in contributing this as a new module, you can consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by kiwifellows** [comment]
Hi,
I'll be working on this as a new module. 
Proposed approach is outlined below.
**New module called 'mysql_query'**
Features:
- select, insert, delete, update
- returns result set or error if can't connect

Parameters:
- sqlstring (from a variable), database (host, credentials etc...)

Behaviour:
SELECT returns result set
INSERT returns new ID if an auto increment, or returns true if affected rows=1
DELETE returns number of affected rows
UPDATE returns number of affected rows

Out of scope:
Doesn't use a local file or remote file. Reason: The existing mysql module does this quite nicely using the "import" feature

**Comment by kiwifellows** [comment]
Hi @tersmitten and @robynbergeron I've currently started a dev version of this. However it is currently sitting in another repository. Once I get some feedback etc.. then Ill do a PR to put it into ansible-modules-extra repo.
Let me know what you think below:
https://github.com/teemops/ansible-modules/blob/master/database/mysql_query.py

It also needs some work on doco.

Cheers,

Ben
(Currently building up a repo of special ansible modules to include in extras for features such as mysql queries, SQL Server tasks, azure) https://github.com/teemops/ansible-modules

**Comment by Jmainguy** [comment]
@kiwifellows Have a look at https://github.com/ansible/ansible-modules-extras/pull/1593.
