### ISSUE TITLE
About option of win_package

### ISSUE THREAD

**Issue by tksarah** [ansible/ansible-modules-extras#984]
I found two issue.

I think Product-ID parameter is not "product_id" , is it "productid"?
Also , it seems the required columns is "yes".

```
fatal: [10.1.1.6]: FAILED! => {"changed": false, "failed": true, "msg": "Missing required argument: productid"
```

Therefore , it take a mistake about "ProductId" below an example on document of win_package:

```
# Playbook example
  - name: Install the vc thingy
    win_package:
      name="Microsoft Visual C thingy"
      path="http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe"
      ProductId="{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}"
      Arguments="/install /passive /norestart"
```

**Comment by robynbergeron** [comment]
@tksarah -- thanks for submitting this bug report.

@trondhindenes -- letting you know about this. Also: @trondhindenes -- if you get a moment, can you add your github ID to the author line in this module? :) Thanks!

**Comment by robynbergeron** [comment]
[module: windows/win_package.py]

**Comment by trondhindenes** [comment]
thanks for letting me know @tksarah. I will have a look at it right away.

**Comment by trondhindenes** [comment]
@robynbergeron as for author: my name/email is in there, isnt that the standard?

**Comment by robynbergeron** [comment]
@trondhindenes -- @gregdek went through most of the modules (probably missed some things) and added github IDs. Useful so we can actually more efficiently ping people on github when we need to, and if/when there is a glorious future where we can automate pinging of people at the very least, this is helpful for that as well. :)

It's also in the module guidelines as they appear today (name + github ID at least, is what I think it says) -- i'm not really one to be super crazy about details, but it really does help us out as far as triaging things and trying to smooth things out and be more responsive. :)

Thankfully I already knew yours and you have one that actually relates to your name, in the event I didn't know :) But adding it would be stellar.

**Comment by robynbergeron** [comment]
@trondhindenes -- folks have been following this sort of convention as FYI. Also: Not to get into too many details... but... thanks for submitting a fix for this so fast :) 

author: "Robyn Bergeron (@robynbergeron)"

**Comment by trondhindenes** [comment]
okay. I knew about name but not github ID. https://github.com/ansible/ansible/blob/devel/examples/DOCUMENTATION.yml also just uses name.

**Comment by robynbergeron** [comment]
Ahh, good catch. :) I'll get that fixed up.
